#include <ansi.h>
mapping *wheres=({
          
      (["chinese":                "大理北门",
       "weizhi" :              "/d/dali/beimen",]),  
      (["chinese":                "梅路小林",
       "weizhi" :              "/d/wanmei/entrance_road",]),  
     (["chinese":                "清音阁",
       "weizhi" :              "d/emei/qingyinge",]),
     (["chinese":                "扬州西门",
       "weizhi" :              "/d/city/ximen",]),
     (["chinese":                "积雪小路",
       "weizhi" :              "/d/xueshan/xuelu06",]),
     (["chinese":                "宝带桥",
       "weizhi" :              "/d/suzhou/baodaiqiao",]),
        (["chinese":                "杭州飞来峰",
       "weizhi" :              "/d/hz/feilaifeng",]),
     (["chinese":                "杭州净慈寺",
       "weizhi" :              "/d/hz/jingcisi",]),
            (["chinese":                "杭州九曲桥",
       "weizhi" :              "/d/hz/juquqiao",]),
       (["chinese":                "扬州中央广场",
       "weizhi" :              "/d/city/guangchang",]),  
      (["chinese":                "杭州断桥",
       "weizhi" :              "/d/hz/duanqiao",]), 
      (["chinese":                "杭州灵隐寺",
       "weizhi" :              "/d/hz/lingyinsi",]), 
      (["chinese":                "星宿日月洞",
       "weizhi" :              "/d/xingxiu/ryd",]), 
      (["chinese":                "武当茶亭",
       "weizhi" :              "/d/wudang/chating",]), 
      (["chinese":                "峨嵋十二盘",
       "weizhi" :              "/d/emei/shierpan3",]), 
      (["chinese":                "峨嵋千佛庵",
       "weizhi" :              "/d/emei/qianfoan",]), 
      (["chinese":                "峨嵋九十九道拐",
       "weizhi" :              "/d/emei/jsjdg1",]), 
      (["chinese":                "明教烈火旗",
       "weizhi" :              "/d/mingjiao/huoqi",]), 
      (["chinese":                "明教锐金旗",
       "weizhi" :              "/d/mingjiao/jinqi",]), 
      (["chinese":                "福州北门",
       "weizhi" :              "/d/fuzhou/beimen",]), 
      (["chinese":                "福州西街",
       "weizhi" :              "/d/fuzhou/xijie",]), 
      (["chinese":                "星宿海沙漠",
       "weizhi" :              "/d/xingxiu/shamo2",]),
      (["chinese":                "少林寺石阶",
       "weizhi" :              "/d/shaolin/shijie4",]),
      (["chinese":                "襄阳丁字路口",
       "weizhi" :              "/d/xiangyang/cross2",]),
      (["chinese":                "华山猢狲愁",
       "weizhi" :              "/d/hs/husun",]),
      (["chinese":                "华山玉女峰",
       "weizhi" :              "/d/hs/yunu",]),
      (["chinese":                "慕容小径",
       "weizhi" :              "/d/mr/xiaojing1-2",]),
      (["chinese":                "慕容柳树林",
       "weizhi" :              "/d/mr/liulin",]),
      (["chinese":                "大理太和大街",
       "weizhi" :              "/d/dali//d/dali/beijie3",]),
      (["chinese":                "苏州城北门",
       "weizhi" :              "/d/suzhou/beimen",]),
      (["chinese":                "苏州城玄妙观",
       "weizhi" :              "/d/suzhou/xuanmiao",]),
      (["chinese":                "少林寺山门殿",
       "weizhi" :              "/d/shaolin/smdian",]),
      (["chinese":                "少林寺走廊",
       "weizhi" :              "/d/shaolin/zoulang7",]),
      (["chinese":                "武当山路",
       "weizhi" :              "/d/wudang/shanlu3",]),
      (["chinese":                "少林寺般若堂九部",
       "weizhi" :              "/d/shaolin/banruo9",]),
      (["chinese":                "雪山山脚",
       "weizhi" :              "/d/xueshan/shanjiao",]),
      (["chinese":                "峨嵋九老洞",
       "weizhi" :              "/d/emei/jiulaodong",]),
       (["chinese":                "峨嵋古德林",
       "weizhi" :              "/d/emei/gudelin1",]),
      (["chinese":                "华山脚下",
       "weizhi" :              "/d/hs/path1",]),});