#define BASE "/d/Dark/cephrin/"
#define ROOMS(x) BASE + "rooms/" + "x"
#define ARMOR(x) BASE + "armor/" + "x"
#define MON(x) BASE + "mon/" + "x"
#define OBJ(x) BASE + "obj/" + "x"
#define WEAP(x) BASE + "weapons/" + "x"
