/* vehicle.c header file */

object *GetShipEnemies();
object *AddShipEnemy(object);
object *RemoveShipEnemy(object);
object GetPilot();
int SetVehicleSize(int);
int GetVehicleSize();
int SetSensorSuite(int);
int GetSensorSuite();
int SetDriveSystem(int x);
int GetDriveSystem();
int SetWeaponSystem(int x);
int GetWeaponSystem();
int SetShieldSystem(int);
int GetShieldSystem();
int SetPrizeBonus(int);
int GetPrizeBonus();
int GetCrystals();
int AddCrystals(int);
int SetCrystals(int);
int GetHasAttacked();
int GetHasMoved();
string SetShipStyle(string);
string GetShipStyle();
string SetVehicleName(string x);
string GetVehicleName();
string SetOwner(string x);
string GetOwner();
string SetCaptain(string x);
string GetCaptain();
string *SetDamagedSystems(string *system);
string *AddDamagedSystem(string system);
string *RemoveDamagedSystem(string system);
string *GetDamagedSystems();
string GetRepairSkill(string system);
int GetDamagedSystem(string system);
string GetClimate();
string GetDriveStatus();
string GetWeaponStatus();
string GetShieldStatus();
int GetDamagedSystem(string system);
string SetCurrentLocation(string);
string GetCurrentLocation();
void eventEncounterShip(object);
int eventMove(mixed dest);
varargs int eventMoveLiving(mixed dest, string outmessage, string inmessage);
int eventScan(object who, string what);
int eventHyperjump(object, string, string, string);
varargs int eventLaunchWeapon(object, object, string);
void SaveVehicle();
void LoadVehicle();
void DeleteVehicle();
void ResetExit();
mixed CanPilot(object, mixed);
varargs mixed CanHyperjump(object, string, string, string);
varargs mixed CanLaunchWeapons(object, object, string);
mixed CanRepair(object, string);
nosave mixed *AddSave(mixed *vars);
string SetUniqueVehicleId();
string GetUniqueVehicleId();
