#ifndef K_MARSH_H
#define K_MARSH_H
#define ITEMS "/wizards/hepualahaole/marsh/item/"
#define MOB "/wizards/hepualahaole/marsh/mob/"
#define ARM "/wizards/hepualahaole/marsh/arm/"
#define WEP "/wizards/hepualahaole/marsh/wep/"
#define ROOMS "/wizards/hepualahaole/marsh/room/"
#define BA  ROOMS "ba/"
#define CAVE  ROOMS "cave/"
#define ELE  ROOMS "ele/"
#define FORT  ROOMS "fort/"
#define FUN  ROOMS "fun/"
#define GAR  ROOMS "gar/"
#define HAM  ROOMS "ham/"
#define SAB  ROOMS "sab/"
#define SPI  ROOMS "spi/"
#define TOWN  ROOMS "town/"
#define UMI  ROOMS "umi/"
#define WATER  ROOMS "water/"
#define HIVE  ROOMS "hive/"
#define NEST  ROOMS "nest/"
#define ARENA  ROOMS "arena/"
#define MARSH ROOMS "marsh/"
#define MARSH2 ROOMS "marsh2/"
#define GRASS ROOMS "grass/"
#endif
