
ADD_EXPERIENCE(L)       LOCAL FUNCTIONS         ADD_EXPERIENCE(L)

NAME
     add_experience() - adds experience points to a living object.

SYNOPSIS
     int add_experience ( int xp ) ;   

DESCRIPTION
     The add_experience() lfun is defined in /std/body/attack.c. It 
     returns and integer equal to the experience added after possible
     adjustments based on character race.

AUTHOR
     Cyanide@Nightfall's Keep



Vertigo Release 0.9         Last change:    13 May 1998               