#define DURG_DIR      "/domains/frostmarches/towns/durgoroth"
#define DURG_OBJ      DURG_DIR "/obj/"
#define DURG_NPC      DURG_DIR "/npc/"
#define DURG_ROOM     DURG_DIR "/room/"
#define DURG_FOOD     DURG_OBJ "/food/"
