mapping allloca = ([
  "扬州城": ({ "/d/city/", "beidajie1", "beidajie2", "beimen", "biaoju",
    "bingqiku", "bingyin", "bingyindamen", "caizhu",
    "chaguan", "dangpu", "datiepu", "dayuan", "dongdajie1", "dongdajie2",
    "dongmen", "dongting", "dongxiang", "duchang", "duchang2", "garments",
    "gbandao", "gbxiaowu", "guangchang", "houyuan", "kedian", "kedian2",
    "kedian3", "lichunyuan", "lichunyuan2", "meigui",
    "ml1", "ml2", "ml3", "ml4", "ml5", "ml6", "ml7",
    "mudan", "nandajie1", "nandajie2", "nanmen", "neizhai",
    "pomiao", "qianzhuang", "shuyuan", "shuyuan2",
    "work", "wumiao", "xidajie1", "xidajie2",
    "ximen", "xiting", "xixiang",
    "yamen", "yaopu", "yaopuls", "ymzhengting", "zahuopu", "zhengting",
    "zuixianlou", "zuixianlou2", "zxlpath",
  }),

  "北京城": ({ "/d/city2/", "alley1", "alley2", "alley3", "andao1", "andao10", "andao7",
    "andao9", "anding", "aobai1", "aobai10", "aobai11", "aobai12", "aobai2",
    "aobai3", "aobai6", "aobai7", "bingqiku", "bingyin1", "bingyin2", "bridge",
    "bridge2", "bridge3", "ceting",
    "chaguan", "chaoyan1", "chaoyan2", "chaoyang", "dangpu", "datiepu", "dating",
    "di_an1", "di_an2", "di_an3", "di_an4", "di_anmen",
    "dongcha1", "dongcha2", "dongchangdamen", "dongmen", "duchang", "duchang2",
    "eproom", "fotang", "guancai1", "guancai2", "haigang",
    "hbridge", "houtai", "huayuan", "huichunt", "jiulou1", "jiulou2", "kang1",
    "kang2", "kang3", "kedian", "kedian1", "kedian2", "kedian3", "kedian4",
    "mapeng", "mianguan", "nandaj1", "nandaj2", "neishi",
    "neitang", "nproom", "qianzhua", "shufang",
    "shuyuan", "shuyuan2", "sproom", "stage", "tian_anm", "tuzai", "wangfu1",
    "wangfu2", "wangfu3", "wenmiao", "wproom", "wuchang", "wuqiku", "xiaotan",
    "xichang1", "xichang2", "xichangdamen", "xidan", "xidan1", "ximen", "ximenwai",
    "xisi", "xisi2", "xiyuan", "yihongyu", "yongding", "zahuopu", "zhengmen",
    "zhulin1", "zhulin2", "zhulin3", "zhulin4", "zhulin5",
  }),

  "白驼山": ({ "/d/baituo/", "bridge", "cao1", "cao2", "caomeide", "caoping", "cave", "cave1", "cedong",
    "chaifang", "changlang", "chufang", "damen", "datiepu", "dating", "dongjie",
    "dongkou", "dongnei", "fang", "fende", "gebi", "guangchang", "houmen", "houyuan",
    "huayuan", "jiudian", "liangong", "menlang", "midao", "mumen", "neishi", "nongshe",
    "restroom", "room1", "room2", "room3", "shanlu", "shanlu1", "shijie", "shulin",
    "shulin1", "storeroom", "tuyuan", "wuqiku", "xiaolu1", "xiaolu2", "xiaolu3",
    "xiaolu4", "xijie", "ximen", "yaofang", "yuanzi", "zhailuo", "zhulin", "zhuyuan",
  }),

  "北京城外": ({ "/d/city2/", "road10", "road9", "road8", "road7", "road6", "road5",
    "road4", "road3", "road2", "road1", "zhuang1", "zhuang2", "zhuang3", "zhuang4",
  }),

  "泉洲": ({ "/d/quanzhou/", "beimen", "haigang", "houyuan", "jiaxing",
    "jxnanmen", "laozhai", "liang", "midao", "mishi", "nanhu", "nanhu1", "nanmen",
    "qzroad1", "qzroad2", "qzroad3", "qzroad4", "qzroad5", "tieqiang", "well",
    "xijie", "yanyu", "zahuopu", "zhongxin",
  }),

  "灵蹴宫": ({ "/d/lingjiu/", "biguan", "caifeng", "changl1", "changl10", "changl11",
    "changl12", "changl13", "changl14", "changl15", "changl2", "changl3",
    "changl4", "changl5", "changl6", "changl7", "changl8", "changl9", "chufang",
    "daban", "dadao1", "dadao2", "damen", "dating", "huayuan", "jian", "liangong",
    "men1", "men2", "men3", "shanjiao", "shufang", "wuqiku", "xianchou",
    "xiaodao1", "xiaodao2",
  }),

  "南阳": ({ "/d/nanyang/", "duchuan", "hanshui1", "hanshui2", "hong-damen", "hong-zoulang",
    "hongniang-zhuang", "hubudatang", "kedian1", "matou1", "matou2", "nanyang",
    "ruzhou", "shanmen", "shijie1", "shijie2", "shijie3", "shijie4", "shijie5",
    "shijie6", "shijie7", "wangxi-lu", "xiaozheng", "ximen", "xingbudatang",
    "yamen-damen", "yamen-datang", "yidao", "yidao2", "yidao3", "yingbin-lou1",
  }),

  "逍遥派邻近": ({ "/d/xiaoyao/", "bingqif", "damen", "fangjian1", "fangjian2", "gudi", "hubian",
    "liangong", "midao1", "midao2", "midao3", "mubanlu", "muwu1", "muwu2", "muwu3", "pubu",
    "qingcaop", "shantang", "shidong", "shiji1", "shiji2", "shiji3", "shishi1", "shishi2",
    "shishi3", "shishi4", "shishi5", "shulin1", "shulin2", "shulin3", "tongmen", "xiaodao1",
    "xiaodao2", "xiaodao3", "xiaodao4", "xiaodao5", "xiuxis", "yandong", "yanfeng",
  }),

  "华山村": ({
    "/d/village/", "alley1", "alley2", "bighouse1", "bighouse2", "eexit", "ehouse1", "ehouse2",
    "eroad1", "eroad2", "eroad3", "hsroad1", "hsroad2", "hsroad3", "nwhouse", "nwroad1",
    "nwroad2", "sexit", "shack", "shop", "shouse", "smithy1", "smithy2", "square", "sroad1",
    "sroad2", "sroad3", "sroad4", "temple1", "temple2", "wexit",
  }),

  "泰山": ({ "/d/taishan/", "baihe", "baozang", "beitian", "bixia", "daizong",
    "dongtian", "doumo", "ertian", "fengchan", "huima", "lianhua",
    "longmen", "nantian", "riguan", "shengxian", "shijin", "shixin",
    "tanhai", "tianjie", "weipin", "wudafu",
    "xiayi", "xitian", "yidao", "yidao1", "yidao2", "yidao3",
    "yitian", "yueguan", "yuhuang", "zhangren", "zhengqi",
  }),

  "大理城": ({ "/d/dali/", "tusifu", "guangchang",
    "sheguta", "tusimentang", "xidajie1", "xidajie2", "xidajie3", "dongdajie1",
    "tusiyishi", "paifang",
    "tusihouting", }),
]);
