mapping *family_zhan_where=(
{
(["party":       "新手盟",
"where" :       "/d/new/lgting1",]),
(["party":       "白驼山派",
"where" :       "/d/baituo/dating",]),
(["party":       "南海派",
"where" :       "/d/hainan/baiyunshan",]),
(["party":       "痴心妄想门",
"where" :       "/d/cxwxm/gc",]),
(["party":       "大理段家",
"where" :       "/d/dali/duan2",]),	
(["party":       "峨嵋派",
"where" :       "/d/emei/dadian",]),	
(["party":       "飞天御剑流",
"where" :       "/d/feitian/damen",]),
(["party":       "丐帮",
"where" :       "/d/city/pomiao",]),
(["party":       "姑苏慕容",
"where" :       "/d/mr/dating",]),
(["party":       "古墓派",
"where" :       "/d/gumu/gmht",]),
(["party":       "胡苗世家",
"where" :       "/d/zhongzhou/miaojia_zhengting",]),
(["party":       "恒山派",
"where" :       "/d/hengshan/baiyunan",]),
(["party":       "衡山派",
"where" :       "/d/hen/hengyang",]),
(["party":       "红花会",
"where" :       "/d/honghua/damen",]),
(["party":       "华山派",
"where" :       "/d/huashan/square",]),
(["party":       "浣花剑派",
"where" :       "/d/huanhua/dating",]),
(["party":       "昆仑派",
"where" :       "/d/kunlun/bwc",]),
(["party":       "灵鹫宫",
"where" :       "/d/lingjiu/damen",]),
(["party":       "凌霄城",
"where" :       "/d/lingxiao/dadian",]),
(["party":       "梅庄",
"where" :       "/d/meizhuang/zoulang1",]),
(["party":       "明教",
"where" :       "/d/mingjiao/shanmen",]),
(["party":       "青城派",
"where" :       "/d/qingcheng/shangqing",]),
(["party":       "全真教",
"where" :       "/d/quanzhen/sanqingdian",]),
(["party":       "日月神教",
"where" :       "/d/heimuya/shimen",]),
(["party":       "杀手楼",
"where" :       "/d/shashou/qiandian",]),
(["party":       "神龙教",
"where" :       "/d/shenlong/damen",]),
(["party":       "圣剑魔宫",
"where" :       "/d/hangzhou/duanqiao",]),
(["party":       "蜀山派",
"where" :       "/d/shushan/tianshi",]),
(["party":       "嵩山派",
"where" :       "/d/songshan/qianting",]),
(["party":       "泰山派",
"where" :       "/d/taishan/zhangren",]),
(["party":       "唐门",
"where" :       "/d/tangmen/liujiantang",]),
(["party":       "桃花岛",
"where" :       "/d/taohua/dating",]),
(["party":       "铁掌帮",
"where" :       "/d/tiezhang/guangchang",]),
(["party":       "通吃帮",
"where" :       "/d/tongchi/tingyuan",]),
(["party":       "五毒教",
"where" :       "/d/wudujiao/dating",]),
(["party":      "武当派",
"where" :       "/d/wudang/sanqingdian",]),
(["party":       "舞蝶仙",
"where" :       "/d/wudie/jm",]),
(["party":       "逍遥派",
"where" :       "/d/xiaoyao/qingcaop",]),
(["party":       "星宿派",
"where" :       "/d/xingxiu/xxh2",]),
(["party":       "玄天派",
"where" :       "/d/xuantian/door",]),
(["party":       "雪山寺",
"where" :       "/d/xueshan/dadian",]),
(["party":       "血刀门",
"where" :       "/d/xuedao/sroad9",]),
(["party":       "血河派",
"where" :       "/d/xuehepai/xueku",]),
(["party":       "移花宫",
"where" :       "/d/yihua/yihua_ge",]),
(["party":       "云龙门",
"where" :       "/d/city2/dating",]),
(["party":        "少林派",
"where" :         "/d/shaolin/guangchang2",]),
});