nosave mapping weapon_shuxing = ([
"damage"        : "物理攻击",
"strength"      : "臂力",
"intelligence"  : "悟性",
"constitution"  : "根骨",
"dexerity"      : "身法",
"karma"         : "福缘",
"personality"   : "容貌",
"dodge"         : "轻功",
"unarmed"       : "拳脚",
"force"         : "内功",
"parry"         : "招架",
"sword"         : "剑法",
"blade"         : "刀法",
"axe"           : "斧法",
"spear"         : "枪法",
"club"          : "棍法",
"throwing"      : "暗器",
"hammer"        : "锤法",
"whip"          : "鞭法",
"staff"         : "杖法",
/*"taoism"        : "道学心法",
"stick"         : "棒法",
"fork"          : "叉法",
"strike"        : "掌法",
"finger"        : "指法",
"poison"        : "毒功",
"hand"          : "手法",
"cuff"          : "拳法",
"claw"          : "爪法",
"magic"         : "法术",
"spells"        : "咒文",*/
]);

nosave mapping armor_shuxing = ([
"armor"         : "物理防御",
"strength"      : "臂力",
"intelligence"  : "悟性",
"constitution"  : "根骨",
"dexerity"      : "身法",
"karma"         : "福缘",
"personality"   : "容貌",
"dodge"         : "轻功",
"unarmed"       : "拳脚",
"force"         : "内功",
"parry"         : "招架",
"sword"         : "剑法",
"blade"         : "刀法",
"axe"           : "斧法",
"staff"         : "杖法",
"spear"         : "枪法",
"club"          : "棍法",
"throwing"      : "暗器",
"hammer"        : "锤法",
"whip"          : "鞭法",
/*"taoism"        : "道学心法",
"stick"         : "棒法",
"fork"          : "叉法",
"strike"        : "掌法",
"finger"        : "指法",
"poison"        : "毒功",
"hand"          : "手法",
"cuff"          : "拳法",
"claw"          : "爪法",
"magic"         : "法术",
"spells"        : "咒文",
"armor_vs_force": "真气护体",*/
]);