mapping *menpai= ({
([	//门派1-1	第1套
	"family":				"白驼山派",	
	"gender":				"男性",
//	"class":				"sworder",	//这个属于门派类型，例如尼姑、剑派等，在这里没什么用
	"force":				"hamagong",
	"dodge":				"chanchu-bufa",
	"parry":				"shexing-diaoshou",
	"unarmed":				"shexing-diaoshou",	
	"staff":				"lingshe-zhangfa",
	"weapon":				"/clone/weapon/hanbing-zhang",
]),	
([	//门派2-1	第2套
	"family":				"南海派",	
	"gender":				"男性",
	"force":				"bitao-shengong",
	"dodge":				"qiongya-bufa",
	"parry":				"feixian-jian",
	"unarmed":				"baihua-zhang",	
	"sword":				"feixian-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派3-1	第3套
	"family":				"痴心妄想门",	
	"gender":				"女性",
	"force":				"wangran-xinfa",
	"dodge":				"shuiyue",
	"parry":				"chixin-bianfa",
	"unarmed":				"cxwx-quan",	
	"whip":					"chixin-bianfa",
	"weapon":				"/clone/weapon/hanbing-bian",
]),
([	//门派4-1	第4套
	"family":				"大理段家",	
	"gender":				"男性",
	"force":				"kumu-shengong",
	"dodge":				"tiannan-step",
	"parry":				"yiyang-zhi",
	"unarmed":				"yiyang-zhi",	
	"sword":				"duanjia-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派4-2	第5套
	"family":				"大理段家",	
	"gender":				"女性",
	"force":				"kumu-shengong",
	"dodge":				"tiannan-step",
	"parry":				"wuluo-zhang",
	"unarmed":				"wuluo-zhang",
	"whip":					"feifeng-whip",
]),
([	//门派4-3	第6套
	"family":				"大理段家",	
	"gender":				"男性",
	"force":				"kumu-shengong",
	"dodge":				"tiannan-step",
	"parry":				"yiyang-zhi",
	"unarmed":				"liumai-shenjian",	
]),
([	//门派5-1	第7套
	"family":				"峨嵋派",	
	"gender":				"男性",
	"force":				"linji-zhuang",
	"dodge":				"zhutian-bu",
	"parry":				"jinding-zhang",
	"unarmed":				"jinding-zhang",	
	"sword":				"huifeng-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派6-1	第8套
	"family":				"飞天御剑流",	
	"gender":				"男性",
	"force":				"shayi-xinfa",
	"dodge":				"wuxing-dun",
	"parry":				"feitian-yujianliu",
	"unarmed":				"enmeiryu",	
	"blade":				"feitian-yujianliu",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派6-2	第9套
	"family":				"飞天御剑流",	
	"gender":				"男性",
	"force":				"shayi-xinfa",
	"dodge":				"wuxing-dun",
	"parry":				"ittouryu",
	"unarmed":				"aikido",	
	"blade":				"ittouryu",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派6-3	第10套
	"family":				"飞天御剑流",	
	"gender":				"男性",
	"force":				"shayi-xinfa",
	"dodge":				"wuxing-dun",
	"parry":				"xuanhualiu-quanfa",
	"unarmed":				"xuanhualiu-quanfa",	
	"blade":				"ittouryu",
]),
([	//门派7-1	第11套
	"family":				"丐帮",	
	"gender":				"男性",
	"force":				"huntian-qigong",
	"dodge":				"xiaoyaoyou",
	"parry":				"xianglong-zhang",
	"unarmed":				"xianglong-zhang",
]),
([	//门派7-2	第12套
	"family":				"丐帮",	
	"gender":				"男性",
	"force":				"huntian-qigong",
	"dodge":				"xiaoyaoyou",
	"parry":				"dagou-bang",
	"unarmed":				"xianglong-zhang",	
	"club":					"dagou-bang",
	"weapon":				"/clone/weapon/hanbing-gun",
]),
([	//门派8-1	第13套
	"family":				"姑苏慕容",	
	"gender":				"男性",
	"force":				"shenyuan-gong",
	"dodge":				"yanling-shenfa",
	"parry":				"douzhuan-xingyi",
	"unarmed":				"canhe-zhi",	
]),
([	//门派8-2	第14套
	"family":				"姑苏慕容",	
	"gender":				"男性",
	"force":				"shenyuan-gong",
	"dodge":				"yanling-shenfa",
	"parry":				"douzhuan-xingyi",
	"unarmed":				"xingyi-zhang",	
	"blade":				"murong-daofa",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派8-3	第15套
	"family":				"姑苏慕容",	
	"gender":				"男性",
	"force":				"shenyuan-gong",
	"dodge":				"yanling-shenfa",
	"parry":				"douzhuan-xingyi",
	"unarmed":				"canhe-zhi",	
	"sword":				"murong-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派9-1	第16套
	"family":				"古墓派",	
	"gender":				"男性",
	"force":				"yunv-xinfa",
	"dodge":				"yunv-shenfa",
	"parry":				"anranxiaohun-zhang",
	"unarmed":				"anranxiaohun-zhang",	
	"sword":				"xuantie-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派9-2	第17套
	"family":				"古墓派",	
	"gender":				"女性",
	"force":				"yunv-xinjing",
	"dodge":				"yunv-shenfa",
	"parry":				"yunv-jianfa",
	"unarmed":				"meinv-quanfa",	
	"sword":				"yunv-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派9-3	第18套
	"family":				"古墓派",	
	"gender":				"女性",
	"force":				"yunv-xinjing",
	"dodge":				"yunv-shenfa",
	"parry":				"yinsuo-jinling",
	"unarmed":				"wudu-shenzhang",	
	"whip":					"qiufeng-chenfa",
	"weapon":				"/clone/weapon/hanbing-bian",
]),
([	//门派10-1	第19套
	"family":				"胡苗世家",	
	"gender":				"男性",
	"force":				"lengyue-shengong",
	"dodge":				"sixiang-bufa",
	"parry":				"miaojia-jian",
	"unarmed":				"tianchang-zhang",
	"blade":				"hujia-dao",	
	"sword":				"daojian-guizhen",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派10-2	第20套
	"family":				"胡苗世家",	
	"gender":				"男性",
	"force":				"lengyue-shengong",
	"dodge":				"sixiang-bufa",
	"parry":				"daojian-guizhen",
	"unarmed":				"tianchang-zhang",	
	"blade":				"hujia-dao",
	"sword":				"miaojia-jian",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派11-1	第21套
	"family":				"恒山派",	
	"gender":				"女性",
	"force":				"baiyun-xinfa",
	"dodge":				"shenxing-baibian",
	"parry":				"hengshan-jian",
	"unarmed":				"xuantian-zhi",	
	"sword":				"hengshan-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派12-1	第22套
	"family":				"衡山派",	
	"gender":				"男性",
	"force":				"zhenyue-jue",
	"dodge":				"shenxing-baibian",
	"parry":				"luoyan-jian",
	"unarmed":				"qinnashou",	
	"sword":				"luoyan-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派13-1	第23套
	"family":				"红花会",	
	"gender":				"男性",
	"force":				"honghua-shengong",
	"dodge":				"youlong-shenfa",
	"parry":				"luohua-jian",
	"unarmed":				"baihua-cuoquan",	
	"sword":				"luohua-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派14-1	第24套
	"family":				"华山派",	
	"gender":				"男性",
	"force":				"zixia-shengong",
	"dodge":				"huashan-shenfa",
	"parry":				"kuangfeng-jian",
	"unarmed":				"huashan-zhangfa",	
	"sword":				"huashan-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派14-2	第25套
	"family":				"华山派",	
	"gender":				"男性",
	"force":				"zixia-shengong",
	"dodge":				"huashan-shenfa",
	"parry":				"poyu-quan",
	"unarmed":				"hunyuan-zhang",	
	"blade":				"fanliangyi-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派15-1	第26套
	"family":				"浣花剑派",	
	"gender":				"男性",
	"force":				"guiyuan-dafa",
	"dodge":				"feihua-wuping",
	"parry":				"tiexian-quan",
	"unarmed":				"tiexian-quan",	
	"sword":				"huanhua-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派16-1	第27套
	"family":				"昆仑派",	
	"gender":				"男性",
	"force":				"xuantian-wuji",
	"dodge":				"kunlun-shenfa",
	"parry":				"liangyi-jian",
	"unarmed":				"kunlun-zhang",	
	"sword":				"liangyi-jian",
	"knowledge":			"art",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派16-2	第28套
	"family":				"昆仑派",	
	"gender":				"男性",
	"force":				"xuantian-wuji",
	"dodge":				"kunlun-shenfa",
	"parry":				"kunlun-zhang",
	"unarmed":				"kunlun-zhang",	
]),
([	//门派17-1	第29套
	"family":				"灵鹫宫",	
	"gender":				"女性",
	"force":				"bahuang-gong",
	"dodge":				"yueying-wubu",
	"parry":				"zhemei-shou",
	"unarmed":				"liuyang-zhang",	
	"sword":				"tianyu-qijian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派18-1	第30套
	"family":				"凌霄城",	
	"gender":				"男性",
	"force":				"bingxue-xinfa",
	"dodge":				"snow-step",
	"parry":				"lingxiao-jian",
	"unarmed":				"snow-zhang",	
	"sword":				"xueshan-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派18-2	第31套
	"family":				"凌霄城",	
	"gender":				"男性",
	"force":				"bingxue-xinfa",
	"dodge":				"snow-step",
	"parry":				"xueshan-jianfa",
	"unarmed":				"snow-zhang",	
	"blade":				"jinwu-blade",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派19-1	第32套
	"family":				"梅庄",	
	"gender":				"男性",
	"force":				"wuzheng-xinfa",
	"dodge":				"yaoming-dodge",
	"parry":				"wuying-shenquan",
	"unarmed":				"wuying-shenquan",	
	"throwing":				"mantian-xing",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派19-2	第33套
	"family":				"梅庄",	
	"gender":				"男性",
	"force":				"wuzheng-xinfa",
	"dodge":				"yaoming-dodge",
	"parry":				"wuyun-jianfa",
	"unarmed":				"qixian-wuxingjian",	
	"sword":				"qixian-wuxingjian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派20-1	第34套
	"family":				"明教",	
	"gender":				"男性",
	"force":				"shenghuo-shengong",
	"dodge":				"qingyunwu",
	"parry":				"qiankundanuoyi",
	"unarmed":				"sougu",
	"sword":				"shenghuo-jian",	
	"sword":				"liehuo-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派20-2	第35套
	"family":				"明教",	
	"gender":				"男性",
	"force":				"shenghuo-shengong",
	"dodge":				"qingyunwu",
	"parry":				"qiankundanuoyi",
	"unarmed":				"qishang-quan",	
	"sword":				"shenghuo-ling",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派20-3	第36套
	"family":				"明教",	
	"gender":				"男性",
	"force":				"shenghuo-shengong",
	"dodge":				"qingfu-shenfa",
	"parry":				"qiankundanuoyi",
	"unarmed":				"hanbing-mianzhang",	
	"throwing":				"feihua-shou",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派21-1	第37套
	"family":				"青城派",	
	"gender":				"无性",
	"force":				"xuanmen-gangqi",
	"dodge":				"pixie-jian",
	"parry":				"pixie-sword",
	"unarmed":				"changquan",	
	"sword":				"pixie-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派22-1	第38套
	"family":				"全真教",	
	"gender":				"男性",
	"force":				"xiantian-qigong",
	"dodge":				"qixing-huanwei",
	"parry":				"quanzhen-jianfa",
	"unarmed":				"haotian-zhang",	
	"sword":				"quanzhen-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派22-2	第39套
	"family":				"全真教",	
	"gender":				"男性",
	"force":				"tiangang-zhengqi",
	"dodge":				"jinyan-gong",
	"parry":				"quanzhen-jianfa",
	"unarmed":				"haotian-zhang",	
	"whip":					"duanyun-bian",
	"weapon":				"/clone/weapon/hanbing-bian",
]),
([	//门派23-1	第40套
	"family":				"日月神教",	
	"gender":				"无性",
	"force":				"kuihua-xinfa",
	"dodge":				"kuihua-feiying",
	"parry":				"kuihua-dafa",
	"unarmed":				"kuihua-dafa",	
	"sword":				"kuihua-dafa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派23-2	第41套
	"family":				"日月神教",	
	"gender":				"男性",
	"force":				"tianmo-shengong",
	"dodge":				"wuxue-shenfa",
	"parry":				"tianmo-jian",
	"unarmed":				"tianmo-quan",	
	"sword":				"tianmo-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派23-3	第42套
	"family":				"日月神教",	
	"gender":				"男性",
	"force":				"tianmo-shengong",
	"dodge":				"wuxue-shenfa",
	"parry":				"tianmo-dao",
	"unarmed":				"tianmo-quan",	
	"blade":				"tianmo-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派24-1	第43套
	"family":				"杀手楼",	
	"gender":				"男性",
	"force":				"wuji-shengong",
	"dodge":				"bugui-bufa",
	"parry":				"wushuang-jian",
	"unarmed":				"fanyun-zhang",	
	"sword":				"qingyi-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派24-2	第44套
	"family":				"杀手楼",	
	"gender":				"男性",
	"force":				"wuji-shengong",
	"dodge":				"bugui-bufa",
	"parry":				"liujue-dao",
	"unarmed":				"fanyun-zhang",	
	"blade":				"qishen-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派25-1	第45套
	"family":				"神龙教",	
	"gender":				"男性",
	"force":				"shenlong-xinfa",
	"dodge":				"yixingbu",
	"parry":				"shenlong-bashi",
	"unarmed":				"shenlong-bashi",	
	"staff":				"shedao-qigong",
]),
([	//门派26-1	第46套
	"family":				"圣剑魔宫",	
	"gender":				"男性",
	"force":				"zhenfeng-xinfa",
	"dodge":				"piaoyibu",
	"parry":				"three-sword",
	"unarmed":				"zhentian-quan",	
	"sword":				"three-sword",
	"knowledge":			"qimen-wuxing",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派26-2	第47套
	"family":				"圣剑魔宫",	
	"gender":				"男性",
	"force":				"zhenfeng-xinfa",
	"dodge":				"piaoyibu",
	"parry":				"lonely-sword",
	"unarmed":				"zhentian-quan",	
	"sword":				"lonely-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派27-1	第48套
	"family":				"蜀山派",	
	"gender":				"男性",
	"force":				"shushan-force",
	"dodge":				"zuixian-steps",
	"parry":				"xiaoyaoyou",
	"unarmed":				"fumozhang",	
	"sword":				"yujianshu",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派27-2	第49套
	"family":				"蜀山派",	
	"gender":				"男性",
	"force":				"shushan-force",
	"dodge":				"zuixian-steps",
	"parry":				"canxin-jian",
	"unarmed":				"fumozhang",	
	"sword":				"canxin-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派28-1	第50套
	"family":				"嵩山派",	
	"gender":				"男性",
	"force":				"hanbing-zhenqi",
	"dodge":				"lingxu-bu",
	"parry":				"songyang-zhang",
	"unarmed":				"songyang-zhang",	
	"sword":				"songshan-jian",
]),
([	//门派29-1	第51套
	"family":				"泰山派",	
	"gender":				"男性",
	"force":				"panshi-shengong",
	"dodge":				"shenxing-baibian",
	"parry":				"taishan-jianfa",
	"unarmed":				"taizu-quan",	
	"sword":				"taishan-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派30-1	第52套
	"family":				"唐门",	
	"gender":				"女性",
	"force":				"biyun-xinfa",
	"dodge":				"qiulinshiye",
	"parry":				"liuxing-biao",
	"unarmed":				"biye-wu",	
	"throwing":				"zhuihun-biao",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派30-2	第53套
	"family":				"唐门",	
	"gender":				"男性",
	"force":				"biyun-xinfa",
	"dodge":				"qiulinshiye",
	"parry":				"pili-biao",
	"unarmed":				"biye-wu",	
	"throwing":				"zimu-zhen",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派30-3	第54套
	"family":				"唐门",	
	"gender":				"男性",
	"force":				"biyun-xinfa",
	"dodge":				"qiulinshiye",
	"parry":				"xiaoyaoyou",
	"unarmed":				"biye-wu",	
	"sword":				"wuzhan-mei",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派31-1	第55套
	"family":				"桃花岛",	
	"gender":				"男性",
	"force":				"bibo-shengong",
	"dodge":				"anying-fuxiang",
	"parry":				"yuxiao-jianfa",
	"unarmed":				"lanhua-shou",	
	"sword":				"yuxiao-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派31-1	第56套
	"family":				"桃花岛",	
	"gender":				"女性",
	"force":				"bibo-shengong",
	"dodge":				"anying-fuxiang",
	"parry":				"luoying-zhang",
	"unarmed":				"lanhua-shou",	
	"sword":				"luoying-shenjian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派31-3	第57套
	"family":				"桃花岛",	
	"gender":				"男性",
	"force":				"bibo-shengong",
	"dodge":				"anying-fuxiang",
	"parry":				"tanzhi-shentong",
	"unarmed":				"tanzhi-shentong",	
	"sword":				"yuxiao-jianfa",
	"knowledge":			"qimen-wuxing",
	"knowledge":			"count",
]),
([	//门派32-1	第58套
	"family":				"铁掌帮",	
	"gender":				"男性",
	"force":				"guiyuan-tunafa",
	"dodge":				"shuishangpiao",
	"parry":				"tiezhang-zhangfa",
	"unarmed":				"tiezhang-zhangfa",
]),
([	//门派32-2	第59套
	"family":				"铁掌帮",	
	"gender":				"男性",
	"force":				"guiyuan-tunafa",
	"dodge":				"shuishangpiao",
	"parry":				"duanyun-fu",
	"unarmed":				"tiezhang-zhangfa",
	"axe":					"duanyun-fu",
	"weapon":				"/clone/weapon/hanbing-fu",
]),
([	//门派33-1	第60套
	"family":				"通吃帮",	
	"gender":				"男性",
	"force":				"fanyun-force",
	"dodge":				"piaomiao-shenfa",
	"parry":				"langzi-sword",
	"unarmed":				"dabei-zhang",	
	"sword":				"guxing-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派34-1	第61套
	"family":				"五毒教",	
	"gender":				"男性",
	"force":				"wudu-shengong",
	"dodge":				"wudu-yanluobu",
	"parry":				"wudu-goufa",
	"unarmed":				"qianzhu-wandushou",	
	"sword":				"wudu-goufa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派35-1	第62套
	"family":				"武当派",	
	"gender":				"男性",
	"force":				"taiji-shengong",
	"dodge":				"tiyunzong",
	"parry":				"taiji-quan",
	"unarmed":				"taiji-quan",	
	"sword":				"taiji-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派35-2	第63套
	"family":				"武当派",	
	"gender":				"男性",
	"force":				"taiji-shengong",
	"dodge":				"tiyunzong",
	"parry":				"taiji-quan",
	"unarmed":				"taiji-quan",	
	"blade":				"taiji-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派35-3	第64套
	"family":				"武当派",	
	"gender":				"男性",
	"force":				"yinyun-ziqi",
	"dodge":				"tiyunzong",
	"parry":				"juehu-shou",
	"unarmed":				"juehu-shou",
]),
([	//门派36-1	第65套
	"family":				"舞蝶仙",	
	"gender":				"女性",
	"force":				"wudie-xinjing",
	"dodge":				"wudie-bu",
	"parry":				"meihua-sannong",
	"unarmed":				"meihua-sannong",	
	"sword":				"dieyi-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派37-1	第66套
	"family":				"逍遥派",	
	"gender":				"男性",
	"force":				"beiming-shengong",
	"dodge":				"lingboweibu",
	"parry":				"zhemei-shou",
	"unarmed":				"zhemei-shou",	
	"blade":				"ruyi-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派38-1	第67套
	"family":				"星宿派",	
	"gender":				"男性",
	"force":				"huagong-dafa",
	"dodge":				"zhaixinggong",
	"parry":				"chousui-zhang",
	"unarmed":				"chousui-zhang",	
	"staff":				"tianshan-zhang",
	"weapon":				"/clone/weapon/hanbing-zhang",
]),
([	//门派39-1	第68套
	"family":				"玄天派",	
	"gender":				"男性",
	"force":				"lingyuan-xinfa",
	"dodge":				"lingyunbu",
	"parry":				"tianxin-blade",
	"unarmed":				"cuixin-zhang",	
	"blade":				"tianxin-blade",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派40-1	第69套
	"family":				"雪山寺",	
	"gender":				"男性",
	"force":				"longxiang",
	"dodge":				"shenkong-xing",
	"parry":				"riyue-lun",
	"unarmed":				"huoyan-dao",	
	"hammer":				"riyue-lun",
	"weapon":				"/clone/weapon/hanbing-chui",
]),
([	//门派40-2	第70套
	"family":				"雪山寺",	
	"gender":				"男性",
	"force":				"longxiang",
	"dodge":				"shenkong-xing",
	"parry":				"xiangmo-chu",
	"unarmed":				"dashou-yin",	
	"staff":				"xiangmo-chu",
	"weapon":				"/clone/weapon/hanbing-zhang",
]),
([	//门派40-3	第71套
	"family":				"雪山寺",	
	"gender":				"男性",
	"force":				"longxiang",
	"dodge":				"shenkong-xing",
	"parry":				"dashou-yin",
	"unarmed":				"yujiamu-quan",
]),
([	//门派40-4	第72套
	"family":				"雪山寺",	
	"gender":				"男性",
	"force":				"xiaowuxiang",
	"dodge":				"shenkong-xing",
	"parry":				"huoyan-dao",
	"unarmed":				"huoyan-dao",
	"sword":				"mingwang-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派41-1	第73套
	"family":				"血刀门",	
	"gender":				"男性",
	"force":				"xuedao-xinfa",
	"dodge":				"xueying-shenfa",
	"parry":				"xue-dao",
	"unarmed":				"ningxue-shenzhua",	
	"blade":				"xue-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派42-1	第74套
	"family":				"血河派",	
	"gender":				"男性",
	"force":				"huaxue-dafa",
	"dodge":				"youran-bu",
	"parry":				"tianhe-jian",
	"unarmed":				"feixue-quan",	
	"sword":				"tianhe-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派42-2	第75套
	"family":				"血河派",	
	"gender":				"男性",
	"force":				"yiqiguan-riyue",
	"dodge":				"youran-bu",
	"parry":				"huaxue-shenzhen",
	"unarmed":				"feixue-quan",	
	"throwing":				"youren-jian",
	"blade":				"jieniu-dao",
	"whip":					"yudi-bian",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派42-3	第76套
	"family":				"血河派",	
	"gender":				"男性",
	"force":				"longmen-shengong",
	"dodge":				"youran-bu",
	"parry":				"jieniu-dao",
	"unarmed":				"feixue-quan",	
	"blade":				"jieniu-dao",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派43-1	第77套
	"family":				"移花宫",	
	"gender":				"女性",
	"force":				"mingyu-shengong",
	"dodge":				"yihua-jiemu",
	"parry":				"yihua-jiemu",
	"unarmed":				"jueqing-zhang",	
	"sword":				"yifeng-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派44-1	第78套
	"family":				"云龙门",	
	"gender":				"男性",
	"force":				"yunlong-shengong",
	"dodge":				"yunlong-shenfa",
	"parry":				"yunlong-zhua",
	"unarmed":				"yunlong-shou",	
	"sword":				"yunlong-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派45-1	第79套
	"family":				"少林派",	
	"gender":				"男性",
	"force":				"hunyuan-yiqi",
	"dodge":				"shaolin-shenfa",
	"parry":				"fengyun-shou",
	"unarmed":				"yizhi-chan",	
	"club":					"weituo-gun",
	"weapon":				"/clone/weapon/hanbing-gun",
]),
([	//门派45-2	第80套
	"family":				"少林派",	
	"gender":				"男性",
	"force":				"hunyuan-yiqi",
	"dodge":				"shaolin-shenfa",
	"parry":				"yingzhua-gong",
	"unarmed":				"longzhua-gong",	
	"staff":				"pudu-zhang",
	"weapon":				"/clone/weapon/hanbing-zhang",
]),
([	//门派45-3	第81套
	"family":				"少林派",	
	"gender":				"男性",
	"force":				"yijinjing",
	"dodge":				"shaolin-shenfa",
	"parry":				"sanhua-zhang",
	"unarmed":				"qianye-shou",	
	"blade":				"cibei-dao",
]),
([	//门派45-4	第82套
	"family":				"少林派",	
	"gender":				"男性",
	"force":				"yijinjing",
	"dodge":				"shaolin-shenfa",
	"parry":				"riyue-bian",
	"unarmed":				"nianhua-zhi",
	"sword":				"fumo-jian",
	"whip":					"riyue-bian",
	"weapon":				"/clone/weapon/hanbing-bian",
]),
([	//门派45-5	第83套
	"family":				"少林派",	
	"gender":				"男性",
	"force":				"yijinjing",
	"dodge":				"shaolin-shenfa",
	"parry":				"banruo-zhang",
	"unarmed":				"jingang-quan",	
	"sword":				"wuying-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第84套
	"family":				"八部龙女剑",	
	"gender":				"女性",
	"force":				"hanbing-zhenqi",
	"dodge":				"lingxu-bu",
	"parry":				"babulongnv-jian",
	"unarmed":				"zuoyou-boji",
	"sword":				"huashan-jianfa",
	"sword":				"songshan-jian",
	"sword":				"taishan-jianfa",
	"sword":				"luoyan-jian",
	"sword":				"hengshan-jian",
	"sword":				"babulongnv-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第85套
	"family":				"独孤九剑",	
	"gender":				"男性",
	"force":				"taixuan-gong",
	"dodge":				"taixuan-gong",
	"parry":				"lonely-sword",
	"unarmed":				"taixuan-gong",	
	"sword":				"dugu-jiujian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第86套
	"family":				"独孤九剑",	
	"gender":				"男性",
	"force":				"xixing-dafa",
	"dodge":				"shenxing-baibian",
	"parry":				"dugu-jiujian",
	"unarmed":				"kongming-quan",	
	"sword":				"lonely-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第87套
	"family":				"九阴真经",	
	"gender":				"女性",
	"force":				"jiuyin-zhenjing",
	"dodge":				"shenxing-baibian",
	"parry":				"jiuyin-baiguzhao",
	"unarmed":				"jiuyin-baiguzhao",	
]),
([	//门派	第88套
	"family":				"九阳神功",	
	"gender":				"男性",
	"force":				"jiuyang-shengong",
	"dodge":				"qiankundanuoyi",
	"parry":				"shenghuo-ling",
	"unarmed":				"qishang-quan",	
	"sword":				"shenghuo-ling",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第89套
	"family":				"太玄无名",	
	"gender":				"男性",
	"force":				"taixuan-gong",
	"dodge":				"taixuan-gong",
	"parry":				"taixuan-gong",
	"unarmed":				"taixuan-gong",	
	"sword":				"wuming-jianfa",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第90套
	"family":				"金蛇系",	
	"gender":				"男性",
	"force":				"yijing-force",
	"dodge":				"shenxing-baibian",
	"parry":				"jinshe-zhang",
	"unarmed":				"jinshe-zhang",	
	"sword":				"jinshe-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第91套
	"family":				"金蛇系",	
	"gender":				"男性",
	"force":				"xixing-dafa",
	"dodge":				"shenxing-baibian",
	"parry":				"jinshe-zhang",
	"unarmed":				"jinshe-zhang",	
	"throwing":				"jinshe-zhui",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派	第92套
	"family":				"小李飞刀",	
	"gender":				"男性",
	"force":				"tianmo-shengong",
	"dodge":				"wuxue-shenfa",
	"parry":				"xiaoli-feidao",
	"unarmed":				"tianmo-quan",	
	"throwing":				"xiaoli-feidao",
	"weapon":				"/clone/weapon/hanbing-shi",
]),
([	//门派	第93套
	"family":				"音乐",	
	"gender":				"女性",
	"force":				"wudie-xinjing",
	"dodge":				"wudie-bu",
	"parry":				"music",
	"unarmed":				"music",	
	"hand":					"music",
]),
([	//门派	第94套
	"family":				"棋道",	
	"gender":				"男性",
	"force":				"xuantian-wuji",
	"dodge":				"yaoming-dodge",
	"parry":				"qidao",
	"unarmed":				"qidao",	
	"finger":				"qidao",
]),
([	//门派	第95套
	"family":				"雷霆斧",	
	"gender":				"男性",
	"force":				"jiuyang-shengong",
	"dodge":				"qiankundanuoyi",
	"parry":				"qinnashou",
	"unarmed":				"qinnashou",	
	"axe":					"leiting-axe",
	"weapon":				"/clone/weapon/hanbing-fu",
]),
([	//门派	第96套
	"family":				"岳家枪",	
	"gender":				"男性",
	"force":				"jiuyang-shengong",
	"dodge":				"shenxing-baibian",
	"parry":				"yuejia-qiang",
	"unarmed":				"houquan",	
	"spear":				"yuejia-qiang",
	"weapon":				"/clone/weapon/hanbing-qiang",
]),
([	//门派	第97套
	"family":				"风刀",	
	"gender":				"男性",
	"force":				"taixuan-gong",
	"dodge":				"shenxing-baibian",
	"parry":				"wind-blade",
	"unarmed":				"zuoyou-boji",	
	"blade":				"wind-blade",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派	第98套
	"family":				"温柔剑",	
	"gender":				"女性",
	"force":				"jiuyin-zhenjing",
	"dodge":				"shenxing-baibian",
	"parry":				"wenrou-jian",
	"unarmed":				"qinnashou",	
	"sword":				"wenrou-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第99套
	"family":				"太监",	
	"gender":				"无性",
	"force":				"kuihua-xinfa",
	"dodge":				"pixie-jian",
	"parry":				"pixie-jian",
	"unarmed":				"ningxue-shenzhua",	
	"sword":				"pixie-jian",
	"weapon":				"/clone/weapon/hanbing-jian",
]),
([	//门派	第100套
	"family":				"魔刀",	
	"gender":				"男性",
	"force":				"yunshang-xinjing",
	"dodge":				"shuiyue",
	"parry":				"demon-blade",
	"unarmed":				"qidao",	
	"blade":				"demon-blade",
	"weapon":				"/clone/weapon/hanbing-dao",
]),
([	//门派	第101套
	"family":				"情剑",	
	"gender":				"女性",
	"force":				"yunshang-xinjing",
	"dodge":				"shuiyue",
	"parry":				"ai-sword",
	"unarmed":				"music",	
	"sword":				"ai-sword",
	"weapon":				"/clone/weapon/hanbing-jian",
])
});