mapping *dest = ({
 ([ "name":"shijianshi",
           "context": ({
"/u/beyond/suzhou/qianrenshi",
"/u/beyond/suzhou/wjszhuang",
"/u/beyond/suzhou/toushanmen",
"/u/beyond/suzhou/huqiushan",
"/u/beyond/suzhou/qsgdao6",
"/d/city/sroad1",
"/d/city/jiangnan",
"/d/city/sroad1",
"/u/beyond/suzhou/qsgdao6",
"/u/beyond/suzhou/northgate",
"/u/beyond/suzhou/beidajie2",
"/u/beyond/suzhou/beidiajie1",
})]),

 ([ "name":"caixiangjing",
           "context": ({
"/u/beyond/suzhou/shuiwa1",
"/u/beyond/suzhou/shiyuan",
"/u/beyond/suzhou/yingxiaoting",
"/u/beyond/suzhou/lingyanshan",
"/u/beyond/suzhou/tianpingshan",
"/u/beyond/suzhou/shihu",
"/u/beyond/suzhou/tianpingshan",
"/u/beyond/suzhou/baiyunquan",   
"/u/beyond/suzhou/tianpingshan",
"/u/beyond/suzhou/qsgdao",
"/u/beyond/suzhou/qsgdao1",
"/u/beyond/suzhou/qsgdao2",
})]),
([ "name":"chitang",
           "context": ({
"/u/beyond/suzhou/gumujiaohe",
"/u/beyond/suzhou/hehuating",
"/u/beyond/suzhou/liuyuan",
"/u/beyond/suzhou/nandajie2",
"/u/beyond/suzhou/tingyuxuan",
"/u/beyond/suzhou/nandajie2",
"/u/beyond/suzhou/nandajie1",
"/u/beyond/suzhou/shizilin",
"/u/beyond/suzhou/zhibaixuan",
"/u/beyond/suzhou/shizilin",
"/u/beyond/suzhou/baodaiqiao",
})]),
([ "name":"baodaiqiao",
           "context": ({
"/u/beyond/suzhou/canglangting",
"/u/beyond/suzhou/xidajie1",
"/u/beyond/suzhou/xidajie2",
"/u/beyond/suzhou/xuanmiaoguan",
"/u/beyond/suzhou/xidajie1",
"/u/beyond/suzhou/westgate",
"/u/beyond/suzhou/qsgdao3",
"/u/beyond/suzhou/qsgdao4",
"/u/beyond/suzhou/qsgdao5",
"/u/beyond/suzhou/hanshansi",
"/u/beyond/zhengdian",
})]),

});

