// File: /u/d/dony/home/idle.c
// Generated by Roommaker Wed Jan 10 21:46:32 1996

#include <mudlib.h>

void create(object ob)
{
	if ( !ob ) return ;
	ob->set_short("发呆幻想室");
	ob->set_long( @LONG_DESCRIPTION
这是宁丹的最爱的幻想空间

    你看到房间内都是软骨头，红的，黄的，绿的，甚麽颜色都有，
    只要你慢慢寻找，可能宁丹最在这□发呆，寻找他的灵感！
    房间的正中间，摆著宁丹最重要的东西，咖啡，音乐，和电话，
    宁丹每天离不开这些东西，一旦缺了一样，宁丹会变成另一个人似的
    会觉得生命总是缺少了甚麽，桌上放了一个字条(sign)!
    往北则是宁丹的工作室

LONG_DESCRIPTION
	);

	ob->set( "light", 1 );
	ob->set( "exits", ([ 
		"north" : "/u/d/dony/home/workroom" ]) );
	ob->reset();
}
