大话西游==@==/doc/help/dhxy.txt
李白诗选==@==/doc/poem/libai.txt
辛弃疾词选==@==/doc/poem/xin.txt
白居易诗选==@==/doc/poem/bai.txt
苏轼词选==@==/doc/poem/su.txt
李商隐诗选==@==/doc/poem/li.txt
柳永词选==@==/doc/poem/liu.txt
李煜词选==@==/doc/poem/liyu.txt
其他名句==@==/doc/poem/qitar.txt
名词妙句==@==/doc/poem/mylove.txt
武当三兄弟(上)==@==/doc/help/wudang.txt
武当三兄弟(下)==@==/doc/help/wudang2.txt
侠骨柔情==@==subdir0
论尽江湖==@==subdir1
小说传记==@==subdir2
巫师文档==@==subdir3
笑话一则==@==/doc/help/xiaohua.txt
考场上的故事==@==/doc/help/kaoshi.txt
旧歌新词==@==/doc/help/song.txt
泥巴上手==@==subdir4
