#define LOTHPATH "/d/barriermnts/lothwaite/inherit/pathway.lpc"
#define PATHEXIT "/d/barriermnts/lothwaite/rooms/"+
#define PATHEND "/d/barriermnts/lothwaite/inherit/pathwayend.lpc"
#define MON "/d/barriermnts/lothwaite/mon/"+
#define OBJ "/d/barriermnts/lothwaite/obj/"+
#define BARROWS "/d/barriermnts/lothwaite/inherit/barrows.lpc"
#define BTOMB "/d/barriermnts/lothwaite/inherit/barrow_tomb.lpc"
#define TOWNPATH "/d/barriermnts/lothwaite/inherit/vilpathway.lpc"
#define STORAGE "/d/barriermnts/lothwaite/inherit/"+
#define LOTHSHORE "/d/barriermnts/lothwaite/inherit/shore.lpc"
