mapping *quest = ({
  (["city":                "长安城内",
    "start" :              "/d/changan/wroad2",
    "place" :              "永泰路", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/sroad1",
    "place" :              "华瑞街", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/sroad4",
    "place" :              "南安大道", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/shroad2",
    "place" :              "南环路", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/jinghu",
    "place" :              "小镜湖", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/eroad2",
    "place" :              "连德街", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/eroad9",
    "place" :              "东安大道", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/ehroad3",
    "place" :              "东环路", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/nhroad2",
    "place" :              "北环路", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/jingsq2",
    "place" :              "金水桥", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/whroad2",
    "place" :              "西环路", ]), 
  (["city":                "长安城内",
    "start" :              "/d/changan/wroad4",
    "place" :              "西安大道", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/luzhuxiang1",
    "place" :              "绿竹巷", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/jinyangjie5",
    "place" :              "晋阳街", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/youfujie2",
    "place" :              "右府街", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/huayanlu2",
    "place" :              "华严路", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/tanhuanglu3",
    "place" :              "坦皇路", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/huaandao2",
    "place" :              "华安道", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/hongchanglu5",
    "place" :              "洪昌路", ]), 
  (["city":                "大同府",
    "start" :              "/d/datong/huayanlu4",
    "place" :              "华严路", ]),
  (["city":                "侯集镇",
    "start" :              "/d/houjizhen/shilu4",
    "place" :              "碎石路", ]),
  (["city":                "侯集镇",
    "start" :              "/d/houjizhen/hean2",
    "place" :              "河岸", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai29",
    "place" :              "长青路", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai21",
    "place" :              "背阴小巷", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai9",
    "place" :              "虹日路", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai65",
    "place" :              "开封西街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai37",
    "place" :              "山南街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai55",
    "place" :              "立山街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai165",
    "place" :              "向阳街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai103",
    "place" :              "开封南街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai73",
    "place" :              "中心街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai147",
    "place" :              "开封东街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai158",
    "place" :              "前松街", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai133",
    "place" :              "夷林东路", ]),
  (["city":                "开封府",
    "start" :              "/d/kaifeng/kai119",
    "place" :              "夷林北路", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/wmlu2",
    "place" :              "万明路", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/wmlu5",
    "place" :              "万明路", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/wwdao3",
    "place" :              "武王道", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/jguanlu3",
    "place" :              "锦官路", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/jguanlu6",
    "place" :              "锦官路", ]),
  (["city":                "成都府",
    "start" :              "/d/chengdu/fdjie1",
    "place" :              "府道街", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/guotaiw2",
    "place" :              "国泰路", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/guotaie2",
    "place" :              "国泰路", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/minan04",
    "place" :              "民安南街", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/changanw2",
    "place" :              "长安西街", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/changane2",
    "place" :              "长安东街", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/yongningn2",
    "place" :              "永宁街", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/stoneroad3",
    "place" :              "石板路", ]),
  (["city":                "杭州城",
    "start" :              "/d/hangzhou/rockroad2",
    "place" :              "碎石路", ]),
});  

