mapping *quest = ({
  (["place":                "长安西环路",
    "start" :              "/d/changan/whroad2",]), 
  (["place":                "长安永泰路",
    "start" :              "/d/changan/wroad5",]), 
  (["place":                "长安华瑞街",
    "start" :              "/d/changan/sroad2",]), 
  (["place":                "长安连德街",
    "start" :              "/d/changan/eroad2",]), 
  (["place":                "长安南门外青石官道",
    "start" :              "/d/path2/ch_k4",]), 
  (["place":                "长安南门外黄土路",
    "start" :              "/d/path2/ch_k10",]), 
  (["place":                "长安南门外高原大道",
    "start" :              "/d/path2/ch_k18",]), 
  (["place":                "长安北门外林中小路",
    "start" :              "/d/houjizhen/lzxiaolu",]), 
  (["place":                "长安北门外山间小路",
    "start" :              "/d/houjizhen/shanlu2",]), 
  (["place":                "候集镇土路",
    "start" :              "/d/houjizhen/tulu1",]),
  (["place":                "长安西门外青石官道",
    "start" :              "/d/path2/ch_t4",]), 
  (["place":                "大同晋阳街",
    "start" :              "/d/datong/jinyangjie1",]), 
  (["place":                "大同绿竹巷",
    "start" :              "/d/datong/luzhuxiang2",]), 
  (["place":                "大同南门外高粱地",
    "start" :              "/d/path2/da_hou5",]), 
  (["place":                "开封胡同拐角",
    "start" :              "/d/kaifeng/kai53",]), 
  (["place":                "开封南门外大路",
    "start" :              "/d/path3/k_s3",]), 
  (["place":                "开封路口",
    "start" :              "/d/kaifeng/kai162",]),
  (["place":                "开封北街",
    "start" :              "/d/kaifeng/kai86",]),
  (["place":                "开封北门外黄土大道",
    "start" :              "/d/path2/ch_k41",]),
  (["place":                "华山上山路",
    "start" :              "/d/huayin/tl8",]),
  (["place":                "华山林间小路",
    "start" :              "/d/huashan/xiaolu3",]), 
  (["place":                "华山山路",
    "start" :              "/d/huashan/xiaolu9",]), 
  (["place":                "华山猢狲愁",
    "start" :              "/d/huashan/husunchou",]), 
  (["place":                "华山山路",
    "start" :              "/d/huashan/shanlu2",]), 
  (["place":                "少林土路",
    "start" :              "/d/shaolin/tulu1",]), 
  (["place":                "少林蜿蜒小路",
    "start" :              "/d/shaolin/xiaolu1",]), 
  (["place":                "杭州石板路",
    "start" :              "/d/hangzhou/stoneroad2",]), 
  (["place":                "杭州小径",
    "start" :              "/d/hangzhou/pathy2",]), 
  (["place":                "杭州碎石路",
    "start" :              "/d/hangzhou/rockroad3",]), 
  (["place":                "杭州树林",
    "start" :              "/d/hangzhou/forest3",]), 
  (["place":                "杭州南门外黄土大道",
    "start" :              "/d/hangzhou/spath1",]), 

});  

string *snake_name = ({ "眼镜蛇","响尾蛇","巨蝮蛇","金环蛇","银环蛇","菜花蛇","七步蛇","竹叶青","小青蛇","斑斓蛇","珊瑚蛇","鸡冠蛇","闪鳞蛇","斑管蛇","针尾蛇","泰攀蛇","小花蛇","铜斑蛇","损嘴蛇","乌梢蛇","滑鼠蛇","王锦蛇","灰鼠蛇 ","赤链蛇","玉斑锦蛇","翠青蛇","虎斑游蛇","乌游蛇","五步蛇","青环海蛇","烙铁头","丽纹蛇"}); 