#define G_DIR           "/domains/estergrym/towns/grymxoria"
#define G_OBJ          G_DIR + "/obj/"
#define G_NPC          G_DIR + "/npc/"
#define G_ROOM         G_DIR + "/room/"
#define NINJA "/domains/tairi/towns/tairi/npc/"
