/* This program is a part of RW mudlib 
 * See /doc/help/copyright for more info
 -----------------------------------------
 * File   : daemon.h
 * Author : 由 creator 產生
 * Date   : 
 * Note   : Include File.
 * Update :
 *  o 2005-00-00
 *
 -----------------------------------------
 */

#define ADVENTURE_D                              "/system/daemons/adventure_d.lpc"
#define AREA_D                                   "/system/daemons/area_d.lpc"
#define AREA_D_MAIN                              "/system/daemons/area_d_main.lpc"
#define AUCTION_D                                "/system/daemons/auction_d.lpc"
#define BIRTHDAY_D                               "/system/daemons/birthday_d.lpc"
#define BUG_D                                    "/system/daemons/bug_d.lpc"
#define BUILDING_D                               "/system/daemons/building_d.lpc"
#define CHANNEL_D                                "/system/daemons/channel_d.lpc"
#define CHAR_D                                   "/system/daemons/char_d.lpc"
#define CHINESE_D                                "/system/daemons/chinese_d.lpc"
#define CITY_D                                   "/system/daemons/city_d.lpc"
#define CITY_D_MAIN                              "/system/daemons/city_d_main.lpc"
#define CLEAN_D                                  "/system/daemons/clean_d.lpc"
#define COMBAT_D                                 "/system/daemons/combat_d.lpc"
#define COMMAND_D                                "/system/daemons/command_d.lpc"
#define DESCRIPTION_D                            "/system/daemons/description_d.lpc"
#define DICT_D                                   "/system/daemons/dict_d.lpc"
#define EMOTE_D                                  "/system/daemons/emote_d.lpc"
#define ENTERPRISE_D                             "/system/daemons/enterprise_d.lpc"
#define ESTATE_D                                 "/system/daemons/estate_d.lpc"
#define EXCHANGE_D                               "/system/daemons/exchange_d.lpc"
#define FINGER_D                                 "/system/daemons/finger_d.lpc"
#define FTP_D                                    "/system/daemons/ftp_d.lpc"
#define GRAPH_D                                  "/system/daemons/graph_d.lpc"
#define GROWTH_D                                 "/system/daemons/growth_d.lpc"
#define HTML_D                                   "/system/daemons/html_d.lpc"
#define HTTP_CLIENT_D                            "/system/daemons/http_client_d.lpc"
#define IM_D                                     "/system/daemons/im_d.lpc"
#define INTERMUD2_D                              "/system/daemons/intermud2_d.lpc"
#define IP_D                                     "/system/daemons/ip_d.lpc"
#define LABOR_D                                  "/system/daemons/labor_d.lpc"
#define LANGUAGE_D                               "/system/daemons/language_d.lpc"
#define LOGIN_D                                  "/system/daemons/login_d.lpc"
#define LOGOUT_D                                 "/system/daemons/logout_d.lpc"
#define MAIL_D                                   "/system/daemons/mail_d.lpc"
#define MAP_D                                    "/system/daemons/map_d.lpc"
#define MAPOB_D                                  "/system/daemons/mapob_d.lpc"
#define MATERIAL_D                               "/system/daemons/material_d.lpc"
#define MONEY_D                                  "/system/daemons/money_d.lpc"
#define MUD_D                                    "/system/daemons/mud_d.lpc"
#define NATURE_D                                 "/system/daemons/nature_d.lpc"
#define NETWORK_D                                "/system/daemons/network_d.lpc"
#define NEWS_D                                   "/system/daemons/news_d.lpc"
#define NUMBER_D                                 "/system/daemons/number_d.lpc"
#define PASSWORD_D                               "/system/daemons/password_d.lpc"
#define PPL_LOGIN_D                              "/system/daemons/ppl_login_d.lpc"
#define PRODUCT_D                                "/system/daemons/product_d.lpc"
#define QUANTITY_D                               "/system/daemons/quantity_d.lpc"
#define QUEST_D                                  "/system/daemons/quest_d.lpc"
#define QUESTION_D                               "/system/daemons/question_d.lpc"
#define REALNEWS_D                               "/system/daemons/realnews_d.lpc"
#define SALARY_D                                 "/system/daemons/salary_d.lpc"
#define SCHEDULE_D                               "/system/daemons/schedule_d.lpc"
#define SECURE_D                                 "/system/daemons/secure_d.lpc"
#define SERIAL_NUMBER_D                          "/system/daemons/serial_number_d.lpc"
#define SHOPPING_D                               "/system/daemons/shopping_d.lpc"
#define SKILL_D                                  "/system/daemons/skill_d.lpc"
#define SMTP_D                                   "/system/daemons/smtp_d.lpc"
#define SOCKET_D                                 "/system/daemons/socket_d.lpc"
#define SOCKET_OB                                "/system/daemons/socket_ob.lpc"
#define SYSDATABASE_D                            "/system/daemons/sysdatabase_d.lpc"
#define SYSTEM_D                                 "/system/daemons/system_d.lpc"
#define TAX_D                                    "/system/daemons/tax_d.lpc"
#define TERRAIN_D                                "/system/daemons/terrain_d.lpc"
#define TIME_D                                   "/system/daemons/time_d.lpc"
#define TOP_D                                    "/system/daemons/top_d.lpc"
#define TRANSLATE_D                              "/system/daemons/translate_d.lpc"
#define TREASURE_D                               "/system/daemons/treasure_d.lpc"
#define VIRTUAL_D                                "/system/daemons/virtual_d.lpc"
#define WHOIS_D                                  "/system/daemons/whois_d.lpc"
#define WIZ_LOGIN_D                              "/system/daemons/wiz_login_d.lpc"
#define ZONE_D                                   "/system/daemons/zone_d.lpc"

