#include <ansi.h>

mapping npcneed=([
"tiepipa"          :   HIC"铁琵琶"NOR,
"tongren"          :   HIY"独脚铜人"NOR,
"chuangwang baodao":   HIW"闯王宝刀"NOR,
"hujia daopu"      :   "胡家刀谱残篇",
"yu xiao"          :   HIG"玉萧"NOR,
"ruanwei jia"      :   HIY"软猬甲"NOR,
"shenghuo ling"    :   HIR"圣火令"NOR,
"bishuijian"       :   HIG"碧水剑"NOR,
"chanyi jian"      :   YEL"蝉翼剑"NOR,
"yitian jian"      :   HIC"倚天剑"NOR,
"wuqing dao"       :   HIB"无情刀"NOR,
"jingang zhao"     :   HIY"金刚罩"NOR,
"jinshe jian"      :   HIY"金蛇剑"NOR,
"xue dao"          :   RED"血刀"NOR,
"qingshui hulu"    :   "清水葫芦",
"puti zi"          :   HIW"菩提子"NOR,
"fumo dao"         :   HIW"伏魔刀"NOR,
"xuelian"          :   "天山雪莲",
"Zhenwu jian"      :   HIW"真武剑"NOR,
"lianxin dan"      :   HIR"炼心弹"NOR,
"bilin xing"       :   "碧磷星",
"menghan yao"      :   "蒙汗药",
"shu"              :   "正气诀",
"shu"              :   "紫氤吟",
"tian qi"          :   HIB"田七"NOR,
"wuchang dan"      :   HIR"无常丹"NOR,
"xiao jindan"      :   HIR"小金丹"NOR, 
"gao"              :   "冰雪翡翠糕",
"suanmei tang"     :   "酸梅汤",
"shoufa tu"        :   "天山折梅手法图上卷",
"shoufa tu"        :   "天山折梅手法图下卷",
"zhangfa tu"       :   "天山六阳掌法图上册",
"zhangfa tu"       :   "天山六阳掌法图下册",
"jian pu"          :   "天羽奇剑剑谱",
"xuantie jian"     :   HIB"玄铁剑"NOR,
"yufeng zhen"      :   HIY"玉蜂针" NOR,
"yinsuo jinling"   :   HIW"银索"HIY"金铃"NOR,
"yufeng jiang"     :   HIY"玉蜂浆"NOR,
"dumang dan"       :   MAG"毒蟒胆"NOR,
"dan"              :   "腹蛇胆",
"xionghuang"       :   "雄黄",
"baihua gao"       :   "百花腹蛇膏",
]);

