#define W_DIR(x) ("/d/city/npc/obj/"+x)

mapping familys = ([
        "五庄观" 	: ([
        	"class"	: "xian",
        	"skills": ({	"unarmed","wuxing-quan",
				"parry","fumo-zhang",
				"dodge","baguazhen",
				"spells","taiyi",
				"force","zhenyuan-force",
				"staff","fumo-zhang",
			}),
		"weapon": W_DIR("staff"),
		]),

	"南海普陀山"	: ([
		"class"	: "xian",
		"skills": ({	"unarmed","jienan-zhi",
				"parry","lunhui-zhang",
				"dodge","lotusmove",
				"force","lotusforce",
				"spells","buddhism",
				"staff","lunhui-zhang",
			}),
		"weapon": W_DIR("staff"),
		]),

	"方寸山三星洞"	: ([
		"class" : "xian",
		"skills": ({	"unarmed","puti-zhi",
				"parry","qianjun-bang",
				"dodge","jindouyun",
				"force","wuxiangforce",
				"spells","dao",
				"stick","qianjun-bang",
			}),
		"weapon": W_DIR("stick"),
		]),

	"东海龙宫"	: ([
		"class"	: "xian",
		"skills": ({	"unarmed","dragonfight",
				"parry","fengbo-cha",
				"dodge","dragonstep",
				"force","dragonforce",
				"spells","seashentong",
				"fork","fengbo-cha",
			}),
		"weapon": W_DIR("fork"),
		]),

	"月宫"		: ([
		"class"	: "xian",
		"skills": ({	"unarmed","baihua-zhang",
				"parry","snowsword",
				"dodge","moondance",
				"force","moonforce",
				"spells","moonshentong",
				"sword","snowsword",
			}),
		"weapon": W_DIR("sword"),
		]),

	"阎罗地府"	: ([
		"class"	: "xian",
                  "skills": ({    "unarmed","jinghun-zhang",
				"parry","kusang-bang",
				"dodge","ghost-steps",
				"force","tonsillit",
				"spells","gouhunshu",
				"stick","kusang-bang",
			}),
		"weapon": W_DIR("stick"),
		]),

        "昆仑山玉虚洞"	: ([
        	"class"	: "xian",
        	"skills": ({	"unarmed","kaitian-zhang",
        			"parry","dashen-bian",
        			"dodge","lingyunbu",
        			"force","xuanzong-force",
        			"spells","yuxu-spells",
        			"whip","dashen-bian",
        		}),
        	"weapon": W_DIR("whip"),
        	]),

        "三界散仙"	: ([
        	"class" : "xian",
        	"skills": ({	"unarmed","ice_fire_zhang",
        			"parry","spysword",
        			"dodge","binfen-steps",
        			"force","butian-force",
        			"spells","mysticism",
        			"sword","spysword",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"武圣门"	: ([
		"class"	: "xian",
        	"skills": ({	"unarmed","fumobashi",
        			"parry","wuying",
        			"dodge","mizongbu",
        			"force","xiantian",
        			"spells","feisheng",
        			"sword","wuying",
        		}),
        	"weapon": W_DIR("sword"),
        	]),
/*********************************************/
	"少林寺"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","jingang-leg",
                                "parry","zui-gun",
        			"dodge","shaolin-shenfa",
        			"force","yijinjing",
        			"spells","chanzong",
        			"stick","zui-gun",
        		}),
        	"weapon": W_DIR("stick"),
        	]),

	"神剑山庄"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","lianhuan-zhang",
        			"parry","duo-sword",
        			"dodge","shadowsteps",
        			"force","cloudforce",
        			"spells","xueying-xianfa",
        			"sword","duo-sword",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"蜀山剑派"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","hunyuan-zhang",
        			"parry","yujianshu",
        			"dodge","sevensteps",
        			"force","zixia-shengong",
        			"spells","taoism",
        			"sword","yujianshu",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"峨嵋派"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","jinding-zhang",
        			"parry","tianlei-sword",
        			"dodge","zhutian-bu",
        			"force","emeiforce",
        			"spells","mahayana",
        			"sword","tianlei-sword",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"剑客联盟"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","kongshoudao",
        			"parry","feitian-sword",
        			"dodge","fengyu-piaoxiang",
        			"force","guixi-force",
        			"spells","renshu",
        			"sword","feitian-sword",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"江湖浪子"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","lingxiyizhi",
        			"parry","mozi-sword",
        			"dodge","piaoxiang",
        			"force","wuji-force",
        			"spells","tianjijue",
        			"sword","mozi-sword",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"将军府"	: ([
		"class"	: "human",
        	"skills": ({	"unarmed","changquan",
        			"parry","sanban-axe",
        			"dodge","yanxing-steps",
        			"force","lengquan-force",
        			"spells","baguazhou",
        			"axe","sanban-axe",
        		}),
        	"weapon": W_DIR("axe"),
        	]),

	"明教"		: ([
		"class"	: "human",
        	"skills": ({	"unarmed","qishang-quan",
        			"parry","shenghuo-ling",
        			"dodge","qingfu-shenfa",
        			"force","jiuyang-shengong",
        			"spells","qiankun-danuoyi",
        			"sword","shenghuo-ling",
        		}),
        	"weapon": W_DIR("sword"),
        	]),
/*****************************************/
	"陷空山无底洞"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","yinfeng-zhua",
        			"parry","kugu-blade",
        			"dodge","lingfu-steps",
        			"force","huntian-qigong",
        			"spells","yaofa",
        			"blade","kugu-blade",
        		}),
        	"weapon": W_DIR("blade"),
        	]),

	"火云洞"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","moyun-shou",
        			"parry","wuyue-spear",
        			"dodge","moshenbu",
        			"force","huomoforce",
        			"spells","pingtian-dafa",
        			"spear","wuyue-spear",
        		}),
        	"weapon": W_DIR("spear"),
        	]),

	"大雪山"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","cuixin-zhang",
        			"parry","bainiao-jian",
        			"dodge","xiaoyaoyou",
        			"force","ningxie-force",
        			"spells","dengxian-dafa",
        			"sword","bainiao-jian",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"轩辕古墓"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","jiuyin-zhua",
        			"parry","qinghu-jian",
        			"dodge","kongming-steps",
        			"force","jiuyin-force",
        			"spells","youming-spells",
        			"sword","qinghu-jian",
        		}),
        	"weapon": W_DIR("sword"),
        	]),

	"盘丝洞"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","lanhua-shou",
        			"parry","yinsuo-jinling",
        			"dodge","yueying-wubu",
        			"force","jiuyin-xinjing",
        			"spells","pansi-dafa",
        			"whip","yinsuo-jinling",
        		}),
        	"weapon": W_DIR("whip"),
        	]),

	"三界山"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","lanhua-shou",
        			"parry","huxiaojian",
        			"dodge","zhaoyangbu",
        			"force","huntianforce",
        			"spells","tianmogong",
        			"sword","huxiaojian",
        		}),
        	"weapon": W_DIR("whip"),
        	]),

	"魔界"		: ([
		"class"	: "yao",
        	"skills": ({	"unarmed","shifo-zhi",
        			"parry","xueling-jian",
        			"dodge","moshenbu",
        			"force","heilian-force",
        			"spells","molian-spells",
        			"sword","xueling-jian",
        		}),
        	"weapon": W_DIR("sword"),
        	]),
]);
