#include <ansi.h>

mapping npcneed=([
"[1;31mxiuluo zhua[2;37;0m"          :   "[1;34m修罗[1;31m之爪[2;37;0m",
"zai cao"          :   "一堆杂草",
"wuji jing"        :   "乌鸡精",
"tao zi"           :   "大桃子",
"[1;31mlong yi[2;37;0m"          :   "[1;33m龙神[1;34m之翼[2;37;0m",
"zhuaxian sword"   :   "[1;37m诛仙剑[2;37;0m",
"yao dao"          :   "[1;34m妖刀[2;37;0m",
"xi fan"           :   "稀饭",
"roujia mo"        :   "肉夹馍",
"clasp"            :   "[33m银簪[2;37;0m",
"linggu sword"     :   "灵骨剑",
"mi fan"           :   "米饭",
"xun yu"           :   "熏鱼",
"kao ruzhu"        :   "烤乳猪",
"jinshan"          :   "锦绒褊衫",
"qixing cao"       :   "七星草",
"cloth"            :   "葛布长袍",
"feng mi"          :   "蜂蜜",
"xiao cai"         :   "小菜",
"mo mo"            :   "香油馍馍",
"mi han"           :   "密函",
"langya bang"      :   "短软狼牙棒",
"xiniu piyi"       :   "犀牛皮衣",
"chou gan"         :   "香油臭干",
"ying mukui"       :   "硬木盔",
"armor"            :   "锈铜甲",
"zui"              :   "[1;32m醉生梦死[2;37;0m", 
"fireblade"        :   "[1;31m火焰长刀[2;37;0m",
"xian yi"          :   "[1;37m仙衣[2;37;0m",
"tang"             :   "[33m五仙汤[2;37;0m",
"jiu dou"          :   "酒浸过的蚕豆",
"cloth"            :   "绿绒袍",
"shuer guo"        :   "[1;36m鼠儿果[2;37;0m",
"baihua niang"     :   "[1;35m百花酿[2;37;0m",
"rose"             :   "[1;31m红玫瑰[2;37;0m",
"xi jian"          :   "细剑",
"seng xie"         :   "僧鞋",
"shoes"            :   "圆口布鞋",
"shugan"           :   "树干",
"jingu zhou"       :   "[1;31m紧箍咒[2;37;0m",
"tie zhang"        :   "铁杖",
"xue lian"         :   "[1;37m雪莲[2;37;0m",
]);

