//Created by Pkyou@xyj  2002年 中秋节
// Update by waiwai@2002/12/05

mapping obstacles = ([
  "wuxingshan" : "  01. 脱困五行山",
  "huangfeng"  : "  02. 怪阻黄风岭",
  "yingchou"   : "  03. 鹰愁涧换马",
  "gao"        : "  04. 施法高老庄",
  "liusha"     : "  05. 流沙河收僧",
  "wuzhuang"   : "  06. 大闹五庄观",
  "baigu"      : "  07. 三打白骨精",
  "xinyuan"    : "  08. 真假美猴王",
  "baoxiang"   : "  09. 宝象国捎书",
  "pingding"   : "  10. 平顶山逢魔",
  "wuji"       : "  11. 乌鸡国救主",
  "huoyun"     : "  12. 火云洞降魔",
  "heishui"    : "  13. 黑水河沉没",
  "chechi"     : "  14. 车迟国兴僧",
  "tongtian"   : "  15. 陈家庄救童",
  "jindou"     : "  16. 金兜山遇怪",
  "nuerguo"    : "  17. 西梁国留婚",
  "dudi"       : "  18. 琵琶洞受苦",
  "firemount"  : "  19. 三骗芭蕉扇",
  "jilei"      : "  20. 积雷山伏牛",
  "jisaiguo"   : "  21. 祭赛国寻宝",
  "jingjiling" : "  22. 荆棘岭吟咏",
  "xiaoxitian" : "  23. 小雷音遇难",
  "zhuzi"      : "  24. 施为朱紫国",
  "pansi"      : "  25. 盘丝俘七精",
  "xueshan"    : "  26. 路阻狮驼岭",
  "biqiu"      : "  27. 比丘国救子",
  "wudidong"   : "  28. 三探无底洞",
  "qinfa"      : "  29. 步阻钦法国",
  "yinwu"      : "  30. 泪洒隐雾山",
  "fengxian"   : "  31. 凤仙郡求雨",
  "yuhua"      : "  32. 竹节山遭难",
  "jinping"    : "  33. 玄英洞受苦",
  "tianzhu"    : "  34. 天竺国招婚",
  "jz"         : "  35. 犯险金山寺",
  "heishui"    : "  36. 黑水收孽龙",
  "sc"         : "  37. 伏魔双叉岭",
]);
