#include <ansi.h>
mapping *job = ({
        ([      "job":                "翠花",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "白衣少女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "丫环",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "阿紫"
  ]),
        ([      "job":                "小青",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":               HIY"王难姑"NOR,
                "job_type":           "抓",
                "exp_bonus":            50,
        ]),
        ([      "job":                "寡妇",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "婢女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "维吾尔族妇女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),      
            ([      "job":                "白衣少女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "苏州少女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "牧羊女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "五姑",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "杨不悔",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "青衣小尼",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "村妇",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "纺纱女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "台夷妇女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "歌女",
                "job_type":           "抓",
                "exp_bonus":            10,    
]),
 ([      "job":                "南国姑娘",
"job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "小道姑",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "黄蓉",
                "job_type":           "抓",
                "exp_bonus":            50,
        ]),
        ([      "job":                "木婉清",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "岳灵珊",
                "job_type":           "抓",
                "exp_bonus":            30,
        ]),
        ([      "job":                "崔莺莺",
                "job_type":           "抓",          
  "exp_bonus":            20,
        ]),
        ([      "job":                "王夫人",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "双儿",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "程玉环",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "程遥伽",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "冷若霜",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "小昭",          
                  "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "卖花姑娘",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "采桑女",
                "job_type":           "抓",
                "exp_bonus":            10,
        ]),
        ([      "job":                "摆夷女子",
                "job_type":           "抓",
                "exp_bonus":            15,
        ]),
        ([      "job":                "台夷姑娘",
                "job_type":           "抓",
                "exp_bonus":            15,
        ]),
        ([      "job":                "养花女",
                "job_type":           "抓",
                "exp_bonus":            15,
 ]),
        ([      "job":                "苗族少女",
                "job_type":           "抓",
                "exp_bonus":            15,
        ]),
        ([      "job":                "养蚕女",
                "job_type":           "抓",
                "exp_bonus":            15,
        ]),
        ([      "job":                "方碧琳",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "李明霞",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
        ([      "job":                "苏梦清",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),  
         ([      "job":                "赵灵珠",
                "job_type":           "抓",
                "exp_bonus":            20,
        ]),
});
mapping query_job()
{
        return job[random(sizeof(job))];
}
