'\" t
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Van Jacobson.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)traceroute.8	8.1 (Berkeley) 6/6/93
'\"macro stdmacro
.\"
.nr X
.TH traceroute 8 "15 Oct 1998"
.SH NAME
traceroute \- display the routes that IP packets follow from one point 
to another
.SH SYNOPSIS
.LP
.B traceroute
[
.B \-adnruvAMOQU
] [
.BI \-w " wait"
] [
.BI \-S " start_ttl"
]
.ti +5n
[
.BI \-m " max_ttl"
] [
.BI \-p " port#"
] [
.BI \-q " nqueries"
] 
.ti +5n
[
.BI \-g " gateway"
] [
.BI \-t " tos"
] [
.BI \-s " src_addr"
]
.ti +5n
[
.BI \-g " router"
] host [
.I datasize
] 

.SH DESCRIPTION
The Internet is a large and complex aggregation of
network hardware, connected together by gateways.
Tracking the route one's packets follow (or finding the miscreant
gateway that's discarding your packets) can be difficult.
.I Traceroute
utilizes the IP protocol `time to live' field and attempts to elicit an
.I ICMP
.I TIME_EXCEEDED
response from each gateway along the path to some
host.
.PP
The only mandatory parameter is the destination host name or IP number.
The default probe datagram length is 38 bytes, but this may be increased
by specifying a packet size (in bytes) after the destination host
name.
.PP
.SH OPTIONS
other options are:
.TP
.B \-a 
Causes traceroute to quit after receiving 10 lost packets in one hop.
.TP
.B \-d
Turns on socket-level debugging for the IP packets. If you don't know
what this is, you shouldn't use it.
.TP
.B \-g 
.I gateway
Use Loose-Source and Record-Route IP options to route the packets through one
or more intermediate IP hosts.
.TP
.B \-S
.IStart TTL 
Specifies the minimum hop-count that traceroute will attempt to get to. It
defaults to 1 hop.  Use a larger value to skip the initial few hops.
.TP
.B \-m 
.Imax_ttl
Set the max time-to-live (max number of hops) used in outgoing probe
packets.  The default is 30 hops (the same default used for
.I TCP
connections). Use a smaller value to halt the traceroute process prematurely.
.TP
.B \-n
Print hop addresses numerically rather than symbolically and numerically
(saves a nameserver address-to-name lookup for each gateway found on the
path).
.TP
.B \-p 
.Iport
Set the base
UDP
.I port
number used in probes (default is 33434).
.I Traceroute
hopes that nothing is listening on
.I UDP
ports
.I base
to
.I base+nhops-1
at the destination host (so an
.I ICMP
.I PORT_UNREACHABLE
message will
be returned to terminate the route tracing).  If something is
listening on a port in the default range, this option can be used
to pick an unused port range.
.TP
.B \-q 
.Inqueries
Set the number of probes per ``ttl'' to
.I nqueries
(default is three probes). Use larger numbers with the -Q flag for better statistic gathering.
.TP
.B \-r
Bypass the normal routing tables and send directly to a host on an attached
network.
If the host is not on a directly-attached network,
an error is returned.
This option can be used to ping a local host through an interface
that has no route through it (e.g., after the interface was dropped by
routed (1m).
.TP
.B \-s
.I src_addr
Use the following IP address
(which must be given as an IP number, not
a hostname) as the source address in outgoing probe packets.  On
hosts with more than one IP address, this option can be used to
force the source address to be something other than the IP address
of the interface the probe packet is sent on.  If the IP address
is not one of this machine's interface addresses, an error is
returned and nothing is sent.
.TP
.B \-t 
.I tos
Set the
.I type-of-service
in probe packets to the following value (default zero).  The value must be
a decimal integer in the range 0 to 255.  This option can be used to
see if different types-of-service result in different paths.  (If you
are not running a 4.3 tahoe
or later system, this may be academic since the normal network
services like telnet and ftp don't let you control the
.I TOS ) .
Not all values of
.I TOS
are legal or
meaningful \- see the IP spec for definitions.  Useful values are
probably
.Ql \-t 16
(low delay) and
.Ql \-t 8
(high throughput).
.TP
.B \-u 
Use microsecond timestamps
.TP
.B \-v
Verbose output.  Received
.I ICMP
packets other than
.I TIME_EXCEEDED
and
.I UNREACHABLE Ns s
are listed.
.TP
.B \-w
Set the time (in seconds) to wait for a response to a probe (default 5
sec.).
.TP
.B \-A
Report Autonomous System Number at each hop from the Routing Arbiter project's
routing database (RADB).  The ASN displayed is the most specific ASN found for 
that route.  If multiple ASNs with equal specifity exist, they will be 
displayed separated by a "/".
.TP
.B \-M
This flag causes traceroute to do IP MTU discovery as specified in RFC1191. 
Note that this does not work going through all types of IP gateways.
.TP
.B \-O
This flag causes traceroute to look up the DNS owner of the inverse-domain
for each hop in the trace.
.TP
.B \-Q
Report delay statistics at each hop in the form of "(min/avg+-stddev/max)" (ms) 
rather than individual packet time.
.TP
.B \-U
Move on to the next hop after receiving any satisfactory response from the current hop.  That way hops with loss will get up to -n probes and hops with no loss will get just one.
.El
.PP
This program attempts to trace the route an IP packet would follow to some
internet host by launching
.Tn UDP
probe
packets with a small ttl (time to live) then listening for an
.I ICMP
"time exceeded" reply from a gateway.  We start our probes
with a ttl of one and increase by one until we get an
.I ICMP
"port unreachable"
(which means we got to "host") or hit a max (which
defaults to 30 hops & can be changed with the
.Fl m
flag).  Three
probes (changed with \-q
flag) are sent at each ttl setting and a
line is printed showing the ttl, address of the gateway and
round trip time of each probe.  If the probe answers come from
different gateways, the address of each responding system will
be printed.  If there is no response within a 3 sec. timeout
interval (changed with the \-w
flag), a "*" is printed for that
probe.
.PP
We don't want the destination
host to process the
.I UDP
probe packets so the destination port is set to an
unlikely value (if some clod on the destination is using that
value, it can be changed with the
\-p
flag).
.PP
.SH EXAMPLES
.nf
[yak 71]% traceroute nis.nsf.net.
traceroute to nis.nsf.net (35.1.1.48), 30 hops max, 56 byte packet
1  helios.ee.lbl.gov (128.3.112.1)  19 ms  19 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  39 ms  19 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  39 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  39 ms  40 ms  39 ms
5  ccn-nerif22.Berkeley.EDU (128.32.168.22)  39 ms  39 ms  39 ms
6  128.32.197.4 (128.32.197.4)  40 ms  59 ms  59 ms
7  131.119.2.5 (131.119.2.5)  59 ms  59 ms  59 ms
8  129.140.70.13 (129.140.70.13)  99 ms  99 ms  80 ms
9  129.140.71.6 (129.140.71.6)  139 ms  239 ms  319 ms
10  129.140.81.7 (129.140.81.7)  220 ms  199 ms  199 ms
11  nic.merit.edu (35.1.1.48)  239 ms  239 ms  239 ms

.fi
.PP
Note that lines 2 & 3 are the same.  This is due to a buggy
kernel on the 2nd hop system \- lbl-csam.arpa \- that forwards
packets with a zero ttl (a bug in the distributed version
of 4.3 BSD).
Note that you have to guess what path
the packets are taking cross-country since the NSFNet
(129.140)
doesn't supply address-to-name translations for its NSSes .
.PP
A more interesting example is:
.nf
[yak 72]% traceroute allspice.lcs.mit.edu.
traceroute to allspice.lcs.mit.edu (18.26.0.115), 30 hops max
1  helios.ee.lbl.gov (128.3.112.1)  0 ms  0 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  19 ms  19 ms  19 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  19 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  19 ms  39 ms  39 ms
5  ccn-nerif22.Berkeley.EDU (128.32.168.22)  20 ms  39 ms  39 ms
6  128.32.197.4 (128.32.197.4)  59 ms  119 ms  39 ms
7  131.119.2.5 (131.119.2.5)  59 ms  59 ms  39 ms
8  129.140.70.13 (129.140.70.13)  80 ms  79 ms  99 ms
9  129.140.71.6 (129.140.71.6)  139 ms  139 ms  159 ms
10  129.140.81.7 (129.140.81.7)  199 ms  180 ms  300 ms
11  129.140.72.17 (129.140.72.17)  300 ms  239 ms  239 ms
12  * * *
13  128.121.54.72 (128.121.54.72)  259 ms  499 ms  279 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  ALLSPICE.LCS.MIT.EDU (18.26.0.115)  339 ms  279 ms  279 ms

.fi
.PP
Note that the gateways 12, 14, 15, 16 & 17 hops away
either don't send ICMP
"time exceeded" messages or send them
with a ttl too small to reach us.  14 \- 17 are running the
MIT C Gateway code that doesn't send "time exceeded"s.  God
only knows what's going on with 12.
.PP
The silent gateway 12 in the above may be the result of a bug in
the 4.[23] BSD
network code (and its derivatives):  4.x (x <= 3)
sends an unreachable message using whatever ttl remains in the
original datagram.  Since, for gateways, the remaining ttl is
zero, the ICMP
"time exceeded" is guaranteed to not make it back
to us.  The behavior of this bug is slightly more interesting
when it appears on the destination system:
.nf
1  helios.ee.lbl.gov (128.3.112.1)  0 ms  0 ms  0 ms
2  lilac-dmc.Berkeley.EDU (128.32.216.1)  39 ms  19 ms  39 ms
3  lilac-dmc.Berkeley.EDU (128.32.216.1)  19 ms  39 ms  19 ms
4  ccngw-ner-cc.Berkeley.EDU (128.32.136.23)  39 ms  40 ms  19 ms
5  ccn-nerif35.Berkeley.EDU (128.32.168.35)  39 ms  39 ms  39 ms
6  csgw.Berkeley.EDU (128.32.133.254)  39 ms  59 ms  39 ms
7  * * *
8  * * *
9  * * *
10  * * *
11  * * *
12  * * *
13  rip.Berkeley.EDU (128.32.131.22)  59 ms !  39 ms !  39 ms !

.fi
.PP
Notice that there are 12 "gateways" (13 is the final
destination) and exactly the last half of them are "missing".
What's really happening is that rip (a Sun-3 running Sun OS3.5)
is using the ttl from our arriving datagram as the ttl in its
ICMP
reply.  So, the reply will time out on the return path
(with no notice sent to anyone since
ICMP's aren't sent for ICMP's )
until we probe with a ttl that's at least twice the path
length.  I.e., rip is really only 7 hops away.  A reply that
returns with a ttl of 1 is a clue this problem exists.
.I Traceroute
prints a "!" after the time if the ttl is <= 1.
Since vendors ship a lot of obsolete
(DEC Ns \'s
Ultrix, Sun 3.x) or
non-standard
(HPUX)
software, expect to see this problem
frequently and/or take care picking the target host of your
probes.
Other possible annotations after the time are
.I !H ,
.I !N ,
.I !P
(got a host, network or protocol unreachable, respectively),
.I !S
or
.I !F
(source route failed or fragmentation needed \- neither of these should
ever occur and the associated gateway is busted if you see one).  If
almost all the probes result in some kind of unreachable,
.I traceroute
will give up and exit.
.PP
Here's an example using the -A -Q and -q flags:
.PP
.nf 
[74] mjr@five:~> traceroute -A -Q -q 100 sprintlink.net
traceroute to sprintlink.net (199.0.55.90), 30 hops max, 40 byte packets
 1  Backbone-GW.ACES.NET (192.195.240.31) [AS3463]  (1.5 ms/3.4 ms(+-3.9 ms)/24.6 ms) 100/100 (100.00%)
 2  sl-ana-9-S4/4-6M.sprintlink.net (144.228.79.41) [AS1239]  (13.7 ms/36.7 ms(+-12.6 ms)/65.1 ms) 100/100 (100.00%)
 3  144.228.70.14 (144.228.70.14) [AS1239] (13.0 ms/63.2 ms(+-75.6 ms)/339.5 ms) 98/100 (100.00%)
 4  sl-fw-6-H2/0-T3.sprintlink.net (144.228.10.29) [AS1239] (42.7 ms/77.6 ms(+-19.0 ms)/142.8 ms) 100/100 (100.00%)
 5  sl-fw-8-F0/0.sprintlink.net (144.228.30.8) [AS1239] (37.7 ms/65.1 ms(+-13.9 ms)/93.8 ms) 100/100 (100.00%)
 6  sl-hrn-1-S1/1-T1.sprintlink.net (144.228.38.62) [AS1239] (74.4 ms/114.4 ms(+-30.4 ms)/245.5 ms) 85/100 (100.00%)
 7  tiny.sprintlink.net (199.0.55.90) [AS1239]  (74.4 ms/107.2 ms(+-13.8 ms)/136.9 ms) 100/100 (100.00%)
.fi
.PP

I would like to find out the route taken between a given router in BBN Planet's backbone to ftp.netcom.com.  I also want to skip the first two hops and start on hop #3.
.PP
.nf
[30] mjr:~> traceroute -S 3 -g 4.0.1.10 ftp.netcom.com
traceroute to ftp.netcom.com (206.217.29.2), 30 hops max, 52 byte packets
 3  paloalto-br2.bbnplanet.net (4.0.1.10)  61 ms  22 ms  18 ms
 4  sanjose1-br1.bbnplanet.net (4.0.1.9)  22 ms *  68 ms
 5  sanjose1-br1.bbnplanet.net (4.0.1.9)  21 ms  26 ms *
 6  198.32.136.15 (198.32.136.15)  521 ms  405 ms  247 ms
 7  h4-0-sjx-ca-gw1.netcom.net (163.179.232.89)  273 ms *  700 ms
 8  * sjx-ca-gw6.netcom.net (163.179.1.6)  659 ms  640 ms
 9  ftp.netcom.com (206.217.29.2)  910 ms  576 ms *

.PP
This program is intended for use in network testing, measurement
and management.
It should be used primarily for manual fault isolation.
Because of the load it could impose on the network, it is unwise to use
.I traceroute
during normal operations or from automated scripts.
.SH AUTHOR
Implemented by Van Jacobson from a suggestion by Steve Deering.  Debugged
by a cast of thousands with particularly cogent suggestions or fixes from
C. Philip Wood, Tim Seaver and Ken Adelman.  Extensive enhancements made
by Ehud Gavron <GAVRON@ACES.COM>.
.PP
Manual last updated 15 July, 1998 by Matthew Ramsey <mjr@blackened.com> 
.SH SEE ALSO
netstat(1), ping(8)
