#include <ansi.h>
mapping *quest = ({
([
	"name":  "长剑",  
	"id"  :  "sword",
	"tit" :  "新收弟子",
	"pot" :  1,
	"exp" :  10,
	"exp_required" : 0,
]),
([
	"name":  "八卦道袍",
	"id"  :  "cloth",
	"tit" :  "入门弟子",
	"pot" :  10,
	"exp" :  50,
        "exp_required" : 200,
]),
([
	"name":  "舞蝶彩衫",
	"id"  :  "skirt",
	"tit" :  "入室弟子",
	"pot" :  20,
	"exp" :  100,
        "exp_required" : 1000,
]),
([
	"name":  "诗词详解",
	"id"  :  "book",
	"tit" :  "喜堂弟子",
	"pot" :  20,
        "exp" :  100,
        "exp_required" : 2000,
]),
([
        "name":  "夜行衣",
	"id"  :  "black suit",
	"tit" :  "怒堂弟子",
	"pot" :  20,
        "exp" :  100,
        "exp_required" : 3000,
]),                                                // 5 
([
        "name":  "细剑",
	"id"  :  "sword",
	"tit" :  "悲堂弟子",
	"pot" :  20,
        "exp" :  100,
        "exp_required" : 4000,
]),
([
        "name":  "大红绸衫",
	"id"  :  "cloth",
	"tit" :  "狂堂弟子",
        "pot" :  20,
        "exp" :  100,
        "exp_required" : 5000,
]),
([
        "name":  "水下功夫简介",
	"id"  :  "diving book",
	"tit" :  "静堂弟子",
	"pot" :  20,
        "exp" :  100,
        "exp_required" : 6000,
]),
([
	"name":  "铜牌",
	"id"  :  "token",
	"tit" :  "潜堂弟子",
	"pot" :  20,
        "exp" :  100,
        "exp_required" : 7000,
]),
([
	 "name":  "一包糖",
	"id"  :  "yibaotang",
	"tit" :  "翔堂弟子",
        "pot" :  20,
        "exp" :  100,
        "exp_required" : 8000,
]),					// 10
([
        "name":  "地图的左上角",
	"id"  :  "map nw",
	"tit" :  "虚堂弟子",
	"pot" :  30,
	"exp" :  100,
        "exp_required" : 9000,
]),
([
        "name":  "密信",
        "id"  :  "letter",
	"tit" :  "亲传弟子",
	"pot" :  30,
        "exp" :  100,
        "exp_required" : 10000,
]),
([
        "name":  "贡品胭脂",
	"id"  :  "yanzhi",
        "tit" :  "大弟子",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 11000,
]),
([
        "name":  "青蛇胆",
	"id"  :  "qingshedan",
        "tit" :  "亲传大弟子",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 12000,
]),
([
        "name":  "燕尾金镖",
	"id"  :  "dart",
        "tit" :  "喜堂副香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 13000,
]),					//15
([
        "name":  "无名纸卷",
	"id"  :  "book",
        "tit" :  "喜堂香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 14000,
]), 
([
        "name":  "黄布长袍",
	"id"  :  "huang cloth",
        "tit" :  "怒堂副香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 15000,
]),
([
        "name":  "丹丸",
	"id"  :  "pill",
        "tit" :  "怒堂香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 16000,
]),
([
        "name":  "无我经",
	"id"  :  "book",
        "tit" :  "悲堂副香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 17000,
]), 
([
        "name":  "青布短裤",
	"id"  :  "duanku",
        "tit" :  "悲堂香主",
        "pot" :  30,
        "exp" :  100,
        "exp_required" : 18000,
]), 					//20
([
        "name":  "七星古砚",
	"id"  :  "7yan",
	"tit" :  "狂堂副香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 19000,
]),
([
        "name":  "囚服",
	"id"  :  "cloth",
	"tit" :  "狂堂香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 20000,
]),
([
        "name":  "纸片",
	"id"  :  "zhipian",
        "tit" :  "静堂副香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 21000,
]),
([
        "name":  "平龙认",
	"id"  :  "pinglongren",
        "tit" :  "静堂香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 22000,
]),
([
        "name":  "银盔甲",
	"id"  :  "armor",
        "tit" :  "潜堂副香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 23000,
]),					//25
([
        "name":  "桂花醇酒",
	"id"  :  "jiudai",
	"tit" :  "潜堂香主",
        "pot" :  40,
        "exp" :  100,
        "exp_required" : 24000,
]),
([
        "name":  GRN"黄金刀"NOR,
	"id"  :  "blade",
	"tit" :  "翔堂副香主",
        "pot" :  40,
        "exp" :  200,
	        "exp_required" : 28000,
]),
([
        "name":  "轰天锤",
	"id"  :  "hammer",
	"tit" :  "翔堂香主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 32000,
]),
([
        "name":  "断肠散",
	"id"  :  "duanchang",
	"tit" :  "虚堂副香主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 36000,
]),
([
        "name":  "毒经",
	"id"  :  "dujing",
	"tit" :  "虚堂香主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 40000,
]),					//30
([
	"name":  "桃花",
	"id"  :  "taohua",
	"tit" :  "喜堂副舵主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 44000,
]),
([
        "name":  "映月梅花",
	"id"  :  "yingyue",
	"tit" :  "怒堂副舵主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 48000,
]),
([
	"name":  "武昌鱼之珠",
	"id"  :  "perle",
	"tit" :  "悲堂副舵主",
	"pot" :  40,
	"exp" :  200,
	"exp_required" : 52000,
]),
([
        "name":  "烂铁剑",
	"id"  :  "lantiejian",
        "tit" :  "狂堂副舵主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 56000,
]),
([
        "name":  "旧盔甲",
	"id"  :  "jiu kuijia",
	"tit" :  "静堂副舵主",
        "pot" :  40,
        "exp" :  200,
        "exp_required" : 60000,
]),                                    //35

([
        "name":  "地图的左边",
	"id"  :  "map w",
	"tit" :  "潜堂副舵主",
	"pot" :  50,
        "exp" :  200,
        "exp_required" : 64000,
]),
([
        "name":  "暂无任务"
]),
([
        "name":  "兵符",
        "id"  :  "bingfu",      
]),
([
        "name":  "灵威冠",
	"id"  :  "hat",
]),
});


