#include <ansi.h>
mapping npcneed=([
 "chang pao"  :"白色长袍" ,
 "cao mei"  :"草莓" , 
 "chai"  :"柴" , 
 "cai dao"  :"柴刀" ,
 "fen"  :"蛇胆粉" , 
 "jin"  :"金蛇胆" ,
 "qing"  :"青蛇胆" ,
 "she rou"  :"蛇肉" , 
 "shoe"  :"绣花鞋" , 
 "tu rou"  :"兔肉" , 
 "gangzhang"  :"钢杖" , 
 "pi beixin"  :"皮背心" , 
 "sandals"  :"草鞋" , 
 "dabaicai"  :"大白菜" , 
 "duanjian"  :"短剑" , 
 "flower shoes"  :"绣花小鞋" , 
 "gou pi"  :"狗皮" , 
 "gou rou"  :"红烧狗肉" , 
 "hammer"  :"铁锤" , 
 "jiudai"  :"花雕酒袋" , 
 "jinchuang yao"  :"金创药" , 
 "kaoya"  :"烤鸭" , 
 "budai"  :"麻布袋" , 
 "piang"  :"夫妻肺片" , 
 "qingcai"  :"青菜" , 
 "guoqiao mixian"  :"过桥米线" , 
 "qiguo ji"  :"汽锅鸡" , 
 "stone"  :"大理石" , 
 "white cloth"  :"白绸衫" , 
 "xiao ao"  :"圆领小袄" , 
 "bocai fentiao"  :"菠菜粉条" , 
 "qing hulu"  :"青葫芦" , 
 "liuli qiezi"  :"琉璃茄子" , 
 "mala doufu"  :"麻辣豆腐" , 
 "qingshui hulu"  :"清水葫芦" , 
 "shanhu baicai"  :"珊瑚白菜" , 
 "zhudao"  :"竹刀" , 
 "zhujian"  :"竹剑" , 
 "zhuye"  :"竹叶" , 
 "saozhou"  :"扫帚" ,
 "cloth"  :"蓑衣" , 
 "shuzhi"  :"树枝" , 
 "tao shuzhi"  :"桃树枝" , 
 "jiutan"  :"白瓷酒坛" , 
 "zichou shan"  :"紫绸衫" , 
 "qian cenggao"  :"千层糕" , 
 "shao bing"  :"肉末烧饼" , 
 "wandou huang"  :"豌豆黄" , 
 "xiao shaomai"  :"小烧麦" , 
 "rou"  :"蒜泥白切肉" , 
 "bazhen gao"  :"八珍糕" , 
 "congyou baocui"  :"葱油薄脆" , 
 "diao pi"  :"貂皮" , 
 "gongyu gan"  :"弓鱼干" , 
 "jiangbao niurou"  :"酱爆牛肉" , 
 "tangpen"  :"荷花汤盆" , 
 "gao"  :"玫瑰绿豆糕" , 
 "cloth"  :"摔角粗衣" , 
 "xiaren"  :"清炒虾仁" , 
 "zaoliu yupian"  :"糟溜鱼片" , 
 "yaorou"  :"镇江肴肉" , 
 "meat"  :"羊肉" , 
 "biandan"  :"扁担" , 
 "caoxie"  :"草鞋" , 
 "cai dao"  :"菜刀" , 
 "cai kuang"  :"菜筐子" , 
 "chaihe"  :"柴禾" ,
 "chang pao"  :"长袍" , 
 "jiudai"  :"牛皮酒袋" , 
 "baicai"  :"翡翠白菜" , 
 "gangding"  :"钢钉" , 
 "gangzhang"  :"精钢杖" , 
 "cloth"  :"白布长袍" , 
 "tie beixin"  :"铁背心" , 
 "chan zhang"  :"禅杖" , 
 "feibiao"  :"飞镖" , 
 "lingshen san"  :"灵神散" , 
 "liushen wan"  :"六神丸" , 
 "nianhua san"  :"拈花散" , 
 "sanqing dan"  :"三清丹" , 
 "sanzijing"  :"三字经" , 
 "cloth"  :"长衫" ,
 "xiaojing dan"  :"小精丹" , 
 "xuqi wan"  :"虚气丸" , 
 "zhengqi wan"  :"正气丸" , 
 "shanzi"  :"檀香扇" ,
 "chuanjiang"  :"船浆" , 
 "jiandao"  :"花剪" , 
 "penghu"  :"喷壶" , 
 "xiang"  :"香" , 
 "tao"  :"水蜜桃" ,
 "duan shan"  :"短衫" , 
 "huashengmi"  :"花生米" , 
 "hu pi"  :"虎皮" , 
 "lang pi"  :"狼皮" , 
 "lie zhuang"  :"猎装" , 
 "putuan"  :"蒲团" , 
 "ren shen"  :"人参" , 
 "yangjing dan"  :"养精丹" , 
 "yanshuie"  :"盐水鹅" , 
 "zhuye"  :"竹叶" , 
 "niu rou"  :"牛肉" , 
 "you deng"  :"油灯" , 
 "doufu"  :"豆腐" , 
 "doufu"  :"家常豆腐" , 
 "lajiao"  :"辣椒" , 
 "tu rou"  :"红烧兔肉" , 
 "xiangyou"  :"香油" , 
 "yan"  :"盐巴" , 
 "jiangyou"  :"酱油" , 
 "shedan gao"  :"蛇胆膏" ,
 "wuliangye"  :"五粮液" , 
 "cha hua"  :HIY"落第秀才"NOR , 
 "cha hua"  :HIB"眼"HIW"儿媚"NOR , 
 "cha hua"  :HIR"红妆"HIW"素裹"NOR , 
 "cha hua"  :HIW"抓破"HIG"美"NOR"人"HIR"脸"NOR , 
 "cha hua"  :HIW"倚"HIG"栏"HIR"娇"NOR , 
 "cha hua"  :HIR"十八学士"NOR , 
 "cha hua"  :HIG"十三太保"NOR , 
 "cha hua"  :HIB"八仙过海"NOR , 
 "cha hua"  :HIR"七仙女"NOR , 
 "cha hua"  :MAG"风"WHT"尘三"HIR"侠"NOR , 
 "cha hua"  :HIR"二"WHT"乔"NOR , 
 "cha hua"  :HIG"八宝妆"NOR , 
 "cha hua"  :HIW"满月"NOR , 
 "cha hua"  :HIR"山茶花"NOR , 
 "dou peng"  :"斗篷" ,
 "junfu"  :"锦衣军服" , 
 "junfu"  :"黄衣军服" ,
 "fangsha ji"  :"纺纱机" , 
 "li"  :"大理雪梨" , 
 "duan qun"  :"摆夷短裙" , 
 "duan qun"  :"台夷短裙" , 
 "tong qun"  :"筒裙" , 
 "tou jin"  :"台夷头巾" , 
 "chang qun"  :"乌夷长裙" , 
 "da hui"  :"乌夷大麾" ,
 "qingshui doufu"  :HIW"清水豆腐"NOR , 
 "shuijing doufu"  :HIW"水晶豆腐"NOR , 
 "wuxiang huasheng"  :HIY"五香花生米"NOR , 
 "jiaoyan paigu"  :HIR"椒盐排骨"NOR , 
 "pangxie"  :HIC"清蒸螃蟹"NOR , 
 "shi gu"  :"尸骨" , 
 "fuling"  :YEL"茯苓"NOR ,
 "moyao"  :HIW"没药"NOR ,
 "tianqi"  :HIY"田七"NOR ,
 "xiongdan"  :HIR"熊胆"NOR ,
 "xuejie"  :RED"血竭"NOR ,
 "guiling gao"  :HIW"龟苓膏"NOR ,
 "bingfu"  :"兵服" , 
 "duangua"  :"小短褂" , 
 "xiang"  :"地藏菩萨像" , 
 "xiang"  :"观音菩萨像" ,
 "xiang"  :"金塔像" , 
 "jing"  :"妙法莲华经" ,
 "nidao"  :"泥刀" , 
 "xiang"  :"释迦牟尼佛像" ,
 "zhuding"  :"竹钉" , 
 "bishou"  :"匕首" , 
 "tie suanpan"  :"铁算盘" , 
 "yinyang-sword"  :"阴阳剑" , 
 "yin zhen"  :"银针" ,
 "gujian"  :"古剑" ,
 "leigong hong"  :"雷公轰" , 
 "shanzi"  :"扇子" ,
 "ban fu"  :"板斧" , 
 "da dao"  :"大刀" ,
 "she pi"  :"蛇皮" ,
 "junfu"  :"军服" ,
 "duijin guazi"  :"对衿褂子" , 
 "kan dao"  :"砍刀" , 
 "ken ao"  :"窄裉袄" , 
 "shell lace"  :"贝壳项链" ,
 "man dao"  :"蛮刀" , 
 "mao tan"  :"毛毯" , 
 "xiangbian qun"  :"白纱挑线镶边裙" , 
 "da fu"  :"大斧" , 
 "niuer dao"  :"牛耳尖刀" , 
 "bigaxe"  :"大板斧" , 
 "diao pi"  :"貂皮大衣" ,
 "xuanwei huotui"  :HIR"宣威火腿"NOR , 
 "ye er ba"  :HIG"叶儿粑"NOR , 
 "fish"  :YEL"宋嫂鱼"NOR , 
 "dachengjing"  :"大乘经" , 
 "daodejing"  :"道德经" , 
 "taihu tu"  :"太湖旅游图" ,
 "hat"  :"银色皮帽" , 
 "jin duan"  :"锦缎" , 
 "laoshan shen"  :"老山参" ,
 "mudi"  :"牧笛" , 
 "muyu"  :"木鱼" , 
 "hua ban"  :"花瓣" ,
 "shanzi"  :"檀香扇" , 
 "gao"  :"冰雪翡翠糕" ,
 "canhezhi"  :"参合指要诀" , 
 "tanyunshou"  :"探云手要诀" ,
 "tuling fu"  :"土灵符" , 
 "golden ring"  :"金戒指" ,
 "xifu"  :"西服" , 
 "yan"  :"香烟" ,
 "zuanshijiezhi"  :"钻石戒指" ,
 "jian pu"  :"天羽奇剑剑谱" , 
 "baiyun wan"  :"白云熊胆丸" , 
 "lingshen san"  :"灵神散" , 
 "liushen wan"  :"六神丸" , 
 "nianhua san"  :"拈花散" , 
 "sanqing dan"  :"三清丹" , 
 "xiaojing dan"  :"小精丹" , 
 "xuqi wan"  :"虚气丸" , 
 "zhengqi wan"  :"正气丸" , 
 "golden ring"  :"金戒指" ,
 "xifu"  :"西服" , 
 "yan"  :"香烟" ,
 "zuanshijiezhi"  :"钻石戒指" ,
 "jian pu"  :"天羽奇剑剑谱" , 
 "baiyun wan"  :"白云熊胆丸" , 
 "lingshen san"  :"灵神散" , 
 "liushen wan"  :"六神丸" , 
 "nianhua san"  :"拈花散" , 
 "sanqing dan"  :"三清丹" , 
 "xiaojing dan"  :"小精丹" , 
 "xuqi wan"  :"虚气丸" , 
 "zhengqi wan"  :"正气丸" , 
 "xiaojing dan"  :"小精丹" , 
 "xuqi wan"  :"虚气丸" , 
 "zhengqi wan"  :"正气丸" , 
 "xiaojing dan"  :"小精丹" , 
 "xuqi wan"  :"虚气丸" , 
 "zhengqi wan"  :"正气丸" , 
 "golden ring"  :"金戒指" ,
 "fuchen"  :"拂尘" , 
 "jia sha"  :"金边黑布袈裟" ,
 "pao"  :"青色道袍" , 
 "jia sha"  :"灰布镶边袈裟" ,
 "yao qin"  :"瑶琴" ,
 "cloth"  :"迦裟" , 
 "card1":"风雷堂令牌", 
 "golden ring" :"金戒指"   ,
 "card2"  :"白虎堂令牌" , 
 "card3"  :"青龙堂令牌" , 
 "card4"  :"天香堂令牌" , 
 "zhenzhu"  :"大珍珠" , 
 "book"  :"《四十二章经》" ,
 "daode jing"  :"《道德经》" , 
 "gaoyao"  :RED"膏"BLK"药"NOR , 
 "key"  :CYN"青铜钥匙"NOR , 
 "yu pei"  :HIC"玉佩"NOR , 
 "sword"  :"白练分水剑" , 
 "sword"  :"扁诸神剑" , 
 "duan di"  :HIG "短笛" NOR , 
 "er hu"  :HIY"二胡"NOR , 
 "sword"  :"古松残阙" , 
 "ping"  :HIC"雨后天青双耳瓶"NOR , 
 "shenxiang"  :HIW"白衣送子观音像"NOR , 
 "haier zheng"  :HIC"水蓝陶瓷孩儿枕"NOR , 
 "qiankun hu"  :HIR"玫瑰红乾坤壶"NOR , 
 "jinpin"  :HIW"乳白水净瓶"NOR , 
 "cloth"  :"五福朝寿衣" ,
 "guai zhang"  :"龙头拐杖" ,
 "guijia"  :"黑色龟甲" , 
 "jing"  :"《金刚般若波罗蜜经》" , 
 "jing"  :"《妙法莲花经》" , 
 "jing"  :"《维摩诘所说经》" , 
 "jing"  :"《萨昙分陀利经》" , 
 "jian pu"  :"天羽奇剑剑谱" ,
 "baiyun wan"  :"白云熊胆丸" ,
 "pao"  :WHT"灰色道袍"NOR , 
 "pao"  :HIG"青色道袍"NOR , 
 "shouwu"  :WHT"何首乌"NOR ,
 "fuchen"  :"乌柄拂尘" , 
 "guan fu"  :"五品官服" ,
 "chang pao"  :"阿拉伯长袍" , 
 "daopao"  :"破道袍" , 
 "cloth"  :"太极道袍" , 
 "wan dao"  :"阿拉伯弯刀" , 
 "yayi cloth"  :"衙役服" , 
 "roujing sword"  :"柔金锋" , 
 "zijin chui"  :"紫金锤" , 
 "tie suanpan"  :"铁算盘" ,
 "yinyang-sword"  :"阴阳剑" , 
 "yin zhen"  :"银针" , 
 "canhezhi"  :"参合指要诀" ,
 "tanyunshou"  :"探云手要诀" , 
 "tuling fu"  :"土灵符" , 
 "shan"  :"鹅黄绸衫" ,
 "shan"  :"藕色纱衫" ,
 "shu"  :"太极十三势" ,
 "nuer xiang"  :"女儿香" , 
 "duanyan"  :"端砚" , 
 "hu pi"  :HIY"虎皮"NOR , 
 "baiyu xiao"  :"白玉箫" ,
 "iron spear"  :"半截铁枪" , 
 "junfu"  :"军服" ,
 "ziyi"  :"灰色淄衣" ,
 "hanyangan"  :"旱烟杆" , 
 "hammer"  :"金刚杵" , 
 "niu jiao"  :"金牛角" , 
 "xifu"  :"西服" , 
 "yan"  :"香烟" , 
 "yuzuizi"  :"玉坠子" , 
 "yuzhuo"  :"玉镯" , 
 "zi_zhuzhang"  :"紫竹杖" , 
 "zuanshijiezhi"  :"钻石戒指" ,
 "iron spear"  :"铁枪" , 
 "xiao huolu"  :"红泥小火炉" , 
 "xiong dan"  :"熊胆" , 
 "tie li"  :"残破铁犁" , 
 "yao chu"  :"药锄" , 
 "jiaohuaji"  :"叫化鸡" , 
 "meigui"  :HIR"红玫瑰"NOR , 
 "cui yuzhuo"  :HIC"翠玉镯"NOR , 
 "skirt"  :"粗布裙" , 
 "cloth"  :"蓝色短褂" , 
 "feicui qun"  :"翡翠长裙" , 
 "cloth"  :"淡黄衫" , 
 "hubi"  :"湖笔" , 
 "deadleaf"  :"枯黄的叶" ,
 "qian"  :"灵签" ,
 "dou peng"  :"斗篷" , 
 "junfu"  :"锦衣军服" , 
 "junfu"  :"黄衣军服" , 
 "fangsha ji"  :"纺纱机" , 
 "jin duan"  :"锦缎" , 
 "laoshan shen"  :"老山参" ,
 "mudi"  :"牧笛" , 
 "muyu"  :"木鱼" , 
 "ruanjian"  :"软剑" ,
 "hua ban"  :"花瓣" , 
 "qingyi"  :"青衣" , 
 "zhuzhang"  :"青竹杖" , 
 "qingshu"  :"情书" , 
 "shoupa"  :"手帕" ,
 "gao"  :"冰雪翡翠糕" , 
 "gujian"  :"古剑" ,
 "leigong hong"  :"雷公轰" , 
 "hat"  :"银色皮帽" , 
 "jin duan"  :"锦缎" , 
 "wuliangye"  :"五粮液" ,
 "beike"  :"贝壳" , 
 "wucai beike"  :"五彩贝壳" ,
 "yu"  :HIC"青龙碧血玉"NOR , 
 "jiangjunzhang"  :"将军杖" , 
 "pomodao"  :"泼墨刀" , 
 "qixianjian"  :"七弦剑" , 
 "weiqizi"  :"围棋子" , 
 "tianxiang gao"  :HIC"天香断续膏"NOR ,
 "beike"  :"贝壳" ,
 "wucai beike"  :"五彩贝壳" ,
 "yu"  :HIC"青龙碧血玉"NOR , 
 "dodge book"  :"〖基本步法〗" ,
 "duan tielian"  :"断开的铁链" ,
 "fo chuan"  :"檀木佛串" , 
 "force book"  :"〖内功心诀〗" ,
 "skirt"  :"百褶裙" , 
 "cloth"  :"月白缁衣" , 
 "hanyue blade"  :HIG"寒月斩"NOR , 
 "lengyue blade"  :HIG"冷月斩"NOR , 
 "guozi"  :HIR"珊瑚果"NOR , 
 "sword book"  :"〖无名剑诀〗" ,
 "skirt"  :YEL"虎皮短裙"NOR , 
 "green ruyi"  :"绿如意" ,
 "baichou san"  :"白绸伞" , 
 "skirt"  :"素白长裙" , 
 "jiasha"  :"大红袈裟" ,
 "hua lan"  :"细编翠竹花蓝" , 
 "heimu ling"  :"黑木令" , 
 "kuihua baodian"  :"葵花宝典" , 
 "cloth"  :"红绸小衫" , 
 "leizhen dang"  :"雷震挡" , 
 "shutong gun"  :"熟铜棍" ,
 "zhen"  :"绣花针" ,
 "yang qin"  :HIC"扬琴"NOR ,
 "fochuan"  :"紫檀佛串" , 
 "jia sha"  :"护法袈裟" ,
 "jiangjunzhang"  :"将军杖" ,
 "pomodao"  :"泼墨刀" ,
 "qixianjian"  :"七弦剑" ,
 "weiqizi"  :"围棋子" ,
 "kulou tougu"  :"骷髅头骨" ,
 "jindao"  :YEL"金刀"NOR , 
 "gang ci"  :"峨嵋钢刺" ,
 "kulou"  :"白骨骷髅" ,
 "hammer"  :"流星锤" , 
 "taoguan"  :"陶罐" , 
 "qingci wan"  :"青瓷碗" , 
 "fuping"  :HIG"浮萍"NOR , 
 "zijin chui"  :"紫金锤" ,
 "tuling zhu"  :"土灵珠" , 
 "cloth"  :"公子衫" , 
 "yemingzhu"  :HIC"夜明珠"NOR ,
 "youming jian"  :RED"幽冥剑"NOR , 
 "boot"  :HIY"绣金福字屐"NOR , 
 "shu"  :"拳谱总诀" ,
 "bishuijian"  :"碧水剑" , 
 "pao"  :"白色道袍" ,
 "biyuzan"  :HIG"碧玉簪"NOR ,
 "wangguo"  :HIG"忘魂果"NOR , 
 "wushuang_jian"  :HIM"无双神剑"NOR , 
 "yuchang"  :HIC"鱼肠剑"NOR , 
 "zijindan"  :"紫金活络丹" ,
 "jinbanfu"  :"金板斧" ,
 "wujinfu"  :RED"乌金斧"NOR , 
 "xingfengdao"  :"腥风刀" ,
 "yinbanfu"  :"银板斧" , 
 "zijindao"  :MAG"紫金刀"NOR , 
 "boyu"  :"紫金钵盂" ,
 "songmo"  :"宋墨" ,
 "stone"  :"晶石" , 
 "leaf"  :RED"僳潞叶"NOR ,
 "taozi"  :"弥猴桃" , 
 "hailuo"  :"海螺" , 
 "skirt"  :"花短褂" , 
 "chui huoguan"  :"吹火管" ,
 "sipao"  :"丝袍" , 
 "skirt"  :"石榴裙" ,
 "zhenzhu"  :"珍珠项链" , 
 "cloth"  :"雪白长衫" ,
 "xiangjiu"  :"苏合香酒" , 
 "powan"  :"破碗" ,
 "jin he"  :"锦盒" , 
 "yaofang"  :"残破药方" ,
 "huang"  :"黄精" 
]);

