inherit SKILL;

mapping *quest = ({
        ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         60,
                "pot_bonus":          10,
                "score" :               5
        ]),
     ([      "quest":                "Î¬Îá¶û×å³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":        40,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            15,
                "score" :               20
        ]),
      ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":           10,
                "score" :               5
        ]),
         ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":          20,
                "pot_bonus":           6,
                "score" :               5
        ]),
       ([      "quest":                "Ìô·ò",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            15,
                "pot_bonus":            6,
                "score" :               5
        ]),
       ([      "quest":                "½øÏã¿Í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            4,
                "score" :               5
        ]),
       ([      "quest":                "Ð¡¹ð×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            7,
                "score" :               5
        ]),
          ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           30,
                "pot_bonus":            20,
                "score" :               5
        ]),
    ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":        30,
                "pot_bonus":          15,
                "score" :               20
        ]),
       ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           30,
                "pot_bonus":           7,
                "score" :               5
        ]),
 ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         40,
                "pot_bonus":          20,
                "score" :               5
        ]),
        ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            30,
                "pot_bonus":            13,
                "score" :               5
        ]),
      ([      "quest":                "»¤ËÂÎäÉ®",
                "quest_type":           "É±",
                "time":                300,
                "exp_bonus":        30,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "ÍÀµ¶",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "°¢À­Ä¾º±",
                "quest_type":           "É±",
                "time":                 450,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
  ([      "quest":                "Ì«¼«Ê®ÈýÊÆ",
                "quest_type":           "Ñ°",
                "time":                100,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          20,
                "pot_bonus":           12,
                "score" :              15
        ]),
    ([      "quest":                "»ÒÉ«µÀÅÛ",
                "quest_type":          "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         15,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹ÉÌÈË",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           16,
                "score" :               5
        ]),
      ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "°×ÒÂÉÙÅ®",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          20,
                "pot_bonus":           8,
                "score" :               5
        ]),
      ([      "quest":                "°¢×Ï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "ÃÅÎÀ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "À¼½£",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "ÇàÉ«µÀÅÛ",
                "quest_type":          "Ñ°",
                "time":                 500,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "ÐÇËÞÅÉ¹ÄÊÖ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         20,
                "pot_bonus":           8,
                "score" :               5
        ]),
   ([      "quest":                "Í­îà",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
   ([      "quest":                "±ÌË®½£",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":         30,
                "pot_bonus":         15,
                "score" :               5
        ]),
       ([      "quest":                "¹ÈÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹ÉÌÈË",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         40,
                "pot_bonus":           15,
                "score" :               5
        ]),
 ([      "quest":                "ÇåÐÄÉ¢",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "¾ÉÖñÆ¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       25,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "È­Æ××Ü¾÷",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       25,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "±¡¾î",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       25,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "Î§²±",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

