inherit SKILL;

mapping *quest = ({
        ([      "quest":                "¶ÎÓþ",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         600,
                "pot_bonus":          100,
                "score" :               5
        ]),      
        ([      "quest":                "¹ù¾¸",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         580,
                "pot_bonus":          100,
                "score" :               5
        ]),
        ([      "quest":                "ÐéÖñ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":           580,
                "pot_bonus":           100,
                "score" :               5
        ]),
      ([      "quest":                "½ðÂÖ·¨Íõ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":           580,
                "pot_bonus":           130,
                "score" :               5
        ]),
      ([      "quest":                "¼ÎÄ¾»î·ð",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":           580,
                "pot_bonus":           130,
                "score" :               5
        ]),
     ([      "quest":                "²¨Ë¹³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":         50,
                "pot_bonus":          20,
                "score" :               5
        ]),
     ([      "quest":                "Ä¾Óãé³",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         50,
                "pot_bonus":          40,
                "score" :               5
        ]),
     ([      "quest":                "°¢À­²®Íäµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       40,
                "pot_bonus":         30,
                "score" :               5
        ]),
    ([      "quest":                "¶·Åñ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       40,
                "pot_bonus":           30,
                "score" :               5
        ]),
   ([      "quest":                "ÃÉº¹Ò©",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         70,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³Â½üÄÏ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         550,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "³Â¼ÒÂå",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "Ä½ÈÝ¸´",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "Ä½ÈÝ²©",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "°àÊçæµ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "ºÎ×ãµÀ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "µ¶·æÀä",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "ÈÎÎÒÐÐ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "¶«·½²»°Ü",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         450,
                "pot_bonus":           120,
                "score" :               5
         ]),        
        ([      "quest":                "ºéÆß¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         480,
                "pot_bonus":           120,
                "score" :               5
        ]),
        ([      "quest":                "½ðÂÖ·¨Íõ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         480,
                "pot_bonus":           130,
                "score" :               5
        ]),
        ([      "quest":                "ð¯Ä¦ÖÇ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         480,
                "pot_bonus":           130,
                "score" :               5
        ]),
        ([      "quest":                "¶¡´ºÇï",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         480,
                "pot_bonus":           130,
                "score" :               5
        ]),
        ([      "quest":                "¶ÎÑÓÇì",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         260,
                "pot_bonus":           75,
                "score" :               5
        ]),
        ([      "quest":                "ÓáÁ«ÖÛ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         150,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "ÕÅËÉÏª",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         150,
                "pot_bonus":           25,
                "score" :               5
        ]),

        ([      "quest":                "Ïô·å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         300,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "âÎ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":        15,
                "score" :               5
        ]),
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 280,
                "exp_bonus":         100,
                "pot_bonus":          15,
                "score" :               150   //over
        ]),
       ([      "quest":                "°ÍÒÀ",
                "quest_type":           "É±",
                "time":                 780,
                "exp_bonus":         170,
                "pot_bonus":          35,
                "score" :               150   //over
        ]),
                ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":       80,
                "pot_bonus":         15,
                "score" :               50   //over
        ]),
        ([      "quest":                "½ð½äÖ¸",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         35,
                "score" :               50   //over
        ]),
                ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         150,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         300,
                "pot_bonus":           30,
                "score" :               20
        ]),
                ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       180,
                "pot_bonus":         20,
                "score" :               5
        ]),
                ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          100,
                "pot_bonus":           20,
                "score" :               5
        ]),
                ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         150,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         100,
                "pot_bonus":            20,
                "score" :               5
        ]),
       ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           220,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           220,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÂòÂôÌá",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           220,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           220,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           220,
                "pot_bonus":           30,
                "score" :               5
        ]),
    ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":       220,
                "pot_bonus":          35,
                "score" :               20
        ]),
 ([      "quest":                    "Ñò±Þ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         80,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            180,
                "pot_bonus":           20,
                "score" :               5
        ]),       
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         100,
                "pot_bonus":            20,
                "score" :               5
        ]),
       ([      "quest":                "Ç®ÀÏ±¾",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         60,
                "pot_bonus":           18,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         190,
                "pot_bonus":           30,
                "score" :               5
        ]),
      ([      "quest":                "À®Âï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          80,
                "pot_bonus":           27,
                "score" :               5
        ]),
      ([      "quest":                "ÏôÇïË®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          400,
                "pot_bonus":           70,
                "score" :               5
        ]),
      ([      "quest":                "ÏôÎ÷Â¥",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            450,
                "pot_bonus":            100,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
