inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Â³ÓÐ½Å",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":            90,
                "pot_bonus":            30,
                "score" :               5
        ]),
     ([      "quest":                "Î¬Îá¶û×å³¤ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":        40,
                "pot_bonus":         10,
                "score" :               5
        ]),
     ([      "quest":                "´ïÄ¦Áî",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":        40,
                "pot_bonus":         20,
                "score" :               5
        ]),
    ([      "quest":                "¸ßÑå³¬",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         60,
                "pot_bonus":           20,
                "score" :               10
        ]),
   ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":         5,
                "pot_bonus":           3,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            40,
                "pot_bonus":            15,
                "score" :               20
        ]),
     ([    "quest":                "½ð½äÖ¸",
                "quest_type":          "Ñ°",
                "time":                 200,
                "exp_bonus":          20,
                "pot_bonus":          9,
                "score" :               5
        ]),
      ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":           10,
                "score" :               5
        ]),
         ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":          20,
                "pot_bonus":           6,
                "score" :               5
        ]),
  ([      "quest":                    "¹·Æ¤",
                "quest_type":         "Ñ°",
                "time":                 100,
                "exp_bonus":          10,
                "pot_bonus":          5,
                "score" :               5
        ]),
       ([      "quest":                "·ëÌú½³",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "½øÏã¿Í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            4,
                "score" :               5
        ]),
       ([      "quest":                "Ð¡¹ð×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            7,
                "score" :               5
        ]),
          ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           30,
                "pot_bonus":            20,
                "score" :               5
        ]),
    ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":        20,  
                 "pot_bonus":          15,
                "score" :               20
        ]),
       ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           30,
                "pot_bonus":           7,
                "score" :               5
        ]),
 ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         40,
                "pot_bonus":          20,
                "score" :               5
        ]),
        ([      "quest":                "ÁÖÆ½Ö®",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            40,
                "pot_bonus":            13,
                "score" :               5
        ]),
      ([      "quest":                "»¤ËÂÎäÉ®",
                "quest_type":           "É±",
                "time":                100,
                "exp_bonus":        30,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "¹þÃÜ¹Ï",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "°¢À­Ä¾º±",
                "quest_type":           "É±",
                "time":                 450,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "Ì«¼«Ê®ÈýÊÆ",
                "quest_type":           "Ñ°",
                "time":                100,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "µÀÍ¯",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          20,
                "pot_bonus":           12,
                "score" :              15
        ]),
    ([      "quest":                "»ÒÉ«µÀÅÛ",
                "quest_type":          "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹ÉÌÈË",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          30,
                "pot_bonus":           16,
                "score" :               5
        ]),
      ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "°×ÒÂÉÙÅ®",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          20,
                "pot_bonus":           8,
                "score" :               5
        ]),
      ([      "quest":                "°¢×Ï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          40,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "ÃÅÎÀ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          30,
                "pot_bonus":           15,
                "score" :               5
        ]),
      ([      "quest":                "¹·Æ¤",
                "quest_type":           "Ñ°",
                "time":                 100,
                "exp_bonus":          10,
                "pot_bonus":           9,
                "score" :               5
        ]),
      ([      "quest":                "À¼½£",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          40,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "ÇàÉ«µÀÅÛ",
                "quest_type":          "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         15,
                "score" :               5
        ]),
 ([      "quest":                "ÐÇËÞÅÉ¹ÄÊÖ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
   ([      "quest":                "Í­îà",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "¹ÈÐéµÀ³¤",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹ÉÌÈË",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         40,
                "pot_bonus":           15,
                "score" :               5
        ]),
 ([      "quest":                "ÇåÐÄÉ¢",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       40,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "¾ÉÖñÆ¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "È­Æ××Ü¾÷",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "±¡¾î",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "Î§²±",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       40,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         15,
                "score" :             5
        ]),
        ([      "quest":                "·ëÌú½³",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         20,
                "score" :             5
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         20,
                "score" :             5
        ]),
        ([      "quest":                "Îä½«",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "½­°ÙÊ¤",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         90,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ìú±³ÐÄ",
                "quest_type":           "Ñ°",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "ÍÁ·Ë",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Öª¿ÍµÀ³¤",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ê·ÇàÉ½",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ïã²è",
                "quest_type":           "Ñ°",
                "time":               300,
                "exp_bonus":         30,
                "pot_bonus":         15,
                "score" :             5
        ]),
    ([      "quest":                "ÉñÁú½ÌÀÏÕß",
                "quest_type":          "É±",
                "time":                 500,
                "exp_bonus":       70,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "ôÕ×Ó",
                "quest_type":          "Ñ°",
                "time":                 200,
                "exp_bonus":       10,
                "pot_bonus":         5,
                "score" :               5
        ]),
    ([      "quest":                "°ü×Ó",
                "quest_type":          "Ñ°",
                "time":                 100,
                "exp_bonus":       8,
                "pot_bonus":         2,
                "score" :               5
        ]),
    ([      "quest":                "½ð»¨",
                "quest_type":          "É±",
                "time":                 800,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "Ìú»¤Ñü",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

