inherit SKILL;

mapping *quest = ({
   ([      "quest":                "ÃÉº¹Ò©",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         80,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 480,
                "exp_bonus":         100,
                "pot_bonus":          15,
                "score" :               150   //over
        ]),
       ([      "quest":                "°ÍÒÀ",
                "quest_type":           "É±",
                "time":                 650,
                "exp_bonus":         100,
                "pot_bonus":          35,
                "score" :               150   //over
        ]),
                ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":       80,
                "pot_bonus":         15,
                "score" :               50   //over
        ]),
        ([      "quest":                "½ð½äÖ¸",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":       60,
                "pot_bonus":         25,
                "score" :               50   //over
        ]),
                ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               20
        ]),
                ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
                ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":          100,
                "pot_bonus":           20,
                "score" :               5
        ]),
                ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         120,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         100,
                "pot_bonus":            20,
                "score" :               5
        ]),
       ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 520,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 420,
                "exp_bonus":           160,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
          ([      "quest":            "ÎÚÑ»",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           20,
                "pot_bonus":            5,
                "score" :               5
        ]),
    ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":       120,
                "pot_bonus":          35,
                "score" :               20
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":           20,
                "score" :               5
        ]),       
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         60,
                "pot_bonus":            20,
                "score" :               5
        ]),
       ([      "quest":                "Ç®ÀÏ±¾",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         60,
                "pot_bonus":           18,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         160,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                100,
                "exp_bonus":          5,
                "pot_bonus":          3,
                "score" :              5
      ]),
       ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :              15
        ]),
      ([      "quest":                "À®Âï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          80,
                "pot_bonus":           27,
                "score" :               5
        ]),
      ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":          30,
                "pot_bonus":           7,
                "score" :               5
        ]),
      ([      "quest":                "¸ßÑå³¬",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
      ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            20,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
