inherit SKILL;

mapping *quest = ({
        ([      "quest":                "Àî½ÌÍ·",
                "quest_type":           "É±",
                "time":                 280,
                "exp_bonus":         80,
                "pot_bonus":          15,
                "score" :               150   //over
        ]),
        ([      "quest":                "ÀÍµÂÅµ",
                "quest_type":           "É±",
                "time":                 380,
                "exp_bonus":         100,
                "pot_bonus":          25,
                "score" :               150   //over
        ]),
        ([      "quest":                "ËÎÔ¶ÇÅ",
                "quest_type":           "É±",
                "time":                 380,
                "exp_bonus":         150,
                "pot_bonus":          45,
                "score" :               150   //over
        ]),
                ([      "quest":                "·÷³¾",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":       60,
                "pot_bonus":         15,
                "score" :               50   //over
        ]),
                ([      "quest":                "´ÞÔ±Íâ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         90,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "º£¹«¹«",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         90,
                "pot_bonus":           30,
                "score" :               20
        ]),
                ([      "quest":                "ÆëÃ¼¹÷",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       60,
                "pot_bonus":         20,
                "score" :               5
        ]),
                ([      "quest":                "´ÞÝºÝº",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          70,
                "pot_bonus":           20,
                "score" :               5
        ]),
                ([      "quest":                "ÓÎÑ¶",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         120,
                "pot_bonus":           25,
                "score" :               5
        ]),
        ([      "quest":                "¿Õ¿Õ¶ù",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         80,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "½äµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "É¨µØÉ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         100,
                "pot_bonus":            20,
                "score" :               5
        ]),
       ([      "quest":                "¹Ü¼Ò",
                "quest_type":           "É±",
                "time":                 320,
                "exp_bonus":           80,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "ÀîÄª³î",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":           150,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "ÓàÆÅÆÅ",
                "quest_type":           "É±",
                "time":                 650,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "°¢·²Ìá",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           100,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "³ö³¾×Ó",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
       ([      "quest":                "Ã·½£",
                "quest_type":           "É±",
                "time":                 620,
                "exp_bonus":           120,
                "pot_bonus":           30,
                "score" :               5
        ]),
          ([      "quest":            "ÎÚÑ»",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           20,
                "pot_bonus":            5,
                "score" :               5
        ]),
    ([      "quest":                "Å·Ñô¿Ë",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           120,
                "pot_bonus":          35,
                "score" :               20
        ]),
       ([      "quest":                "Óæ·ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           120,
                "pot_bonus":           20,
                "score" :               5
        ]),
        ([      "quest":                "ÇåÎÅ±ÈÇð",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "×óÈ«",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            120,
                "pot_bonus":           20,
                "score" :               5
        ]),       
        ([      "quest":                "ÑÃÒÛ·þ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         60,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "ÉÕºìµÄÌú´¸",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":         60,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "Á÷Ã¥Í·",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         30,
                "pot_bonus":           5,
                "score" :               5
        ]),
 ([      "quest":                "ÑòÈâ´®",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       20,
                "pot_bonus":         9,
                "score" :               5
        ]),
       ([      "quest":                "ÓÎ¿Í",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         30,
                "pot_bonus":           8,
                "score" :               5
        ]),
        ([      "quest":                "ÕªÐÇ×Ó",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         150,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "Ã·³¬·ç",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":         170,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "Å£Æ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                100,
                "exp_bonus":          5,
                "pot_bonus":          3,
                "score" :              5
      ]),
       ([      "quest":                "¼Ò¶¡",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            50,
                "pot_bonus":            10,
                "score" :              15
        ]),
      ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":          30,
                "pot_bonus":           7,
                "score" :               5
        ]),
 ([      "quest":                "¾ÉÖñÆ¬",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "È­Æ××Ü¾÷",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "±¡¾î",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
 ([      "quest":                "Î§²±",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Ñ¾»·",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "·ëÌú½³",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "»ï¼Æ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "µêÐ¡¶þ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Îä½«",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "½­°ÙÊ¤",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         90,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ìú±³ÐÄ",
                "quest_type":           "Ñ°",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "ÍÁ·Ë",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Öª¿ÍµÀ³¤",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ê·ÇàÉ½",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ïã²è",
                "quest_type":           "Ñ°",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         25,
                "score" :             5
        ]),
    ([      "quest":                "ÉñÁú½ÌÀÏÕß",
                "quest_type":          "É±",
                "time":                 600,
                "exp_bonus":       80,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "ôÕ×Ó",
                "quest_type":          "Ñ°",
                "time":                 200,
                "exp_bonus":       10,
                "pot_bonus":         5,
                "score" :               5
        ]),
    ([      "quest":                "°ü×Ó",
                "quest_type":          "Ñ°",
                "time":                 100,
                "exp_bonus":       8,
                "pot_bonus":         2,
                "score" :               5
        ]),
    ([      "quest":                "½ð»¨",
                "quest_type":          "É±",
                "time":                 800,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "Ìú»¤Ñü",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),  
    ([      "quest":                "ÉñÁú»¨",
                "quest_type":          "Ñ°",
                "time":                 400,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),   
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

