inherit SKILL;

mapping *quest = ({
        ([      "quest":                "∂Œ”˛",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         160,
                "pot_bonus":          30,
                "score" :               5
        ]),      
        ([      "quest":                "π˘æ∏",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         180,
                "pot_bonus":          40,
                "score" :               5
        ]),
        ([      "quest":                "√∑≥¨∑Á",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         180,
                "pot_bonus":          40,
                "score" :               5
        ]),
        ([      "quest":                "”Ò÷Ò’»",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         160,
                "pot_bonus":          30,
                "score" :               5
        ]),
        ([      "quest":                "”ÒÛÔ",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         160,
                "pot_bonus":          40,
                "score" :               5
        ]),
        ([      "quest":                "–È÷Ò",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":           180,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "ºÚ≥§¿œ",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":           170,
                "pot_bonus":           30,
                "score" :               5
        ]),
      ([      "quest":                "Ω¬÷∑®Õı",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":           180,
                "pot_bonus":           40,
                "score" :               5
        ]),
      ([      "quest":                "ºŒƒæªÓ∑",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":           180,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "≤®Àπ≥§≈€",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":         120,
                "pot_bonus":          20,
                "score" :               5
        ]),
     ([      "quest":                "ƒæ”„È≥",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         120,
                "pot_bonus":          40,
                "score" :               5
        ]),
     ([      "quest":                "∞¢¿≠≤ÆÕ‰µ∂",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":       120,
                "pot_bonus":         30,
                "score" :               5
        ]),
    ([      "quest":                "∂∑≈Ò",
                "quest_type":           "—∞",
                "time":                 500,
                "exp_bonus":       100,
                "pot_bonus":           30,
                "score" :               5
        ]),
   ([      "quest":                "√…∫π“©",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         100,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                " ÃŒ¿",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
         ]),        
        ([      "quest":                "∫Ï“¬Œ‰ ø",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":         80,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "Ω¬÷∑®Õı",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         180,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "«‡“¬Œ‰ ø",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "∞◊“¬Œ‰ ø",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":         120,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "∂Œ—”«Ï",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         170,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "”·¡´÷€",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         150,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "’≈À…œ™",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         150,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "œÙ∑Â",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         180,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "‚Œ",
                "quest_type":          "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":        15,
                "score" :               5
        ]),
        ([      "quest":                "Ω≠∞Ÿ §",
                "quest_type":           "…±",
                "time":               300,
                "exp_bonus":         90,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Ã˙±≥–ƒ",
                "quest_type":           "—∞",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "Õ¡∑À",
                "quest_type":           "…±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "÷™øÕµ¿≥§",
                "quest_type":           "…±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                " ∑«‡…Ω",
                "quest_type":           "…±",
                "time":               200,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "√Ω∆≈",
                "quest_type":           "…±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
        ([      "quest":                "œ„≤Ë",
                "quest_type":           "—∞",
                "time":               300,
                "exp_bonus":         40,
                "pot_bonus":         20,
                "score" :             5
        ]),
        ([      "quest":                "«Â∑®±»«",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
        ([      "quest":                "«Â¿÷±»«",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
        ([      "quest":                "‘¿¡È…∫",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "…Ò¡˙ΩÃ¿œ’ﬂ",
                "quest_type":          "…±",
                "time":                 400,
                "exp_bonus":       80,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "Ù’◊”",
                "quest_type":          "—∞",
                "time":                 200,
                "exp_bonus":       10,
                "pot_bonus":         5,
                "score" :               5
        ]),
    ([      "quest":                "∞¸◊”",
                "quest_type":          "—∞",
                "time":                 100,
                "exp_bonus":       8,
                "pot_bonus":         2,
                "score" :               5
        ]),
    ([      "quest":                "Ωª®",
                "quest_type":          "…±",
                "time":                 600,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),
    ([      "quest":                "Ã˙ª§—¸",
                "quest_type":          "—∞",
                "time":                 600,
                "exp_bonus":       40,
                "pot_bonus":         15,
                "score" :               5
        ]),  
    ([      "quest":                "…Ò¡˙ª®",
                "quest_type":          "—∞",
                "time":                 300,
                "exp_bonus":       30,
                "pot_bonus":         15,
                "score" :               5
        ]),
        ([      "quest":                "À’–«∫”",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         180,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "ø›»Ÿ",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         180,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "À´∂˘",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "Œ‚÷Æ»Ÿ",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         60,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "≈Æπ‹º“",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         50,
                "pot_bonus":           10,
                "score" :               5
        ]), 
        ([      "quest":                "øµ«◊Õı",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         100,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "«‡≤º≈€",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          80,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "…Æ√±",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          80,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "«Â–ƒ…¢",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          80,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "–€ª∆",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          40,
                "pot_bonus":           5,
                "score" :               5
        ]),
        ([      "quest":                "«Â–ƒ…¢",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          80,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "–Âª®–°–¨",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          20,
                "pot_bonus":           5,
                "score" :               5
        ]),
        ([      "quest":                "¥÷¥≈¥ÛÕÎ",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          20,
                "pot_bonus":           5,
                "score" :               5
        ]),
        ([      "quest":                "–€ª∆",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":          100,
                "pot_bonus":           20,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

