#define CATA_DIR      "/domains/frostmarches/areas/catacombs/"
#define CATA_NPC      CATA_DIR "npc/"
#define CATA_OBJ      CATA_DIR "obj/"
#define CATA_ROOM     CATA_DIR "room/"
#define CATA_TREASURE CATA_OBJ "treasure/"
