#define BASE "/d/Dark/Prime/"
#define ROOMS(x) BASE + "rooms/" + "x"
#define MON(x) BASE + "mon/" + "x"
#define OBJ(x) BASE + "obj/" + "x"
#define WIZ(x) BASE + "wiz/" + "x"
#define W_WIZ "/d/Wizard/"
#define BOARDS(x) W_WIZ + "rooms/" + "x"
#define GUILD "/d/guilds/"
#define G_NECRO GUILD + "necromancers/"
#define G_NEC_ROOMS G_NECRO + "rooms/" + "x"
