mapping level_name = ([
        "初级马匹"  : ({
                        ({"青骓","白蹄乌","逸群","绝群","绝地",}),
                        ({"绝尘","飞翩","浮云","翻羽","腾雾",}),
                        ({"白义","渠黄","华骝","绿耳",}),
                        ({"盗骊","骐骥","纤离","蹑景","紫燕骝",}),
                        ({"龙子","嶙驹","乌孙","西极","萧稍","步景","蒲稍","龙文","鱼目",}),
                }),
        "初级战马"  :  ({
                        ({"追风","追电","赤电","挟翼","什伐赤",}),
                        ({"铜爵","晨凫","骕骦","宛天马","禄螭骢","闪电追风驹",}),
                        ({"超光","盗骊","踰轮","紫骍","飒露紫","照夜玉狮子","踢雪乌骓",}),
                        ({"特勒骠","奔宵","越影","逾辉","爪黄飞电","骅骝","绿耳","赤骥",}),   
                        ({"雷首","翠龙","骐骥","赤兔"}),
                }),
        "初级青牛" :  ({
                        ({"青牛",}),
                        ({"五色神牛",}),
                        ({"四不象",}),
                        ({"战象",}),
                        ({"猛犸",}),
                }),
        "初级战狐" :  ({
                        ({"战狐",}),
                        ({"厉狐",}),
                        ({"诡狐",}),
                        ({"九尾妖狐",}),
                        ({"青丘之主",}),
                }),
        "初级鬼狼" :  ({
                        ({"鬼狼",}),
                        ({"迅狼",}),
                        ({"暴狼",}),
                        ({"天狼",}),
                        ({"暗夜之王",}),
                }),
        "初级豹骑" :   ({
                        ({"豹骑",}),
                        ({"虎豹骑",}),
                        ({"云豹骑",}),
                        ({"石生兽",}),
                        ({"开明兽",}),
                }),
        "初级虎骑" :   ({
                        ({"虎骑",}),
                        ({"黑虎骑",}),
                        ({"金刚虎",}),
                        ({"嗜魂虎",}),
                        ({"五色金虎",}),
                }),
        "初级狮骑"  :   ({
                        ({"狮骑",}),
                        ({"狮王",}),
                        ({"九头狮",}),
                        ({"银羽金毛喉",}),
                        ({"玄天百头狮",}),
                }),
                        
        "初级金猪"  :   ({
                        ({"金猪",}),
                        ({"玛瑙猪",}),
                        ({"翡翠猪",}),
                        ({"钻石猪",}),
                        ({"万福猪",}),
                }),
        "初级泰羊"  :   ({
                        ({"泰羊",}),    
                        ({"金泰羊",}),
                        ({"独角兽",}),  
                        ({"三色飞翼独角兽",}),  
                        ({"山丘之王",}),
                }),
        "初级巴蛇"  :   ({
                        ({"巴蛇",}),    
                        ({"火蛇",}),
                        ({"翼蛇",}),    
                        ({"九头蛇",}),
                        ({"北荒九头蛇",}),
                }),     "初级鹏鸟"  :   ({
                        ({"鹏鸟",}),    
                        ({"雪雕",}),    
                        ({"食人金雕",}),        
                        ({"定风迅烈雕",}),      
                        ({"七色凤凰",}),
                }),
        "初级麒麟"  :   ({
                        ({"麒麟",}),    
                        ({"黑麒麟",}),
                        ({"墨麒麟",}),  
                        ({"血麒麟",}),  
                        ({"玉麒麟",}),
                }),                     
        "初级玄武"  :   ({
                        ({"玄武",}),    
                        ({"双翼玄武",}),        
                        ({"四翼玄武",}),        
                        ({"六翼玄武",}),        
                        ({"大地之主",}),
                }),
        "初级朱雀"  :   ({
                        ({"朱雀",}),    
                        ({"双翼朱雀",}),        
                        ({"四翼朱雀",}),        
                        ({"六翼朱雀",}),        
                        ({"火焰之主",}),
                }),
        "初级白虎"  :   ({
                        ({"白虎",}),    
                        ({"双翼白虎",}),        
                        ({"四翼白虎",}),        
                        ({"六翼白虎",}),        
                        ({"万兽之主",}),
                }),                     
        "初级青龙"  :   ({
                        ({"青龙",}),    
                        ({"双翼青龙",}),        
                        ({"四翼青龙",}),        
                        ({"六翼青龙",}),        
                        ({"天空之主",}),
                }),
]);

string *pet_adds = ({
        ({"dodge"}),
        ({"dodge","intelligence",}),
        ({"dodge","parry","intelligence",}),
        ({"dodge","parry","intelligence","constitution",}),
        ({"force","dodge","parry","intelligence","constitution",}),
        ({"force","dodge","parry","intelligence","constitution","spirituality",}),
        ({"force","dodge","parry","intelligence","constitution","spirituality","interate",}),
        ({"force","dodge","parry","intelligence","constitution","spirituality","interate","personality",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure"}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure"}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure"}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure","strength",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure","strength",}),
        ({"force","dodge","parry","spells","intelligence","constitution","spirituality","interate","personality","courage","composure","strength","karma"}),
});

