 I.历史背景：
 
             幽国城；原本是一个小市集，由於往南方探险的冒险者增多，一些
             因应而生的商店也随之增加，住家也慢慢增加，西方盗贼的兴起，
             使得当地的居民组织起来，皇上也派诸候到此治理，也就是幽国城
             王室，民间组织和官方组织合力对抗盗贼的入侵，然而盗贼的实力
             也不容小觑，数次征战让幽国城几乎疲於应付，於是王室黄榜告民
             ，徵求正义之士协防幽国城，吸引不少想试试自己身手的人前来，
             使得战况进入僵持的状态，双方都无法占到绝对的上风，然而每隔
             一段时间，盗贼便会大举入侵，令幽国城民烦不胜烦。

 II.商店：

     一商店一银行一药店(需战功)

 III.任务概要： 
       
                从帮魔法师找一本书开始，为了得到书房的使用权，再帮
                助王子追求女游侠，寻找东西打动游侠的芳心，最後终於
                取得书房的使用权，找到书拿给魔法师即完成任务。

 IV.怪物：

怪物名称     档名     等级   AC/DB  WC  伤害范围  武器装备    特殊能力
(*号表示是战争中的 **表示是任务中的)
**小童       boy       7     30/10  22   10 - 20   拂尘       12级以上会被
                                                              踢出去dam ram(10)
谈军         captain1  15    66/27  62   25 - 39   邀月护胫   追人
                                                   封千里
何峻         captain2  15    66/28  52   30 - 42   逍遥帽     追人
                                                   夺命刀
容群         captain3  15    75/23  52   24 - 39   雷动手套   追人
                                                   闪电爪
*张清        chang     19    95/40  90   38 - 70   狴犴掩心镜 飞石打人
                                                   冷铁□猊靴 (damage none 30
                                                   龙虎战袍    or flee 
                                                   柳叶贯金甲  or block_attack 3
                                                   九云凤翅盔 )
                                                   镔铁银枪
钱先生       cheng     1     5/2    3     1 - 3               不能打
幽国城守卫   guard     13    63/9   37    15 - 35  钢锁子甲
                                                   铁头盔
                                                   铁长枪
幽国城守卫队长 guard1  16    63/24  58    30 - 54  钢锁子甲
                                                   铁头盔
                                                   铁长枪
汗血宝马     horse1    12    35/0   36    16 - 35             载重155kg
赤兔马       horse2    14    35/0   36    16 - 35             载重175kg
修竹阁阁主   host      19    76/40  82    30 - 52  云鹤冠     卖酒
                                                   乾坤戒     特攻 mental
                                                   青玉符        35+ran(30)
                                                   玄机履
                                                   碧竹袍
                                                   墨竹剑
*焦挺        jau       15    70/40  70    31 - 52  青铜护心镜  特攻 dam 25
                                                   吊墩靴
                                                   绯红团花战袍
                                                   乾红凹面巾
幽国城城主   king      19    95/45  72    35 - 65  皇者之戒    特攻 cold 40 or 
                                                   金王冠           fire 40 or
                                                   幽皇龙袍         electric 40
                                                   疾风袖剑*2
**美尔琳思   mage      19    90/45  76    33 - 53  原力护盾   双重魔法(一大一小)
                                                   光魔杖
**萧是然     paladin   18    93/40  80    35 - 56  金织履      特攻 magic 30 or
                                                   旅者之袍         divine 38 or
                                                   金丝绑腿         mental 45
                                                   龙甲挡      
                                                   潇湘夜雨  
幽国城捕快   police    8     50/18  33    15 - 23  捕快制服
                                                   勾魂□  
**幽国城王子 prince    17    81/40  71    30 - 47  束发金簪
                                                   麒麟衣
                                                   赶月流星
幽国城皇后   queen     18    68/40  70    29 - 50  白金臂环    描弱点+神经
                                                   七彩凤裳
                                                   柳眉刃
幽国城皇家守卫 royalguard 16 74/30  76    29 - 42  钢靴
                                                   钢战盔
                                                   钢战甲
                                                   双手巨剑
佐佐木小次郎 samurai   19    90/40  81    40 - 70  白菊武袍    特攻(全部)
                                                   草鞋        65+ran(10)
                                                   天之丛云   
*单廷□      shan      17    86/41  82    35 - 56  嵌线云跟靴  特攻 cold 30
                                                   点翠团花征袍
                                                   熊皮乌油铠
                                                   浑铁四方帽
                                                   黑杆枪
*山贼    small_bandit  7     20/8   24    13 - 22  朴刀
枪棒教头     teacher1  14    60/35  65    30 - 40  短武服
                                                   镔铁长棍
拳法教头     teacher2  14    70/35  65    30 - 40  短武服
                                                   铁拳套
店小二       waiter    3     15/6   8      5 - 11  
**流浪汉     wanderer  1      5/2   8      4 - 8  
*魏定国      wei       17    86/40  76    35 - 50  翠云锦跟靴  特攻 fire 30
                                                   云霞绛红袍
                                                   兽面□猊铠
                                                   朱红点金束发盔
                                                   熟铜刀
*燕青        yan       15    68/38  72    38 - 53  裹金生铁掩心
                                                   金线皂朝靴
                                                   紫绣团花战袍
                                                   皂纱簇花巾
                                                   川弩

 V.武器：

武器名称    档案名称  重量(kg)   武器类别   WC   伤害范围   特殊攻击
(*号表示是战争中的)
 阎王斧     axe       13         axe        25   15-27      bleeding 10      
 夺命刀     blade1    9          longblade  30   20-32      bleeding 10
*熟铜刀     blade3    28         longblade  32   20-34
*川弩       bow       8          blunt      30   18-30      纯叙述
 勾魂□     chain     6          whip       15   10-15
 闪电爪     claw      8          unarmed    30   17-30
 镔铁长棍   club1     12         blunt      35   20-34
 拂尘       club2     6          blunt      15   8-15       纯叙述
 柳眉刃     dagger    3          dagger     40   24-37   (女生用变成 43,26,39
                                                          & 加 anatomlogy 10)
 铁拳套     fist      8          unarmed    30   20-30
*镔铁银枪   spear1    15         thrusting  43   23-40   (骑马变成 45,25,45)
*黑杆枪     spear2    20         thrusting  35   15-36  
 铁长枪     spear3    15         thrusting  25   10-24
 赶月流星   star      18         chain      37   25-40      纯叙述
 墨竹剑     sword1    10         longblade  35   25-32
 双手巨剑   sword2    20         longblade  35   19-37
 潇湘夜雨   sword3    13         longblade  40   25-36      纯叙述
 天之丛云   sword4    15         longblade  40   20-40     
                                                            
      alignment 10000~50000  (42,22,45)
                50000~100000 (44,24,47)
                100000~200000(45,26,48)
                200000~330000(46,28,49)  
                330000~450000(47,30,50)  
                >450000      (48,30,55)  

 疾风袖剑   sword5    8          shortblade 35   15-30    纯叙述   
 光魔杖     wand      6         wand       40   20-35    divine 40
 封千里     whip      7          whip       30   20-32

 VI.

防具名称    档案名称  重量(kg)   型态    质料        AC/DB    特殊效果
(*号表示是战争中的)
 青玉符     amulet1      2       misc    elemental   0/4      electric -20
                                                              fire 10 
                                                              magic 30
*狴犴掩心镜 amulet2      7       misc    heavy_metal 0/4      
*青铜护心镜 amulet3      3       misc    heavy_metal 0/4      
*裹金生铁掩心 amulet4    3.5     misc    heavy_metal 0/4
 白金臂环   armband      3       arms    heavy_metal 4/4
 玄机履     boot1        4.5     feet    cloth       7/2      sneak 6 
*金线皂朝靴 boot2        7       feet    leather     5/2      
*冷铁□猊靴 boot3        10      feet    heavy_metal 8/0    
*嵌线云跟靴 boot4        8       feet    leather     6/2
*翠云锦跟靴 boot5        8.5     feet    leather     6/1
*吊墩靴     boot6        4.5     feet    cloth       5/2
 钢靴       boot7        5       feet    heavy_metal 4/0
 金织履     boot8        4.5     feet    cloth       6/3
 风行靴     boot9        4.5     feet    cloth       6/2      dodge 3
*云霞绛红袍 cloak1       9       cloak   leather     5/4      none 3  magic 4 
*点翠团花征袍 cloak2     9       cloak   cloth       6/3      
*龙虎战袍   cloak3       15      cloak   leather     3/6      magic 20
 碧竹袍     cloth1       10      body    cloth       18/6     cold 10 fire -25
                                                              piety -1 evil 15
                                                              divine -25
                                                              magic 25
 七彩凤裳   cloth2       7       body    cloth       24/5 
 麒麟衣     cloth3       6.5     body    cloth       25/6
 短武服     cloth4       10      body    cloth       20/5
 王冠       crown        4       head    light_metal 7/2      cold 10 
 原力护盾   globe        30      globe   mage        40/15    evil -10 divine 30
                                                              none 10  magic -40
                                                              electric 30 int -1
 (此装备在於眼魔可穿法过少且不强, 眼魔数量亦不多之故)       energy 20 mental -20

 雷动手套   gloves       4       hands   cloth       5/3      parry 3
 逍遥帽     hat          4       head    cloth       6/3      hide 3
 云鹤冠     helmet1      15      head    light_metal 6/3      
*朱红点金束发盔 helmet2  8       head    light_metal 6/2      none 5 magic 2
*浑铁四方帽 helmet3      7       head    light_metal 6/2      none 5
*皂纱簇花巾 helmet4      5       head    cloth       5/2      fire 3 acid 5
                                                              mental 2
*九云凤翅盔 helmet5      8       head    light_metal 6/1      magic 20
*乾红凹面巾 helmet6      3       head    cloth       3/3 
 铁头盔     helmet7      8       head    heavy_metal 4/1   
 束发金簪   helmet8      3       head    light_metal 6/1
 钢头盔     helmet9      8       head    heavy_metal 5/0  
 金丝绑腿   leggings1    6       legs    light_metal 8/2
 邀月护胫   leggings2    5       legs    cloth       6/2
 钢锁子甲   mail1        20      body    heavy_metal 24/3     cold -5 fire 5 
                                                              none 3
 钢战甲     mail2        25      body    heavy_metal 25/3
*熊皮乌油铠 plate1       20      body    leather     28/4
*绯红团花战袍 plate2     10      body    cloth       24/6
*兽面□猊铠 plate3       20      body    leather     29/3
*紫绣团花战袍 plate4     13      body    cloth       24/5
*柳叶贯金甲 plate5       37      body    light_metal 33/3     none 18
 乾坤戒     ring1        1.5     finger  stone       0/4      magic 30 fire 20
                                                              cold -30
                                                              evil 20 divine -30
 皇者之戒   ring2        2       finger  elemental   0/5      none 30
 龙袍       robe1        7       body    cloth       26/6     cold 10 evil 10
 白菊武袍   robe2        8.5     body    cloth       25/5     cold 10 evil 20 
                                                              divine -20
 旅者之袍   robe3        9       body    cloth       23/4
 草鞋       sandal       4       feet    wood        3/1 
 龙甲挡     shield       10      shield  light_metal 6/0      none 15 block 10
 捕快制服   uniform      8       body    cloth       20/3

 VII.其他物品：

       物品名称        档名         用途
 
       竹叶青          ching        酒店卖的酒(heal hp2)
       高粱酒          gou            ..      (heal hp3)
       茅台酒          mao            ..      (+tp 10)
       女儿红          red            ..
       烤山鸡          roast        酒店卖的食物(heal hp10+random(3) )
       青竹丝泡酒      special        ..      (heal hp8+random(5) )

 VIII 房间数：

       市区: 20
       宫殿区: 22
