#define TULU_DIR "/domains/estergrym/areas/tulu/"
#define TULU_ROOM TULU_DIR "room/"
#define TULU_NPC  TULU_DIR "npc/"
#define TULU_OBJ  TULU_DIR "obj/"
#define TULU_VIRTUAL "/domains/estergrym/virtual/tulu/"
