 //topkan@xhc

mapping allloca=([
        "扬州城":({"/d/city/","beidajie1","beidajie2","beimen","biaoju",
               "bingqiku","bingyin","bingyindamen","caizhu",
               "chaguan","dangpu","datiepu","dayuan","dongdajie1","dongdajie2",
               "dongmen","dongting","dongxiang","duchang","duchang2",
               "gbandao","gbxiaowu","guangchang","houyuan",
               "lichunyuan",
               "ml1","ml2","ml3","ml4","ml5","ml6","ml7",
               "nandajie1","nandajie2","nanmen","neizhai",
               "pomiao","qianzhuang","shuyuan",
               "xidajie1","xidajie2",
               "ximen","xiting","xixiang",
               "yamen","yaopu","ymzhengting","zahuopu","zhengting",
               "zuixianlou","zuixianlou2",
             }),

    "北京城":({"/d/city2/","alley1","alley2","alley3",
               "anding","aobai1","aobai10","aobai11","aobai12","aobai2",
               "aobai3","aobai6","aobai7","bingqiku","bingyin1","bingyin2","bridge",
               "bridge2","bridge3","ceting",
               "chaguan","chaoyan1","chaoyan2","chaoyang","dangpu","datiepu","dating",
               "daxiao","daxiao2","di_an1","di_an2","di_an3","di_an4","di_anmen",
               "dongcha1","dongcha2","dongchangdamen","dongmen","duchang","duchang2",
               "eproom","fotang","guancai1","guancai2","haigang",
               "hbridge","houtai","huayuan","huichunt","jiulou1","jiulou2","kang1",
               "kang2","kang3",
               "mapeng","mianguan","nandaj1","nandaj2","neishi",
               "neitang","nproom","qianzhua","shufang",
               "shuyuan","sproom","stage","tian_anm","tingyu","wangfu1",
               "wangfu2","wangfu3","wproom","wuchang","wuqiku","xiaotan",
               "xichang1","xichang2","xichangdamen","xidan","xidan1","ximen","ximenwai",
               "xisi","xisi2","xiyuan","yihongyu","yongding","zahuopu","zhengmen",
               "zhulin1","zhulin2","zhulin3","zhulin4","zhulin5",
                }),
    "白驼山":({"/d/baituo/","bridge","cao1","cao2","caomeide","caoping","cave","cave1","cedong",
               "chaifang","changlang","chufang","damen","datiepu","dating","dongjie",
               "dongkou","dongnei","fang","fende","gebi","guangchang","houmen","houyuan",
               "huayuan","jiudian","liangong","menlang","midao","mumen","neishi","nongshe",
               "restroom","room1","room2","room3","shanlu","shanlu1","shijie","shulin",
               "shulin1","storeroom","tuyuan","wuqiku","xiaolu1","xiaolu2","xiaolu3",
               "xiaolu4","xijie","ximen","yaofang","yuanzi","zhailuo","zhulin","zhuyuan",
                }),

    "北京城外":({"/d/city2/","road10","road9","road8","road7","road6","road5",
               "road4","road3","road2","road1","zhuang1","zhuang2","zhuang3","zhuang4",
               "haigang",
             }),
    "泉洲" :({"/d/quanzhou/","beimen","haigang","houyuan","jiaxing",
              "jxnanmen","laozhai","liang","midao","mishi","nanhu","nanhu1","nanmen",
              "qzroad1","qzroad2","qzroad3","qzroad4","qzroad5","tieqiang","well",
              "xijie","yanyu","zahuopu","zhongxin",
             }),
                  
     "华山村":({"/d/village/","alley1","alley2","bighouse1","bighouse2","eexit","ehouse1","ehouse2",
           "eroad1","eroad2","eroad3","hsroad1","hsroad2","hsroad3","nwhouse","nwroad1",
           "nwroad2","sexit.lpc","shack","shop","shouse","smithy1","smithy2","square","sroad1",
           "sroad2","sroad3","sroad4","temple1","temple2","wexit",}),
           
     
     "泰山":({"/d/taishan/","baihe","baozang","beitian","bixia","daizong",
         "dongtian","doumo","ertian","fengchan","huima","lianhua",
         "longmen","nantian","riguan","shengxian","shijin","shixin",
         "tanhai","tianjie","weipin","wudafu",
         "xiayi","xitian","yidao","yidao1","yidao2","yidao3",
         "yitian","yueguan","yuhuang","zhangren","zhengqi",}),
  
     ]);

