mapping guainame=([

"魔":(["柳孝岚":({"liu xiaolan","liu"}),"沈子泰":({"shen zitai","shen"}),
        "茅世钢":({"mao shigang","mao"}),"言长超":({"yan changchao","yan"}),
        "风二":({"feng er","feng"}),"赵大江":({"zhao dajiang","zhao"}),
        "周福敏":({"zhou fumin","zhou"}),"尹荣":({"yin rong","yin"}),
        "袁昌":({"yuan chang","yuan"}),"辕轩定":({"xuanyuan ding","xuanyuan"}),
        "况诚":({"kuang cheng","kuang"}),"彭金泰":({"peng jintai","peng"}),
        "穆若海":({"mu ruohai","mu"}),"凌孝羽":({"ling xiaoyu","ling"}),
        "庞自荣":({"pang zirong","pang"}),"黄禄浩":({"huang luhao","huang"}),
        "岳高进":({"yue gaojin","yue"}),"陈世美":({"chen shimei","chen"}),
        "左丘剑":({"zuo qiujian","zuo"}),"王公济":({"wang gongji","wang"}),
        "齐锋":({"qi feng","qi"}),"孙霸":({"sun ba","sun"}),
        "东方海":({"dongfang hai","dongfang"}),"姜多杰":({"jiang duojie","jiang"}),
        "公孙二":({"gongsun er","gongsun"}),"梁良":({"liang liang","liang"}),
        "孙罡":({"sun gang","sun"}),"凌长瑜":({"ling changyu","ling"}),
"陈水扁":({"chen shuibian","chen"}),"李登辉":({"li denghui","li"}),
"蔡英文":({"cai yingwen","cai"}),"陈菊":({"chen ju","chen"}),
"小泉纯一郎":({"xiaoquan chunyilang","xiaoquan"}),"安倍晋三":({"anbei jinsan","anbei"}),
"汪精卫":({"wang jingwei","wang"}),"吴三桂":({"wu sangui","wu"}),
"秦桧":({"qin hui","qin"}),"魏忠贤":({"wei zhongxian","wei"}),
"朴槿惠":({"piao jinhui","piao"}),"阿基诺三世":({"ajinuo sanshi","ajinuo"}),
"赵高":({"zhao gao","zhao"}),"董卓":({"dong zhuo","dong"}),
"高俅":({"gao qiu","gao"}),"潘仁美":({"pan renmei","pan"}),
"西门庆":({"ximen qing","ximen"}),"蒋门神":({"jiang menshen","jiang"}),
"东条英机":({"dongtiao yingji","dongtiao"}),"石原慎太郎":({"shiyuan shentailang","shiyuan"}),
"苏贞昌":({"su zhenchang","su"}),"谢长廷":({"xie changting","xie"}),
"游锡堃":({"you xikun","you"}),"赖清德":({"lai qingde","lai"}),
"吕秀莲":({"lü xiulian","lü"}),"邱议莹":({"qiu yiying","qiu"}),
"柯建铭":({"ke jianming","ke"}),"王世坚":({"wang shijian","wang"}),
"庞吉":({"pang ji","pang"}),"潘金莲":({"pan jinlian","pan"}),
   ]),
]);
