        
mapping *renwu1=({ 
([      "type":1,       "id":"xiao bing",       "name":"小兵",             "lv":1, ]), 
([      "type":1,       "id":"xishuai",         "name":"蟋蟀",             "lv":1, ]),
([      "type":1,       "id":"rat",             "name":"大老鼠",           "lv":1, ]), 
([      "type":1,       "id":"dog",             "name":"野狗",             "lv":1, ]), 
([      "type":1,       "id":"wolf",            "name":"小狼",             "lv":1, ]), 
([      "type":1,       "id":"gong ji",         "name":"公鸡",             "lv":1, ]), 
([      "type":1,       "id":"shan ji",         "name":"山鸡",             "lv":1, ]), 
([      "type":1,       "id":"xiao pizi",       "name":"小痞子",           "lv":1, ]), 
([      "type":1,       "id":"xiao liumang",    "name":"小流氓",          "lv":1, ]), 
([      "type":1,       "id":"lao tou",         "name":"瘦老头",           "lv":1, ]), 
([      "type":1,       "id":"da shou",         "name":"打手",             "lv":1, ]), 
([      "type":1,       "id":"bandit leader",   "name":"土匪头目",         "lv":1, ]), 
([      "type":1,       "id":"ma dao",          "name":"马盗",             "lv":1, ]), 
([      "type":1,       "id":"jianghu pianzi",  "name":"江湖骗子",         "lv":1, ]), 
([      "type":1,       "id":"jinchai nv",      "name":"金钗女",           "lv":1, ]), 
([      "type":1,       "id":"jian shang",      "name":"奸商",             "lv":1, ]), 
([      "type":1,       "id":"yong yi",         "name":"庸医",             "lv":1, ]), 
([      "type":1,       "id":"shuishe guai",    "name":"水蛇怪",           "lv":1, ]), 
([      "type":1,       "id":"jinjing shou",    "name":"金睛兽",           "lv":1, ]), 
([      "type":1,       "id":"hua ren",         "name":"花忍",             "lv":1, ]), 
([      "type":1,       "id":"mi",              "name":"蜜",               "lv":1, ]), 
([      "type":1,       "id":"ma",              "name":"蚂",               "lv":1, ]), 
      ([      "type":1,       "id":"lu",              "name":"卢",               "lv":1, ]), 
      ([      "type":1,       "id":"ban",             "name":"班",               "lv":1, ]), 
      ([      "type":1,       "id":"meng",            "name":"蜢",               "lv":1, ]), 
      ([      "type":1,       "id":"la",              "name":"蜡",               "lv":1, ]), 
      ([      "type":1,       "id":"qing",            "name":"蜻",               "lv":1, ]), 
      ([      "type":1,       "id":"yan shu",         "name":"鼹鼠精",           "lv":1, ]), 
      ([      "type":1,       "id":"xia po",          "name":"长腿虾婆",         "lv":1, ]), 
      ([      "type":1,       "id":"xia po",          "name":"大肚虾婆",         "lv":1, ]), 
      ([      "type":1,       "id":"guboer xi",       "name":"古波儿西",         "lv":1, ]), 
      ([      "type":1,       "id":"xiboer gu",       "name":"西波儿古",         "lv":1, ]), 
      ([      "type":1,       "id":"liushu jing",      "name":"柳树精",           "lv":1, ]), 
      ([      "type":1,       "id":"yao guai",        "name":"鹿头怪",           "lv":1, ]), 
      ([      "type":1,       "id":"yao guai",        "name":"马头怪",           "lv":1, ]), 
      ([      "type":1,       "id":"yao guai",        "name":"羊头怪",           "lv":1, ]), 
      ([      "type":1,       "id":"yao guai",        "name":"狐头怪",           "lv":1, ]), 
      ([      "type":1,       "id":"yao guai",        "name":"兔头怪",           "lv":1, ]), 
      ([      "type":1,       "id":"xia pengzhan",    "name":"夏鹏展",           "lv":1, ]), 
      ([      "type":1,       "id":"baboer ben",      "name":"灞波儿奔",         "lv":1, ]), 
      ([      "type":1,       "id":"benboer ba",      "name":"奔波儿灞",         "lv":1, ]), 
      ([      "type":1,       "id":"lingxu zi",       "name":"凌虚子",           "lv":1, ]), 
    



 
      ([      "type":2,       "id":"cloth",   "name":"粗布衣",                "lv":1,]), 
       
      (["type":3,     "id":"/d/city/kezhan",          "name":"南城客栈",      "lv":2,]), 
      }); 
      
mapping *renwu2=({ 
      ([      "type":1,       "id":"xiao tong",      "name":"小童",            "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"虎将",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"熊师",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"豹头",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"彪帅",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"羊头怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"獭象怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"鹿头怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"苍狼怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"乖獐怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"狡兔怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"长蛇怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"狒狒怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"蟒蛇怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"山猫怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"苍狼怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"野猪怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"棕熊怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"花虎怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"黑蟒怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"巨猿怪",           "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"骡怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"犊怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"獾怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"狐怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"猪怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"熊怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"猴怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"蟒怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"虎怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"兔怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"狼怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"马怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"羊怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"鹿怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"豹怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"彪怪",             "lv":2, ]), 
      ([      "type":1,       "id":"yao guai",       "name":"虎怪",             "lv":2, ]), 
       
      ([      "type":2,       "id":"yan",             "name":"盐",            "lv":2,]), 
       
      (["type":3,     "id":"/d/qujing/tianzhu/jiang",         "name":"酱房",  "lv":2,]), 
      }); 
       
mapping *renwu3=({ 
      ([      "type":1,       "id":"yao jing",              "name":"鲞精",             "lv":3, ]),
      ([      "type":1,       "id":"yao jing",              "name":"鲤鱼精",           "lv":3, ]), 
      ([      "type":1,       "id":"yao jing",              "name":"鲫鱼精",           "lv":3, ]),  
       ([      "type":1,       "id":"yao jing",             "name":"水螺精",           "lv":3, ]),
       ([      "type":1,       "id":"yao jing",             "name":"鲇鱼精",           "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"蚌壳精",           "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"水鲑精",           "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"河鳗精",           "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"鳖精",             "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"鳌精",             "lv":3, ]),        
       ([      "type":1,       "id":"shark",                "name":"花皮鲨",           "lv":3, ]),        
       ([      "type":1,       "id":"shark",                "name":"绿背鲨",           "lv":3, ]),        
       ([      "type":1,       "id":"shark",                "name":"双头鲨",           "lv":3, ]),        
       ([      "type":1,       "id":"shark",                "name":"虎齿鲨",           "lv":3, ]),                
       ([      "type":1,       "id":"cloud fog",            "name":"云里雾",           "lv":3, ]),        
       ([      "type":1,       "id":"fog cloud",            "name":"雾里云",           "lv":3, ]),        
       ([      "type":1,       "id":"guard",                "name":"赤身鬼使",         "lv":3, ]),        
       ([      "type":1,       "id":"laohu jing",           "name":"老虎精",           "lv":3, ]),        
       ([      "type":1,       "id":"tianboer xiao",        "name":"天波儿笑",         "lv":3, ]),        
       ([      "type":1,       "id":"xiaoboer tian",        "name":"笑波儿天",         "lv":3, ]),        
       ([      "type":1,       "id":"wansheng gongzhu",     "name":"万圣公主",         "lv":3, ]),        
       ([      "type":1,       "id":"mei hou",              "name":"美后",             "lv":3, ]),        
       ([      "type":1,       "id":"mahuang guai",         "name":"蚂蟥怪",           "lv":3, ]),        
       ([      "type":1,       "id":"bajiao guai",          "name":"芭蕉怪",           "lv":3, ]),        
       ([      "type":1,       "id":"yumian gongzhu",       "name":"玉面公主",         "lv":3, ]),        
       ([      "type":1,       "id":"niuer",                "name":"牛二先生",         "lv":3, ]),        
       ([      "type":1,       "id":"nu zi",                "name":"女子",             "lv":3, ]),        
       ([      "type":1,       "id":"fu ren",               "name":"老妇人",           "lv":3, ]),        
       ([      "type":1,       "id":"gong gong",            "name":"老公公",           "lv":3, ]),        
       ([      "type":1,       "id":"xiezi jing",           "name":"蝎子精",           "lv":3, ]),        
       ([      "type":1,       "id":"yao jing",             "name":"妖精",             "lv":3, ]),        
       ([      "type":1,       "id":"yao wang",             "name":"妖王",             "lv":3, ]),        
       ([      "type":1,       "id":"shuizhi jing",         "name":"水蛭精",           "lv":3, ]),        
       ([      "type":1,       "id":"jingxi gui",           "name":"精细鬼",           "lv":3, ]),       
       ([      "type":1,       "id":"bashan hu",            "name":"巴山虎",           "lv":3, ]),       
       ([      "type":1,       "id":"yihai long",           "name":"倚海龙",           "lv":3, ]),       
       ([      "type":1,       "id":"wansheng longwang",    "name":"万圣龙王",         "lv":3, ]),       
       ([      "type":1,       "id":"yu xiang",             "name":"玉香",             "lv":3, ]),       
       ([      "type":1,       "id":"hua yu",               "name":"花语",             "lv":3, ]),       
       ([      "type":1,       "id":"liu mei",              "name":"柳眉",             "lv":3, ]),       
       ([      "type":1,       "id":"tan  kou",             "name":"檀口",             "lv":3, ]),       
       ([      "type":1,       "id":"chai tou",             "name":"钗头",             "lv":3, ]),       
       ([      "type":1,       "id":"jin lian",             "name":"金莲",             "lv":3, ]),       
       ([      "type":1,       "id":"jiang qun",            "name":"绛裙",             "lv":3, ]),       




([      "type":2,       "id":"golden ring",             "name":"金戒指",                "lv":2,]), 
       
(["type":3,     "id":"/d/nanhai/gate",          "name":"南海普陀山",    "lv":1,]), 
}); 
       
mapping *renwu4=({ 
([      "type":1,       "id":"jiutou fuma",    "name":"九头驸马",              "lv":4, ]), 
([      "type":1,       "id":"golden dragon",  "name":"五爪金龙",              "lv":4, ]), 
([      "type":1,       "id":"guo zhang",      "name":"国丈",                  "lv":4, ]), 
([      "type":1,       "id":"lao nainai",     "name":"老奶奶",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"猱狮",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"抟狮",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"雪狮",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"云豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"水豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"花豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"石豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"草豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"山豹",                  "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"狻猊狮",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"白泽狮",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"伏狸狮",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"白毛虎",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"青面虎",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"花斑虎",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"大王虎",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"八脚虎",                "lv":4, ]), 
([      "type":1,       "id":"yao guai",       "name":"双尾虎",                "lv":4, ]),
([      "type":1,       "id":"huaqi dawang",   "name":"狐阿七大王",            "lv":4, ]),
      
([      "type":2,       "id":"huanyang dan","name":HIG"还阳丹"NOR,      "lv":2,]),
      
(["type":3,     "id":"/d/nanhai/chaoyindong",   "name":"潮音洞",                "lv":3,]),
      
      });
      

