#include <ansi.h>

mapping *quest = ({
      (["name":               "月宫叛徒",
     "where" :                "/u/fly/job/guanfu/npc/npc_moon",]), 
      (["name":               "无底洞叛徒",
     "where" :                "/u/fly/job/guanfu/npc/npc_wudidong",]),
       (["name":              "雪山叛徒",
     "where" :                "/u/fly/job/guanfu/npc/npc_xueshan",]),
      (["name":               "方寸叛徒",
     "where" :                "/u/fly/job/guanfu/npc/npc_fangcun",]),
     (["name":                "古墓叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_gumu",]),   
      (["name":               "龙宫叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_dragon",]),    
      (["name":               "地府叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_hell",]),  
      (["name":               "水帘洞叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_sld",]), 
      (["name":               "普驼山叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_putuo",]), 
      (["name":               "五庄观叛徒",
     "where" :                 "/u/fly/job/guanfu/npc/npc_wzg",]), 
   });
mapping *wheres=({         
      (["chinese":                "开封城西",
       "weizhi" :              "/d/kaifeng/xihu1",]),  
      (["chinese":                "开封城西",
       "weizhi" :              "/d/kaifeng/xihu4",]),         
      (["chinese":                "开封城东",
       "weizhi" :              "d/kaifeng/donghu1",]),   
      (["chinese":                "开封城东",
       "weizhi" :              "d/kaifeng/donghu4",]),   
      (["chinese":                "长安城东",
       "weizhi" :              "/d/kaifeng/east1",]),   
      (["chinese":                "长安城东",
       "weizhi" :              "/d/kaifeng/east3",]),   
      (["chinese":                "长安城西",
       "weizhi" :              "/d/westway/jincheng",]),   
      (["chinese":                "长安城西",
       "weizhi" :              "/d/westway/yongjing",]),   
      (["chinese":                "长安城西",
       "weizhi" :              "/d/westway/shizhan",]),   
      (["chinese":                "长安城南",
       "weizhi" :              "/d/changan/zhongnan",]),   
      (["chinese":                "长安城南",
       "weizhi" :              "/d/changan/wside2",]),   
      (["chinese":                "长安城南",
       "weizhi" :              "/d/changan/broadway4",]),   
      (["chinese":                "长安城南",
       "weizhi" :              "/d/changan/southseashore",]),   
      (["chinese":                "长安城南",
       "weizhi" :              "/d/changan/nanyue",]),   
      (["chinese":                "灌江",
       "weizhi" :              "/d/meishan/erlangwai",]),   
      (["chinese":                "灌江",
       "weizhi" :              "/d/meishan/denglong1",]),  
       (["chinese":                "灌江",
       "weizhi" :              "/d/meishan/guanjiang2",]),   
      (["chinese":                "灌江",
       "weizhi" :              "/d/meishan/maowu",]), 
       (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/road1",]),   
      (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/huayuan",]), 
       (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/pianting",]),   
      (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/cunkou",]), 
       (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/budian",]),   
      (["chinese":                "高家庄",
       "weizhi" :              "/d/gao/shanlu",]), 
       (["chinese":                "大雪山",
       "weizhi" :              "/d/xueshan/wroad1",]),   
      (["chinese":                "大雪山",
       "weizhi" :              "/d/xueshan/wuchang-s",]), 
       (["chinese":                "大雪山",
       "weizhi" :              "/d/xueshan/restroom",]),   
      (["chinese":                "大雪山",
       "weizhi" :              "/d/xueshan/icegate",]), 
       (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/nroom",]),   
      (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/xiaoyao",]), 
       (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/yunu3",]),   
      (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/road1",]), 
       (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/junkroom",]),   
      (["chinese":                "玉女峰",
       "weizhi" :              "/d/moon/wangmu_room",]), 
       (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/jjf_bingqi",]),   
      (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/guest_cabinet",]), 
       (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/se_garden",]),   
      (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/main_shufang",]), 
       (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/son_shufang",]),   
      (["chinese":                "将军府",
       "weizhi" :              "/d/jjf/kitchen_road2",]),  
      (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/jinting",]),   
      (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/jie6",]), 
       (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/daochang",]),   
      (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/xibei",]), 
       (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/yang5",]),   
      (["chinese":                "比丘国",
       "weizhi" :              "/d/qujing/biqiu/yu",]), 
       (["chinese":                "乌鸡",
       "weizhi" :              "/d/qujing/wuji/stable",]),   
      (["chinese":                "乌鸡",
       "weizhi" :              "/d/qujing/wuji/qiyutan",]), 
       (["chinese":                "乌鸡",
       "weizhi" :              "/d/qujing/wuji/ziyun",]),   
      (["chinese":                "乌鸡",
       "weizhi" :              "/d/qujing/wuji/shuijing",]), 
       (["chinese":                "乌鸡",
       "weizhi" :              "/d/qujing/wuji/backyard",]),   
      (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/yanhua",]), 
       (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/xiao",]),   
      (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/hougong3",]), 
       (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/gong1c",]),   
      (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/houdian",]), 
       (["chinese":                "车迟",
       "weizhi" :              "/d/qujing/chechi/damo",]),   
      (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/easthall",]),  
      (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/townb2",]),   
      (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/westriver",]), 
       (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/xiaolu2",]),   
      (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/juxianan",]), 
       (["chinese":                "女儿国",
       "weizhi" :              "/d/qujing/nuerguo/eastriver2",]),   
      (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/qingong1",]), 
       (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/jiupu",]),   
      (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/pihuopu",]), 
       (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/zhongshi",]),   
      (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/tianjing",]), 
       (["chinese":                "钦法国",
       "weizhi" :              "/d/qujing/qinfa/bupu",]),   
      (["chinese":                "祭赛国",
       "weizhi" :              "/d/qujing/jisaiguo/restaurant",]), 
       (["chinese":                "祭赛国",
       "weizhi" :              "/d/qujing/jisaiguo/zai",]),   
      (["chinese":                "祭赛国",
       "weizhi" :              "/d/qujing/jisaiguo/tower5",]), 
       (["chinese":                "流沙河",
       "weizhi" :              "/d/qujing/liusha/hedi6",]),   
      (["chinese":                "流沙河",
       "weizhi" :              "/d/qujing/liusha/riverside",]), 
       (["chinese":                "流沙河",
       "weizhi" :              "/d/qujing/liusha/dadao1",]),   
      (["chinese":                "云栈洞",
       "weizhi" :              "/d/qujing/yunzhan/shulin7",]),  
      (["chinese":                "云栈洞",
       "weizhi" :              "/d/qujing/yunzhan/shulin10",]),   
      (["chinese":                "云栈洞",
       "weizhi" :              "/d/qujing/yunzhan/shulin2",]), 
       (["chinese":                "云栈洞",
       "weizhi" :              "/d/qujing/yunzhan/bed",]),   
      (["chinese":                "凤仙郡",
       "weizhi" :              "/d/qujing/fengxian/jiedao2",]), 
       (["chinese":                "凤仙郡",
       "weizhi" :              "/d/qujing/fengxian/jiuguan",]),   
      (["chinese":                "凤仙郡",
       "weizhi" :              "/d/qujing/fengxian/zhaishi",]), 
       (["chinese":                "宝象国",
       "weizhi" :              "/d/qujing/baoxiang/zuofang",]),   
      (["chinese":                "朱紫国",
       "weizhi" :              "/d/qujing/zhuzi/jiekou",]), 
       (["chinese":                "朱紫国",
       "weizhi" :              "/d/qujing/zhuzi/xi1",]),   
      (["chinese":                "朱紫国",
       "weizhi" :              "/d/qujing/zhuzi/housan",]), 
       (["chinese":                "南海普陀山",
       "weizhi" :              "/d/nanhai/island",]),   
      (["chinese":                "南海普陀山",
       "weizhi" :              "/d/nanhai/road2",]), 
       (["chinese":                "天竺国",
       "weizhi" :              "/d/qujing/tianzhu/budian",]),   
      (["chinese":                "天竺国",
       "weizhi" :              "/d/qujing/tianzhu/yaofang",]), 
       (["chinese":                "天竺国",
       "weizhi" :              "/d/qujing/tianzhu/jiedao85",]),   
      (["chinese":                "小西天",
       "weizhi" :              "/d/qujing/xiaoxitian/houdian",]), 
       (["chinese":                "小西天",
       "weizhi" :              "/d/qujing/xiaoxitian/chanfang",]),   
      (["chinese":                "黑风山",
       "weizhi" :              "/d/qujing/heifeng/shandao3",]),  
      (["chinese":                "观音禅院",
       "weizhi" :              "/d/qujing/heifeng/dadian",]), 
       (["chinese":                "通天河",
       "weizhi" :              "/d/qujing/tongtian/hexi3",]),   
      (["chinese":                "通天河",
       "weizhi" :              "/d/qujing/tongtian/chen1",]), 
       (["chinese":                "金平府",
       "weizhi" :              "/d/qujing/jinping/xiaojie3",]),   
      (["chinese":                "金平府",
       "weizhi" :              "/d/qujing/jinping/datang",]), 
      (["chinese":                "灵台方寸山",
       "weizhi" :              "/d/lingtai/guanjin",]),  
      (["chinese":                "灵台方寸山",
       "weizhi" :              "/d/lingtai/cave2",]),   
      (["chinese":                "灵台方寸山",
       "weizhi" :              "/d/lingtai/lantao2",]), 
       (["chinese":                "灵台方寸山",
       "weizhi" :              "/d/lingtai/houyuan",]),   
      });

