inherit "room/room";

#define EXTRA_RESET

// This driver's call_create() always marks a freshly-loaded object as
// "already reset" and defers its real first reset() for up to "time to
// reset" seconds (room/church.lpc's own create() has the full writeup,
// AGENTS.md); this whole archive uses reset(arg){if(!arg)...} as its
// constructor for exits/light/etc, so every room needs an explicit
// `create() { reset(0); }` to be usable immediately on load rather than
// dark and exit-less for up to 30 minutes. That fix was applied by hand
// to standalone rooms but never to the ~70 rooms generated by these
// four macros -- added here once so every ONE_EXIT/TWO_EXIT/THREE_EXIT/
// FOUR_EXIT room gets it automatically instead of needing a per-file
// edit (confirmed live: room/vill_track, a TWO_EXIT room one hop from
// the starting area, was completely dark with NO exits registered at
// all -- "What?" for every direction -- until this fix).

#define ONE_EXIT(DEST, DIR, SH, LO, LIGHT)\
reset(arg) { if (!arg) { set_light(LIGHT); short_desc = SH;\
    long_desc = LO; dest_dir = ({ DEST, DIR }); } EXTRA_RESET }\
create() { reset(0); }

#define TWO_EXIT(DEST1, DIR1, DEST2, DIR2, SH, LO, LIGHT)\
reset(arg) { if (!arg) { set_light(LIGHT);\
    short_desc = SH; long_desc = LO;\
    dest_dir = ({ DEST1, DIR1, DEST2, DIR2 }); } EXTRA_RESET }\
create() { reset(0); }


#define THREE_EXIT(DEST1, DIR1, DEST2, DIR2, DEST3, DIR3, SH, LO, LIGHT)\
reset(arg) { if (!arg) { set_light(LIGHT);\
    short_desc = SH; long_desc = LO;\
    dest_dir = ({ DEST1, DIR1, DEST2, DIR2, DEST3, DIR3 }); } EXTRA_RESET }\
create() { reset(0); }


#define FOUR_EXIT(DEST1, DIR1, DEST2, DIR2, DEST3, DIR3, DEST4, DIR4, SH, LO, LIGHT)\
reset(arg) { if (!arg) { set_light(LIGHT);\
    short_desc = SH; long_desc = LO;\
    dest_dir = ({ DEST1, DIR1, DEST2, DIR2, DEST3, DIR3, DEST4, DIR4 }); }\
    EXTRA_RESET }\
create() { reset(0); }
