#define MY_OB(x)   PARASE_D->my_ob(x)
#define ENV_OB(x)   PARASE_D->env_ob(x)
#define MYENV_OB(x)  PARASE_D->myenv_ob(x)
#define ENVMY_OB(x)  PARASE_D->envmy_ob(x)
#define ENV_LIV(x)   PARASE_D->env_liv(x)
