mapping *dizhia=({         
      (["cdizhi":                "开封城西",
       "weizhi2" :              "/d/kaifeng/xihu1",]),  
      (["cdizhi":                "开封城西",
       "weizhi2" :              "/d/kaifeng/xihu4",]),         
      (["cdizhi":                "开封城东",
       "weizhi2" :              "d/kaifeng/donghu1",]),   
      (["cdizhi":                "开封城东",
       "weizhi2" :              "d/kaifeng/donghu4",]),   
      (["cdizhi":                "长安城东",
       "weizhi2" :              "/d/kaifeng/east1",]),   
      (["cdizhi":                "长安城东",
       "weizhi2" :              "/d/kaifeng/east3",]),   
      (["cdizhi":                "长安城西",
       "weizhi2" :              "/d/westway/jincheng",]),   
      (["cdizhi":                "长安城西",
       "weizhi2" :              "/d/westway/yongjing",]),   
      (["cdizhi":                "长安城西",
       "weizhi2" :              "/d/westway/shizhan",]),   
      (["cdizhi":                "长安城南",
       "weizhi2" :              "/d/changan/zhongnan",]),   
      (["cdizhi":                "长安城南",
       "weizhi2" :              "/d/changan/wside2",]),   
      (["cdizhi":                "长安城南",
       "weizhi2" :              "/d/changan/broadway4",]),   
      (["cdizhi":                "长安城南",
       "weizhi2" :              "/d/changan/southseashore",]),   
      (["cdizhi":                "长安城南",
       "weizhi2" :              "/d/changan/nanyue",]),   
      (["cdizhi":                "灌江",
       "weizhi2" :              "/d/meishan/erlangwai",]),   
      (["cdizhi":                "灌江",
       "weizhi2" :              "/d/meishan/denglong1",]),  
       (["cdizhi":                "灌江",
       "weizhi2" :              "/d/meishan/guanjiang2",]),   
      (["cdizhi":                "灌江",
       "weizhi2" :              "/d/meishan/maowu",]), 
       (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/road1",]),   
      (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/huayuan",]), 
       (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/pianting",]),   
      (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/cunkou",]), 
       (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/budian",]),   
      (["cdizhi":                "高家庄",
       "weizhi2" :              "/d/gao/shanlu",]), 
       (["cdizhi":                "大雪山",
       "weizhi2" :              "/d/xueshan/wroad1",]),   
      (["cdizhi":                "大雪山",
       "weizhi2" :              "/d/xueshan/wuchang-s",]), 
       (["cdizhi":                "大雪山",
       "weizhi2" :              "/d/xueshan/restroom",]),   
      (["cdizhi":                "大雪山",
       "weizhi2" :              "/d/xueshan/icegate",]), 
       (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/nroom",]),   
      (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/xiaoyao",]), 
       (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/yunu3",]),   
      (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/road1",]), 
       (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/junkroom",]),   
      (["cdizhi":                "玉女峰",
       "weizhi2" :              "/d/moon/wangmu_room",]), 
       (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/jjf_bingqi",]),   
      (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/guest_cabinet",]), 
       (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/se_garden",]),   
      (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/main_shufang",]), 
       (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/son_shufang",]),   
      (["cdizhi":                "将军府",
       "weizhi2" :              "/d/jjf/kitchen_road2",]),  
      (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/jinting",]),   
      (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/jie6",]), 
       (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/daochang",]),   
      (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/xibei",]), 
       (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/yang5",]),   
      (["cdizhi":                "比丘国",
       "weizhi2" :              "/d/qujing/biqiu/yu",]), 
       (["cdizhi":                "乌鸡",
       "weizhi2" :              "/d/qujing/wuji/stable",]),   
      (["cdizhi":                "乌鸡",
       "weizhi2" :              "/d/qujing/wuji/qiyutan",]), 
       (["cdizhi":                "乌鸡",
       "weizhi2" :              "/d/qujing/wuji/ziyun",]),   
      (["cdizhi":                "乌鸡",
       "weizhi2" :              "/d/qujing/wuji/shuijing",]), 
       (["cdizhi":                "乌鸡",
       "weizhi2" :              "/d/qujing/wuji/backyard",]),   
      (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/yanhua",]), 
       (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/xiao",]),   
      (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/hougong3",]), 
       (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/gong1c",]),   
      (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/houdian",]), 
       (["cdizhi":                "车迟",
       "weizhi2" :              "/d/qujing/chechi/damo",]),   
      (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/easthall",]),  
      (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/townb2",]),   
      (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/westriver",]), 
       (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/xiaolu2",]),   
      (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/juxianan",]), 
       (["cdizhi":                "女儿国",
       "weizhi2" :              "/d/qujing/nuerguo/eastriver2",]),   
      (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/qingong1",]), 
       (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/jiupu",]),   
      (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/pihuopu",]), 
       (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/zhongshi",]),   
      (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/tianjing",]), 
       (["cdizhi":                "钦法国",
       "weizhi2" :              "/d/qujing/qinfa/bupu",]),   
      (["cdizhi":                "祭赛国",
       "weizhi2" :              "/d/qujing/jisaiguo/restaurant",]), 
       (["cdizhi":                "祭赛国",
       "weizhi2" :              "/d/qujing/jisaiguo/zai",]),   
      (["cdizhi":                "祭赛国",
       "weizhi2" :              "/d/qujing/jisaiguo/tower5",]), 
       (["cdizhi":                "流沙河",
       "weizhi2" :              "/d/qujing/liusha/hedi6",]),   
      (["cdizhi":                "流沙河",
       "weizhi2" :              "/d/qujing/liusha/riverside",]), 
       (["cdizhi":                "流沙河",
       "weizhi2" :              "/d/qujing/liusha/dadao1",]),   
      (["cdizhi":                "云栈洞",
       "weizhi2" :              "/d/qujing/yunzhan/shulin7",]),  
      (["cdizhi":                "云栈洞",
       "weizhi2" :              "/d/qujing/yunzhan/shulin10",]),   
      (["cdizhi":                "云栈洞",
       "weizhi2" :              "/d/qujing/yunzhan/shulin2",]), 
       (["cdizhi":                "云栈洞",
       "weizhi2" :              "/d/qujing/yunzhan/bed",]),   
      (["cdizhi":                "凤仙郡",
       "weizhi2" :              "/d/qujing/fengxian/jiedao2",]), 
       (["cdizhi":                "凤仙郡",
       "weizhi2" :              "/d/qujing/fengxian/jiuguan",]),   
      (["cdizhi":                "凤仙郡",
       "weizhi2" :              "/d/qujing/fengxian/zhaishi",]), 
       (["cdizhi":                "宝象国",
       "weizhi2" :              "/d/qujing/baoxiang/zuofang",]),   
      (["cdizhi":                "朱紫国",
       "weizhi2" :              "/d/qujing/zhuzi/jiekou",]), 
       (["cdizhi":                "朱紫国",
       "weizhi2" :              "/d/qujing/zhuzi/xi1",]),   
      (["cdizhi":                "朱紫国",
       "weizhi2" :              "/d/qujing/zhuzi/housan",]), 
       (["cdizhi":                "南海普陀山",
       "weizhi2" :              "/d/nanhai/island",]),   
      (["cdizhi":                "南海普陀山",
       "weizhi2" :              "/d/nanhai/road2",]), 
       (["cdizhi":                "天竺国",
       "weizhi2" :              "/d/qujing/tianzhu/budian",]),   
      (["cdizhi":                "天竺国",
       "weizhi2" :              "/d/qujing/tianzhu/yaofang",]), 
       (["cdizhi":                "天竺国",
       "weizhi2" :              "/d/qujing/tianzhu/jiedao85",]),   
      (["cdizhi":                "小西天",
       "weizhi2" :              "/d/qujing/xiaoxitian/houdian",]), 
       (["cdizhi":                "小西天",
       "weizhi2" :              "/d/qujing/xiaoxitian/chanfang",]),   
      (["cdizhi":                "黑风山",
       "weizhi2" :              "/d/qujing/heifeng/shandao3",]),  
       (["cdizhi":                "通天河",
       "weizhi2" :              "/d/qujing/tongtian/hexi3",]),   
      (["cdizhi":                "通天河",
       "weizhi2" :              "/d/qujing/tongtian/chen1",]), 
       (["cdizhi":                "金平府",
       "weizhi2" :              "/d/qujing/jinping/xiaojie3",]),   
      (["cdizhi":                "金平府",
       "weizhi2" :              "/d/qujing/jinping/datang",]), 
      (["cdizhi":                "灵台方寸山",
       "weizhi2" :              "/d/lingtai/guanjin",]),  
      (["cdizhi":                "灵台方寸山",
       "weizhi2" :              "/d/lingtai/cave2",]),   
      (["cdizhi":                "灵台方寸山",
       "weizhi2" :              "/d/lingtai/lantao2",]), 
       (["cdizhi":                "灵台方寸山",
       "weizhi2" :              "/d/lingtai/houyuan",]),   
});

