#include <ansi.h>
mapping *wheres=({
          
      (["chinese":                "大理蛇骨塔",
       "weizhi" :              "/d/dali/mazumiao",]),  
      (["chinese":                "扬州虹桥",
       "weizhi" :              "/d/city/hongqiao",]),  
     (["chinese":                "峨嵋金顶",
       "weizhi" :              "/d/emei/jinding",]),
     (["chinese":                "扬州西门",
       "weizhi" :              "/d/city/ximen",]),
     (["chinese":                "雪山圣湖",
       "weizhi" :              "/d/xueshan/shenghu",]),
     (["chinese":                "杭州花港观鱼",
       "weizhi" :              "/d/hangzhou/huagang",]),
     (["chinese":                "杭州虎跑泉",
       "weizhi" :              "/d/hangzhou/hupaoquan",]),
     (["chinese":                "杭州飞来峰",
       "weizhi" :              "/d/hangzhou/feilaifeng",]),
     (["chinese":                "杭州净慈寺",
       "weizhi" :              "/d/hangzhou/jingcisi",]),
     (["chinese":                "杭州翠微亭",
       "weizhi" :              "/d/hangzhou/cuiweiting",]),
     (["chinese":                "杭州聚景园",
       "weizhi" :              "/d/hangzhou/jujingyuan",]),
     (["chinese":                "万劫谷善人渡",
       "weizhi" :              "/d/wanjiegu/port",]),  
      (["chinese":                "扬州中央广场",
       "weizhi" :              "/d/city/guangchang",]),  
      (["chinese":                "杭州郭庄",
       "weizhi" :              "/d/hangzhou/guozhuang",]), 
      (["chinese":                "杭州断桥",
       "weizhi" :              "/d/hangzhou/duanqiao",]), 
      (["chinese":                "杭州灵隐寺",
       "weizhi" :              "/d/hangzhou/lingyinsi",]), 
      (["chinese":                "星宿海北疆小镇",
       "weizhi" :              "/d/xingxiu/beijiang",]), 
      (["chinese":                "武当太子坡",
       "weizhi" :              "/d/wudang/xuanwumen",]), 
      (["chinese":                "峨嵋洗象池",
       "weizhi" :              "/d/emei/xixiangchi",]), 
      (["chinese":                "峨嵋千佛庵",
       "weizhi" :              "/d/emei/qianfoan",]), 
      (["chinese":                "峨嵋莲花石",
       "weizhi" :              "/d/emei/lianhuashi",]), 
      (["chinese":                "明教厚土旗",
       "weizhi" :              "/d/mingjiao/houtuqi",]), 
      (["chinese":                "明教烈火旗",
       "weizhi" :              "/d/mingjiao/liehuoqi",]), 
      (["chinese":                "泉州铁枪庙",
       "weizhi" :              "/d/quanzhou/tieqiang",]), 
      (["chinese":                "牛家村村口",
       "weizhi" :              "/d/nio/njeast",]), 
      (["chinese":                "华山村小港",
       "weizhi" :              "/d/village/alley1",]),
      (["chinese":                "襄阳将军府大院",
       "weizhi" :              "/d/xiangyang/jiangjunyuan",]),
      (["chinese":                "华山朝阳峰",
       "weizhi" :              "/d/huashan/chaoyang",]),
      (["chinese":                "华山玉女峰",
       "weizhi" :              "/d/huashan/yunu",]),
      (["chinese":                "恒山会仙台",
       "weizhi" :              "/d/hengshan/huixiantai",]),
      (["chinese":                "衡山赤帝峰",
       "weizhi" :              "/d/henshan/chidifeng",]),
      (["chinese":                "大理御花园",
       "weizhi" :              "/d/dali/huanggong9",]),
      (["chinese":                "瘦西湖四桥烟雨",
       "weizhi" :              "/d/shouxihu/siqiaoyanyu",]),
      (["chinese":                "瘦西湖观芍亭",
       "weizhi" :              "/d/shouxihu/guanshaoting",]),
      (["chinese":                "瘦西湖湖上草堂",
       "weizhi" :              "/d/shouxihu/caotang",]),
      (["chinese":                "嵩山嵩阳书院",
       "weizhi" :              "/d/songshan/shuyuan",]),
      (["chinese":                "泰山月观峰",
       "weizhi" :              "/d/taishan/yueguan",]),
      (["chinese":                "蜀山破庙",
       "weizhi" :              "/d/shushan/pomiao",]),
      (["chinese":                "高丽玉龙门",
       "weizhi" :              "/d/gaoli/xuanwumen",]),
      (["chinese":                "全真教舍身台",
       "weizhi" :              "/d/quanzhen/sheshentai",]),
       (["chinese":                "神龙岛草坪",
       "weizhi" :              "/d/shenlong/caoping",]),
       (["chinese":                "长白山天池",
       "weizhi" :              "/d/changbaishan/tianchi",]),
       (["chinese":                "开封府",
       "weizhi" :              "/d/kaifeng/kaifeng",]),
       (["chinese":                "中州破庙",
       "weizhi" :              "/d/zhongzhou/guandimiao",]),
       (["chinese":                "成都凉亭",
       "weizhi" :              "/d/city3/liangting",]),
       (["chinese":                "青城山天师洞",
       "weizhi" :              "/d/qingcheng/tianshidong",]),
       (["chinese":                "飞天门中仙道",
       "weizhi" :              "/d/feitian/zhongxiandao",]),
       (["chinese":                "凌霄城温泉",
       "weizhi" :              "/d/lingxiao/water",]),
        
           });


