//Cracked by Roath
// /d/huanghe/changle/bangjob/info_business.h
// by aln 2 / 98

mapping info_business = ([
/*YEL"长白山人参" NOR: 
       ([   "changbai"  :  40 + random(120),
            "city"      :  50 + random(180),
            "dali"      :  40 + random(150),
            "emei"      :  50 + random(120),
            "forest"    :  40 + random(100),
            "foshan"    :  40 + random(240),
            "hangzhou"  :  40 + random(200),
            "huashan"   :  40 + random(120),
            "jiaxing"   :  40 + random(180),
            "qilian"    :  40 + random(100),
            "quanzhou"  :  50 + random(220),
            "shaolin"   :  40 + random(100),
            "taihu"     :  40 + random(180),
            "taishan"   :  40 + random(150),
            "village"   :  50 + random(100),
	    "wudang"    :  40 + random(100),
            "xingxiu"   :  60 + random(120),
            "xixia"     :  70 + random(160),
            "xueshan"   :  40 + random(120),
      ]),
 */
CYN"绸缎"NOR : 
      ([    "changbai"  :  50 +  random(180),
            "city"      :  40 +  random(100),
            "dali"      :  45 +  random(120),
            "emei"      :  40 +  random(140),
            "forest"    :  45 +  random(120),
            "foshan"    :  45 +  random(140),
            "hangzhou"  :  40 +  random(100),
            "huashan"   :  40 +  random(150),
            "jiaxing"   :  45 +  random(80),
            "qilian"    :  50 +  random(200),
            "quanzhou"  :  45 +  random(120),
            "shaolin"   :  40 +  random(150),
            "taihu"     :  40 +  random(80),
            "taishan"   :  45 +  random(100),
            "village"   :  40 +  random(120),
            "wudang"    :  40 +  random(140),
            "xingxiu"   :  50 +  random(220),
            "xixia"     :  50 +  random(240),
            "xueshan"   :  40 +  random(180),
      ]),
HIY"首饰"NOR :
       ([   "changbai"  :  40 +  random(80),
            "city"      :  40 +  random(80),
            "dali"      :  40 +  random(80),
            "emei"      :  50 +  random(80),
            "forest"    :  44 +  random(80),
            "foshan"    :  40 +  random(80),
            "hangzhou"  :  40 +  random(80),
            "huashan"   :  40 +  random(80),
            "jiaxing"   :  40 +  random(80),
            "qilian"    :  40 +  random(80),
            "quanzhou"  :  50 +  random(80),
            "shaolin"   :  40 +  random(80),
            "taihu"     :  40 +  random(80),
            "taishan"   :  40 +  random(80),
            "village"   :  50 +  random(80),
	    "wudang"    :  40 +  random(80),
            "xingxiu"   :  60 +  random(80),
            "xixia"     :  70 +  random(80),
            "xueshan"   :  40 +  random(80),
      ]),  
HIG"字画"NOR : 
      ([    "changbai"  :  50 + random(80),
            "city"      :  60 + random(80),
            "dali"      :  45 + random(80),
            "emei"      :  70 + random(80),
            "forest"    :  55 + random(80),
            "foshan"    :  75 + random(80),
            "hangzhou"  :  50 + random(80),
            "huashan"   :  40 + random(80),
            "jiaxing"   :  65 + random(80),
            "qilian"    :  50 + random(80),
            "quanzhou"  :  65 + random(80),
            "shaolin"   :  40 + random(80),
            "taihu"     :  70 + random(80),
            "taishan"   :  55 + random(80),
            "village"   :  40 + random(80),
            "wudang"    :  40 + random(80),
            "xingxiu"   :  50 + random(80),
            "xixia"     :  50 + random(80),
            "xueshan"   :  40 + random(80),
      ]),
HIW"瓷器"NOR : 
      ([    "changbai"  :  50 + random(80),
            "city"      :  40 + random(80),
            "dali"      :  45 + random(80),
            "emei"      :  40 + random(80),
            "forest"    :  45 + random(80),
            "foshan"    :  45 + random(80),
            "hangzhou"  :  40 + random(80),
            "huashan"   :  40 + random(80),
            "jiaxing"   :  55 + random(80),
            "qilian"    :  50 + random(80),
            "quanzhou"  :  45 + random(80),
            "shaolin"   :  40 + random(80),
            "taihu"     :  60 + random(80),
            "taishan"   :  45 + random(80),
            "village"   :  40 + random(80),
            "wudang"    :  40 + random(80),
            "xingxiu"   :  50 + random(80),
            "xixia"     :  50 + random(80),
            "xueshan"   :  40 + random(80),
      ]),  
]);
