//Cracked by Roath
// /d/huanghe/bangjob/bangjob50000.c

// inherit SKILL;

inherit F_CLEAN_UP;

mapping *bangjobs = ({
        ([      "name"  :  "ÀîãäÜÆ",
                "file"  :  "/d/city/npc/yuanzhi",
                "area"  :  "ÑïÖÝ³ÇÌá¶½¸®",
                "type"  :  "É±",
                "bonus" :  250,
                "score" :  50,
        ]),

        ([      "name"  :  "ÁèÍËË¼",
                "file"  :  "/d/city/npc/tuisi",
                "area"  :  "ÑïÖÝº²ÁÖ¸®",
                "type"  :  "É±",
                "bonus" :  250,
                "score" :  50,
        ]),

        ([      "name"  :  "ÁÖÕðÄÏ",
                "file"  :  "/d/city/npc/linzhennan",
                "area"  :  "ÑïÖÝ¸£ÍþïÚ¾Ö",
                "type"  :  "É±",
                "bonus" :  360,
                "score" :  75,
        ]),

        ([      "name"  :  "Àî¿ËÐã",
                "file"  :  "/d/city/npc/kexiu",
                "area"  :  "ÑïÖÝ³ÇÌá¶½¸®",
                "type"  :  "É±",
                "bonus" :  320,
                "score" :  60,
        ]),

        ([      "name"  :  "ºöÂ×´ó»¢",
                "file"  :  "/d/changbai/npc/juren1",
                "area"  :  "ÁÉ¶«",
                "type"  :  "É±",
                "bonus" :  360,
                "score" :  55,
        ]),

        ([      "name"  :  "ºöÂ×¶þ»¢",
                "file"  :  "/d/changbai/npc/juren2",
                "area"  :  "ÁÉ¶«",
                "type"  :  "É±",
                "bonus" :  255,
                "score" :  54,
        ]),

        ([      "name"  :  "ºöÂ×Èý»¢",
                "file"  :  "/d/changbai/npc/juren3",
                "area"  :  "ÁÉ¶«",
                "type"  :  "É±",
                "bonus" :  250,
                "score" :  53,
        ]),

        ([      "name"  :  "ºöÂ×ËÄ»¢",
                "file"  :  "/d/changbai/npc/juren4",
                "area"  :  "ÁÉ¶«",
                "type"  :  "É±",
                "bonus" :  245,
                "score" :  52,
        ]),

        ([      "name"  :  "Ô¬¹ÚÄÐ",
                "file"  :  "/d/forest/npc/guannan",
                "area"  :  "ÑïÖÝ½¼Íâ",
                "type"  :  "É±",
                "bonus" :  280,
                "score" :  52,
        ]),

        ([      "name"  :  "ÁÖÓñÁú",
                "file"  :  "/d/forest/npc/lin",
                "area"  :  "ÑïÖÝ½¼Íâ",
                "type"  :  "É±",
                "bonus" :  280,
                "score" :  65,
        ]),

        ([      "name"  :  "ÈÎ·ÉÑà",
                "file"  :  "/d/forest/npc/ren",
                "area"  :  "ÑïÖÝ½¼Íâ",
                "type"  :  "É±",
                "bonus" :  280,
                "score" :  55,
        ]),

        ([      "name"  :  "×æÇ§Çï",
                "file"  :  "/d/forest/npc/qiu",
                "area"  :  "»ÆºÓ°¶±ß",
                "type"  :  "É±",
                "bonus" :  250,
                "score" :  62,
        ]),

        ([      "name"  :  "ÏôÖÐ»Û",
                "file"  :  "/d/forest/npc/zhonghui",
                "area"  :  "ÑïÖÝ½¼Íâ",
                "type"  :  "É±",
                "bonus" :  380,
                "score" :  65,
        ]),

        ([      "name"  :  "º£ÀÏ¹«",
                "file"  :  "/d/jiaxing/npc/hai",
                "area"  :  "¼ÎÐË³Ç",
                "type"  :  "É±",
                "bonus" :  240,
                "score" :  62,
        ]),

        ([      "name"  :  "ÏòÎÊÌì",
                "file"  :  "/d/jiaxing/npc/xiang",
                "area"  :  "ÑïÖÝ½¼Íâ",
                "type"  :  "É±",
                "bonus" :  220,
                "score" :  40,
        ]),

        ([      "name"  :  "³Âä°",
                "file"  :  "/d/quanzhou/npc/chenhu",
                "area"  :  "ÈªÖÝÑïÍþÎä¹Ý",
                "type"  :  "É±",
                "bonus" :  250,
                "score" :  62,
        ]),

        ([      "name"  :  "¼ÖÈË´ï",
                "file"  :  "/d/quanzhou/npc/jiarenda",
                "area"  :  "ÈªÖÝÉ½Â·",
                "type"  :  "É±",
                "bonus" :  260,
                "score" :  50,
        ]),

        ([      "name"  :  "ÂíÎåµÂ",
                "file"  :  "/d/quanzhou/npc/mawude",
                "area"  :  "ÈªÖÝÑïÍþÎä¹Ý",
                "type"  :  "É±",
                "bonus" :  280,
                "score" :  50,
        ]),

        ([      "name"  :  "½­°ÙÊ¤",
                "file"  :  "/d/taishan/npc/jiang",
                "area"  :  "Ì©É½",
                "type"  :  "É±",
                "bonus" :  280,
                "score" :  60,
        ]),

        ([      "name"  :  "Ìú°ËØÔ",
                "file"  :  "/d/city/obj/tiebagua",
                "type"  :  "Ñ°",
                "bonus" :  220,
                "score" :  65,
        ]),

        ([      "name"  :  "Ìú¼×",
                "file"  :  "/clone/armor/tiejia",
                "type"  :  "Ñ°",
                "bonus" :  212,
                "score" :  63,
        ]),

        ([      "name"  :  "Ñ©Á«",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  280,
                "score" :  120,
        ]),

        ([      "name"  :  "°Ù²Ýµ¤",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  210,
                "score" :  42,
        ]),

        ([      "name"  :  "ÐÛ»ÆÍè",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  230,
                "score" :  41,
        ]),

        ([      "name"  :  "ºüÀêÆ¤",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  44,
        ]),

        ([      "name"  :  "³¤°×É½ÈË²Î",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  30,
        ]),

        ([      "name"  :  "µ±¹é",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  42,
        ]),

        ([      "name"  :  "´óÑªÌÙ",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  260,
                "score" :  55,
        ]),

        ([      "name"  :  "ÈË²Î¹û",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  280,
                "score" :  60,
        ]),

        ([      "name"  :  "ÐøÃü°Ëµ¤",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  280,
                "score" :  40,
        ]),

        ([      "name"  :  "Ê×ÎÚ¾«",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  83,
        ]),

        ([      "name"  :  "ÌïÆßöèµ¨É¢",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  52,
        ]),

        ([      "name"  :  "ÎÞ³£µ¤",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  62,
        ]),

        ([      "name"  :  "ÁéÖ¥",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  280,
                "score" :  40,
        ]),

        ([      "name"  :  "ºÎÊ×ÎÚ",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  230,
                "score" :  45,
        ]),

        ([      "name"  :  "ÀÏÉ½²Î",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  42,
        ]),

        ([      "name"  :  "ÌúÇò",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  260,
                "score" :  60,
        ]),

        ([      "name"  :  "ÎäÊ¿µ¶",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  220,
                "score" :  55,
        ]),

        ([      "name"  :  "ÎäÊ¿·þ",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  220,
                "score" :  65,
        ]),

        ([      "name"  :  "³ÂÔ²Ô²ÊÖÅÁ",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  450,
                "score" :  62,
        ]),

        ([      "name"  :  "Ê©½«¾üÁîÅÆ",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  250,
                "score" :  42,
        ]),

        ([      "name"  :  "÷»×Ó",
                "file"  :  "  ",
                "type"  :  "Ñ°",
                "bonus" :  224,
                "score" :  45,
        ]),

        ([      "name"  :  "»ÆÒÂ¾ü·þ",
                "file"  :  "/d/dali/obj/ycloth",
                "type"  :  "Ñ°",
                "bonus" :  220,
                "score" :  45,
        ]),

        ([      "name"  :  "±´¿ÇÏîÁ´",
                "file"  :  "/d/dali/npc/obj/shelllace",
                "type"  :  "Ñ°",
                "bonus" :  280,
                "score" :  40,
        ]),

        ([      "name"  :  "Âùµ¶",
                "file"  :  "/d/dali/obj/mandao",
                "type"  :  "Ñ°",
                "bonus" :  260,
                "score" :  45,
        ]),

        ([      "name"  :  "½õÒÂ¾ü·þ",
                "file"  :  "/d/dali/obj/jcloth",
                "type"  :  "Ñ°",
                "bonus" :  260,
                "score" :  45,
        ]),

        ([      "name"  :  "½ðîÎ",
                "file"  :  "/d/forest/npc/obj/jinchai",
                "type"  :  "Ñ°",
                "bonus" :  220,
                "score" :  55,
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),

        ([      "type"  :  "½ØïÚ",
        ]),
});

void create() { seteuid(getuid()); }

mapping query_job()
{
        return bangjobs[random(sizeof(bangjobs))];
}

