#include <ansi.h>
mapping *quest = ({
     (["short":                "天地会 大厅",
       "place" :              "/d/city2/dating",]),   
     (["short":                "向阳老宅 井底",
        "place" :              "/d/quanzhou/well1",]),   
     (["short":                "玄天派 石门",
       "place" :              "/d/xuantian/door",]), 
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
     (["short":                "痴心妄想门 田野",
       "place" :              "/d/cxwxm/tianye",]),   
     (["short":                "痴心妄想门 后门",
       "place" :              "/d/cxwxm/dayuan",]),   
      (["short":                "桃花岛 墓地",
       "place" :              "/d/taohua/mudi",]),   
      (["short":                "桃花迷阵",
       "place" :              "/d/taohua/tao_in",]),   
      (["short":                "鳌府大院",
       "place" :              "/d/city2/aobai3",]),   
      (["short":                "千毒窟外",
       "place" :              "/d/wudujiao/qiandu1",]),   
      (["short":                "百丈涧",
       "place" :              "/d/lingjiu/jian",]),  
      (["short":                "灵鹫宫 蓼风轩",
       "place" :              "/d/lingjiu/wuqiku",]),  
      (["short":                "舍利塔",
       "place" :              "/d/tianlongsi/ta1",]),   
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
      (["short":                "摆夷字馆",
       "place" :              "/d/dali/shuyuan",]),  
      (["short":                "飘香花店",
       "place" :              "/d/dali/huadian",]),  
      (["short":                "嘉明殿",
       "place" :              "/d/dali/huanggong16",]), 
     (["short":                "峨嵋报国寺",
       "place" :              "/d/emei/baoguosi",]),
     (["short":                "白鹤泉",
       "place" :              "/d/taishan/baihe",]),
     (["short":                "南码头",
       "place" :              "/d/nanyang/matou1",]),
     (["short":                "雪山-圣湖",
       "place" :              "/d/xueshan/shenghu",]),
     (["short":                "雪山藏经室",
       "place" :              "/d/xueshan/cangjingge",]),  
      (["short":                "百木园",
       "place" :              "/d/meizhuang/yuan",]),  
      (["short":                "杜甫草堂",
       "place" :              "/d/city3/caotang",]), 
      (["short":                "浣花溪边",
       "place" :              "/d/city3/huanhuaxi1",]), 
      (["short":                "成都百花潭",
       "place" :              "/d/city3/cdta",]), 
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
      (["short":                "武侯祠",
       "place" :              "/d/city3/wuhou",]), 
      (["short":                "春熙路",
       "place" :              "/d/city3/chunxilu1",]), 
      (["short":                "陆羽茶馆",
       "place" :              "/d/city3/chaguan",]), 
      (["short":                "温宅大门",
       "place" :              "/d/city3/wenzai/gate",]), 
      (["short":                "薛涛井",
       "place" :              "/d/city3/xuetao",]), 
      (["short":                "望江楼二楼",
       "place" :              "/d/city3/wangjianglou2",]),
       (["short":                "成都 酿酒屋",
       "place" :              "/d/city3/niangjiuwo",]), 
       (["short":                "成都 占卜铺子",
       "place" :              "/d/city3/zhanbu",]), 
      (["short":                "昭觉寺",
       "place" :              "/d/city3/shimiao",]), 
      (["short":                "成都  凉亭",
       "place" :              "/d/city3/liangting",]), 
      (["short":                "北疆小镇 巴依家院",
       "place" :              "/d/xingxiu/house",]), 
      (["short":                "星宿海",
       "place" :              "/d/xingxiu/xxh1",]), 
      (["short":                "星宿海 山间平地",
       "place" :              "/d/xingxiu/xxroad6",]), 
      (["short":                "白驼山 药房",
       "place" :              "/d/baituo/yaofang",]), 
      (["short":                "武当 榔梅园篱笆",
       "place" :              "/d/wudang/nanyan",]), 
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
      (["short":                "三老峰",
       "place" :              "/d/wudang/sanlao",]), 
      (["short":                "太子坡",
       "place" :              "/d/wudang/xuanwumen",]), 
      (["short":                "磨针井",
       "place" :              "/d/wudang/shuijing",]), 
      (["short":                "峨嵋十二盘",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "峨嵋千佛庵",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "牛心亭",
       "place" :              "/d/emei/niuxinting",]), 
      (["short":                "明教厚土旗门",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "明教烈火旗后门",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
      (["short":                "泉州南门",
       "place" :              "/d/quanzhou/nanmen",]), 
      (["short":                "嘉兴南门",
       "place" :              "/d/quanzhou/jxnanmen",]), 
      (["short":                "少林寺 青云坪",
       "place" :              "/d/shaolin/qyping",]),
      (["short":                "少林寺 东碑林",
       "place" :              "/d/shaolin/beilin1",]), 
      (["short":                "少林寺 天王殿",
       "place" :              "/d/shaolin/twdian",]),
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]), 
      (["short":                "华山镇岳宫",
       "place" :              "/d/huashan/zhenyue",]),
      (["short":                "华山玉女峰山路",
       "place" :              "/d/huashan/shanlu",]),
      (["short":                "慕容燕子坞",
       "place" :              "/d/mr/yanziwu",]),
      (["short":                "慕容云锦楼",
       "place" :              "/d/mr/yunjinlou",]),
      (["short":                "大理夕照路",
       "place" :              "/d/dali/xbdajie2",]),
      (["short":                "少林寺山门殿",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "天府广场",
       "place" :              "/d/city3/guangchang",]),
      (["short":                "雪山山脚",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "峨嵋九老洞",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "峨嵋古德林",
       "place" :              "/d/emei/gudelin",]),
       (["short":                "成都石拱桥",
       "place" :              "/d/city3/gongqiao",]),
       (["short":                "成都薛涛井",
       "place" :              "/d/city3/xuetao",]),
       (["short":                "成都府南河畔",
       "place" :              "/d/city3/funanhe1",]),
       (["short":                "汉水南岸",
       "place" :              "/d/nanyang/hanshui1",]),
       (["short":                "中条山密林",
       "place" :              "/d/huashan/jzroad5",]),
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]), 
       (["short":                "天山脚下",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "华山脚下",
       "place" :              "/d/huashan/path1",]),
        (["short":                "天香堂",
       "place" :              "/d/heimuya/dating4",]),
       (["short":                "乱石坡",
       "place" :              "/d/heimuya/road1",]),      
       (["short":                "长安 乐府诗社",
       "place" :              "/d/changan/shishe",]),   
       (["short":                "长安 太白居",
       "place" :              "/d/changan/shuyuan",]),  
       (["short":                "武功镇的中心广场",
       "place" :              "/d/wugongzhen/zhongxin",]),  
       (["short":                "神龙教大厅",
       "place" :              "/d/shenlong/dating",]),  
       (["short":                "移花宫 雨花阁",
       "place" :              "/d/yihua/bingqi",]),  
       (["short":                "移花宫 密道",
       "place" :              "/d/yihua/midao",]),  
       (["short":                "移花宫 莲花池",
       "place" :              "/d/yihua/lianhuachi",]), 
       ([ "short":                "华山村南村口",
          "place":                "/d/village/sexit",
        ]), ([       "short":                "玉皇顶",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "六盘山",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "天山山路",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "嘉峪关",

                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "西单北大街",
                "place":                "/d/city2/xidan1",
        ]),([      "short":                "嘉兴南湖",
                "place":                "/d/quanzhou/nanhu",
        ]),([      "short":                "王府井大街",
                "place":                "/d/city2/wangfu2",
        ]),([      "short":                "破旧长城",
                "place":                "/d/gaochang/room3",
        ]),([      "short":                "龙门客栈",
                "place":                "/d/gaochang/room16",
        ]),([      "short":                "老龙头",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "嘉兴城",
                "place":                "/d/quanzhou/jiaxing",
        ]),([      "short":                "扬州西门",
                "place":                "/d/city/ximen",
        ]),([      "short":                "星星峡",
                "place":                "/d/gaochang/room52",
        ]),([      "short":                "一天门",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "关外 小土屋",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "铁索桥",
                "place":                "/d/heimuya/zhaoze/tsq",
        ]),([      "short":                "澜沧江畔",
                 "place":                "/d/heimuya/zhaoze/lczb",
        ]),([      "short":                "无量山界",
                 "place":                "/d/city3/shudao3",
        ]),([      "short":                "朝天门",
                 "place":                "/d/songshan/chaotian",
        ]),([      "short":                "碧水神潭",
                 "place":                "/d/nanyang/shuitan",
        ]),([      "short":                "铁梁峡",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "峻极禅院山门",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "嵩山",
                 "place":                "/d/songshan/songshan",
        ]),([      "short":                "峻极禅院",
                 "place":                "/d/songshan/chanyuan",
        ]),([      "short":                "天中阁",
                 "place":                "/d/songshan/tianzhongge",
        ]),([      "short":                "平心石",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "千尺幢",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "山洪瀑布",
                  "place":                "/d/huashan/pubu",
        ]),([      "short":                "清音阁",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "十二盘",
                 "place":                "/d/emei/shierpan1",
        ]),([      "short":                "白龙洞",
                 "place":                "/d/emei/bailongdong",
        ]),([      "short":                "清音阁外",
                 "place":                "/d/emei/qingyinge",
        ]),  
     (["short":                "丐帮 树洞下",
       "place" :              "/d/gaibang/undertre",]),   
          });
mapping query_quest()
 {
 return quest[random(sizeof(quest))];
}

