mapping *family = ({
([      "family"        :       "神龙教",
        "title1"        :       "神龙教恶徒",
        "title2"        :       "神龙教尊使",
        "gender"        :       "男性",
        "dodge"         :       "yixing-bufa",
        "parry"         :       "shedao-qigong",
        "staff"         :       "shedao-qigong",
        "force"         :       "shenlong-xinfa",
        "unarmed"       :       "shenlong-bashi",
        "prepare1"      :       "unarmed",
        "exert1"        :       "powerup",
        "perform1"      :       "staff.chang",
        "perform2"      :       "staff.chang1",
        "perform3"      :       "staff.chang2",
        "perform4"      :       "staff.chang3",
        "weapon"        :       __DIR__"obj/shezhang",
]),                                
([      "family"        :       "关外胡家",
        "title1"        :       "胡家刀魔",
        "title2"        :       "胡家刀圣",
        "gender"        :       "男性",
        "class"         :       "sworder",
        "dodge"         :       "sixiang-bufa",
        "blade"         :       "hujia-daofa",
        "parry"         :       "hujia-daofa",
        "force"         :       "lengyue-shengong",
        "strike"        :       "tianchang-zhang",
        "prepare1"      :       "strike",
        "perform1"      :       "blade.bafang",
        "perform2"      :       "strike.huang",
        "weapon"        :       __DIR__"obj/blade",
]),                       
([      "family"        :       "慕容世家",
        "title1"        :       "慕容弟子",
        "title2"        :       "慕容弟子",
        "gender"        :       "男性",
        "class"         :       "sworder",
        "dodge"         :       "beidou-xianzong",
        "sword"         :       "murong-jianfa",
        "parry"         :       "douzhuan-xingyi",
        "force"         :       "shenyuan-gong",
        "finger"        :       "canhe-zhi",
        "prepare1"      :       "sword",
        "prepare2"      :       "blade",
        "perform1"      :       "sword.xing",
        "perform2"      :       "parry.yi",
        "perform3"      :       "finger.lian",
        "weapon"        :       __DIR__"obj/changjian",
]),
([      "family"        :       "少林派", 
        "title1"        :       "少林恶僧",
        "title2"        :       "少林和尚",
        "gender"        :       "男性",
        "class"         :       "bonze",
        "dodge"         :       "shaolin-shenfa",
        "whip"          :       "riyue-bian",
        "parry"         :       "riyue-bian",
        "force"         :       "hunyuan-yiqi",
        "finger"        :       "yizhi-chan",
        "prepare1"      :       "finger",
        "perform1"      :       "whip.chan",
        "perform2"      :       "finger.jingmo",
        "exert1"        :       "powerup",
        "weapon"        :       __DIR__"obj/changbian",
]),
([      "family"        :       "逍遥派",      
        "title1"        :       "逍遥派恶徒",
        "title2"        :       "逍遥派弟子",
        "clasee"        :       "sworder",
        "gender"        :       "男性",
        "dodge"         :       "lingbo-weibu",
        "parry"         :       "zhemei-shou",
        "force"         :       "beiming-shengong",
        "hand"          :       "zhemei-shou",
        "strike"        :       "liuyang-zhang",
        "blade"         :       "ruyi-dao",
        "prepare1"      :       "hand",
        "prepare2"      :       "strike",
        "exert1"        :       "shield",
        "exert2"        :       "powerup",
        "perform1"      :       "blade.ruyi",
        "perform2"      :       "dodge.lingbo",
        "perform4"      :       "hand.duo",
        "weapon"        :       __DIR__"obj/blade",
]),
([      "title1"        :       "段氏皇族弃仆",
        "title2"        :       "段氏皇族侍将",
        "gender"        :       "男性",
        "dodge"         :       "tiannan-bufa",
        "parry"         :       "duanjia-jian",
        "sword"         :       "duanjia-jian",
        "force"         :       "kurong-changong",
        "finger"        :       "yiyang-zhi",
        "prepare1"      :       "finger",
        "exert1"        :       "powerup",
        "perform1"      :       "sword.jing",
        "perform2"      :       "sword.jue",
        "perform3"      :       "finger.qian",
        "weapon"        :       __DIR__"obj/changjian",
]),
([      "title1"        :       "明教恶徒",
        "title2"        :       "光明圣使",
        "gender"        :       "男性",
        "dodge"         :       "qingfu-shenfa",
        "parry"         :       "qiankun-danuoyi",
        "sword"         :       "shenghuo-ling",
        "force"         :       "jiuyang-shengong",
        "cuff"          :       "qishang-quan",
        "prepare1"      :       "cuff",
        "exert1"        :       "powerup",
        "perform1"      :       "sword.hua",
        "perform2"      :       "cuff.shang", 
        "weapon"        :       __DIR__"obj/shenghuoling",
]),                          
([      "title1"        :       "古墓妖女",
        "title2"        :       "古墓女侠",
        "gender"        :       "女性",
        "dodge"         :       "yunv-shenfa",
        "parry"         :       "yinsuo-jinling",
        "whip"          :       "yinsuo-jinling",
        "force"         :       "yunv-xinjing",
        "unarmed"       :       "meinv-quan",
        "prepare1"      :       "unarmed",
        "exert1"        :       "powerup",
        "perform1"      :       "unarmed.you",
        "weapon"        :       __DIR__"obj/changbian",
]), 
([      "title1"        :       "星宿老魔",
        "title2"        :       "星宿门徒",
        "gender"        :       "男性",
        "dodge"         :       "zhaixing-gong",
        "parry"         :       "tianshan-zhang",
        "staff"         :       "tianshan-zhang",
        "force"         :       "huagong-dafa",
        "poison"        :       "xingxiu-qishu",
        "strike"        :       "chousui-zhang",
        "claw"          :       "sanyin-zhua",
        "prepare1"      :       "strike",
        "prepare2"      :       "claw",
        "exert1"        :       "powerup",
        "perform1"      :       "strike.biyan",
        "perform2"      :       "strike.huoqiu",
]),
([      "title1"        :       "白驼淫贼",
        "title2"        :       "白驼山弟子",
        "gender"        :       "男性",
        "dodge"         :       "chanchu-bufa",
        "parry"         :       "lingshe-zhangfa",
        "staff"         :       "lingshe-zhangfa",
        "force"         :       "hamagong",
        "exert1"        :       "powerup",
        "perform1"      :       "staff.qianshe",
        "perform2"      :       "staff.chan",  
        "perform3"      :       "staff.wuji",  
        "weapon"        :       __DIR__"obj/shezhang",
]),
([      "title1"        :       "峨嵋贼尼",
        "title2"        :       "峨嵋女尼",
        "gender"        :       "女性",
        "class"         :       "bonze",
        "dodge"         :       "zhutian",
        "strike"        :       "jinding-zhang",
        "parry"         :       "huifeng-jian",
        "sword"         :       "huifeng-jian",
        "force"         :       "linji-zhuang",
        "finger"        :       "tiangang-zhi",
        "prepare1"      :       "finger",
        "prepare2"      :       "strike",
        "perform1"      :       "sword.mie",
        "perform2"      :       "finger.ling",   
        "exert1"        :       "powerup",
        "weapon"        :       __DIR__"obj/changjian",
]),
([      "title1"        :       "峨嵋贼尼",
        "title2"        :       "峨嵋女尼",
        "gender"        :       "女性",
        "class"         :       "bonze",
        "dodge"         :       "zhutian",
        "parry"         :       "yanxing-dao",
        "blade"         :                 "yanxing-dao",
        "force"         :                 "linji-zhuang",
        "finger"        :                "tiangang-zhi",
        "strike"        :                "jinding-zhang",
        "prepare1"      :              "finger",
        "prepare2"      :              "strike",
        "perform1"      :              "blade.huan",
        "perform2"      :              "finger.ling",   
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/blade",
]),
([      "title1"        :                "灵鹫妖姬",
        "title2"        :                "灵鹫圣使",
        "gender"        :                "女性",
        "class"         :                 "fighter",
        "dodge"         :                 "yueying-wubu",
        "parry"         :                 "tianyu-qijian",
        "sword"         :                 "tianyu-qijian",
        "force"         :                 "bahuang-gong",
        "hand"          :                  "zhemei-shou",
        "unarmed"       :               "liuyang-zhang",
        "prepare1"      :              "hand",
        "prepare2"      :              "strike",
        "perform1"      :              "sword.san",
        "perform2"      :              "strike.zhong",
        "perform3"      :              "hand.duo",
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/changjian",
]),
([      "title1"        :                "丐帮恶丐",
        "title2"        :                "丐帮长老",
        "gender"        :                "男性",
        "class"         :                 "fighter",
        "dodge"         :                 "xiaoyaoyou",
        "parry"         :                         "dagou-bang",
        "staff"         :                 "dagou-bang",
        "force"         :                 "huntian-qigong",
        "strike"        :                "dragon-strike",
        "prepare1"      :              "strike",
        "perform1"      :              "staff.chan",
        "perform2"      :              "staff.duo",
        "perform3"      :              "strike.lei",
        "perform4"      :              "strike.qin",
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/zhubang",
]),
([      "title1"        :                "丐帮恶丐",
        "title2"        :                "丐帮长老",
        "gender"        :                "男性",
        "class"         :                 "fighter",
        "dodge"         :                 "xiaoyaoyou",
        "parry"         :                 "dagou-bang",
        "staff"         :                 "dagou-bang",
        "force"         :                 "huntian-qigong",
        "strike"        :                "dragon-strike",
        "prepare1"      :              "strike",
        "perform1"      :              "strike.lei",
        "perform2"      :              "strike.qin",
        "exert1"        :                "powerup",
]),            
([      "title1"        :                "神秘杀手",
        "title2"        :                "神秘高手",
        "gender"        :                "男性",
        "class"         :                 "fighter",
        "dodge"         :                 "huashan-shenfa",
        "parry"         :                 "dugu-jiujian",
        "sword"         :                 "dugu-jiujian",
        "force"         :                 "zixia-shengong",
        "strike"        :                "hunyuan-zhang",
        "cuff"          :                  "poyu-quan",
        "prepare1"      :              "strike",
        "prepare2"      :              "cuff",
        "perform1"      :              "sword.po",
        "perform2"      :              "sword.poqi",
        "perform3"      :              "sword.pozhang",
        "perform4"      :              "strike.wuji",  
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/changjian",
]),
([      "title1"        :                "华山派剑客",
        "title2"        :                "华山派弃徒",
        "gender"        :                "男性",
        "class"         :                 "fighter",
        "dodge"         :                 "huashan-shenfa",
        "parry"         :                 "huashan-jianfa",
        "sword"         :                 "huashan-jianfa",
        "force"         :                 "zixia-shengong",
        "strike"        :                "hunyuan-zhang",
        "cuff"          :                  "poyu-quan",
        "prepare1"      :              "strike",
        "prepare2"      :              "cuff",
        "perform1"      :              "sword.feilong",
        "perform2"      :              "sword.jianzhang",
        "perform3"      :              "cuff.leidong",
        "perform4"      :              "strike.wuji",
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/changjian",
]),
([      "title1"        :                "华山派女侠",
        "title2"        :                "华山派弃徒",
        "gender"        :                "女性",
        "class"         :                 "fighter",
        "dodge"         :                 "huashan-shenfa",
        "parry"         :                 "yunu-sword",
        "sword"         :                "yunu-sword",
        "force"         :                 "zixia-shengong",
        "strike"        :                "hunyuan-zhang",
        "cuff"          :                  "poyu-quan",
        "prepare1"      :              "strike",
        "prepare2"      :              "cuff",
        "perform1"      :              "sword.wushuang",
        "perform2"      :              "cuff.leidong",
        "perform3"      :              "strike.wuji",
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/changjian",
]), 
([      "title1"        :                "少林恶僧",
        "title2"        :                "少林和尚",
        "gender"        :                "男性",
        "class"         :                 "bonze",
        "dodge"         :                 "shaolin-shenfa",
        "cuff"          :                  "jingang-quan",
        "parry"         :                 "zui-gun",
        "club"          :                  "zui-gun",
        "force"         :                 "hunyuan-yiqi",
        "finger"        :                "nianhua-zhi",
        "strike"        :                "sanhua-zhang",
        "prepare1"      :              "finger",
        "prepare2"      :              "strike",
        "perform1"      :              "club.zui",
        "perform2"      :              "cuff.jingang",
        "exert1"        :                "powerup",
        "weapon"        :                __DIR__"obj/qimeigun",
]),
([      "title1"        :               "古墓逆徒",
        "title2"        :               "古墓大侠",
        "gender"        :               "男性",
        "dodge"         :                "yunv-shenfa",
        "parry"         :                "xuantie-jian",
        "strike"        :               "sad-strike",
        "sword"         :                "xuantie-jian",
        "force"         :                "yunv-xinjing",
        "exert1"        :               "powerup",
        "prepare1"      :              "strike",
        "perform1"      :             "sword.juan",
        "perform3"      :             "sword.dang",
        "perform4"      :             "sword.haichao", 
        "weapon"        :                __DIR__"obj/changjian",
]),
([      "title1"        :                "全真败类",
        "title2"        :                "全真道长",
        "class"         :                         "taoist",
        "gender"        :                "男性",
        "dodge"         :                 "qixing-huanwei",
        "parry"         :                 "quanzhen-jian",
        "unarmed"       :               "kongming-quan",
        "sword"         :                 "quanzhen-jian",
        "force"         :                 "quanzhen-xinfa",
        "finger"        :                "yiyang-zhi",
        "prepare1"      :              "finger",    
        "perform1"      :              "sword.hua",
        "perform2"      :              "sword.lian",
        "perform3"      :              "sword.ding", 
        "perform4"      :              "finger.qian",   
        "weapon"        :                __DIR__"obj/changjian",
]),   
([      "title1"        :                "血刀淫僧",
        "title2"        :                "血刀门喇嘛",
        "gender"        :                "男性",
        "dodge"         :                 "shenkong-xing",
        "parry"         :                 "xuedao-daofa",
        "hand"          :                  "dashou-yin",
        "blade"         :                 "xuedao-daofa",
        "force"         :                 "xuehai-mogong",
        "prepare1"      :              "hand",
        "perform1"      :              "blade.shendao",
        "perform2"      :              "hand.yin",  
        "exert1"        :                "powerup",   
        "weapon"        :                __DIR__"obj/blade",
]),
([      "title1"        :                "雪山寺贼秃",
        "title2"        :                "雪山寺喇嘛",
        "gender"        :                "男性",
        "dodge"         :                 "shenkong-xing",
        "parry"         :                 "mingwang-jian",
        "strike"        :                "huoyan-dao",
        "sword"         :                 "mingwang-jian",
        "force"         :                 "xiaowuxiang",
        "prepare1"      :              "strike",
        "perform1"      :              "sword.ruo",
        "perform2"      :              "strike.fen",
        "exert1"        :                "shield",
        "weapon"        :                __DIR__"obj/changjian",
]), 
([      "title1"        :                "武当败类",
        "title2"        :                "武当道长",
        "class"         :                 "taoist",
        "dodge"         :                 "tiyunzong",
        "parry"         :                 "taiji-quan", 
        "cuff"          :                  "taiji-quan",
        "sword"         :                 "taiji-jian",
        "force"         :                 "taiji-shengong",
        "perform1"      :              "sword.lian",
        "perform2"      :              "cuff.zhen",
        "weapon"        :                __DIR__"obj/changjian",
]),
([      "title1"        :                "武当败类",
        "title2"        :                "武当道长",
        "class"         :                 "taoist",
        "dodge"         :                 "tiyunzong",
        "parry"         :                 "taiji-quan",
        "cuff"          :                  "taiji-quan",
        "sword"         :                 "taiji-jian",
        "blade"         :                 "taiji-dao",
        "force"         :                 "taiji-shengong",
        "prepare1"      :              "sword",
        "prepare2"      :              "blade",   
        "perform1"      :              "sword.lian",
        "perform3"      :              "cuff.zhen",
        "weapon"        :                __DIR__"obj/changjian",
        "weapon_s"      :              __DIR__"obj/blade",
]), 
([      "title1"        :                "桃花岛逐徒",
        "title2"        :                "桃花岛门下",
        "dodge"         :                 "luoying-shenfa",
        "finger"        :                "tanzhi-shentong",
        "hand"          :                  "lanhua-shou",
        "parry"         :                 "yuxiao-jianfa",
        "sword"         :                 "yuxiao-jianfa",
        "force"         :                 "bibo-shengong",
        "exert1"        :                "powerup",
        "perform1"      :              "sword.qing",
        "perform2"      :              "sword.tian",     
        "perform3"      :              "hand.fuxue",
        "perform4"      :              "finger.jinglei",
        "prepare1"      :              "finger",
        "prepare2"      :              "hand",
        "weapon"        :                __DIR__"obj/yuxiao",
]),
([      "title1"        :                "桃花岛逐徒",
        "title2"        :                "桃花岛门下",
        "dodge"         :                 "luoying-shenfa",
        "unarmed"       :               "xuanfeng-tui",   
        "strike"        :                "luoying-zhang",    
        "parry"         :                 "luoying-shenjian"
        "sword"         :                 "luoying-shenjian"
        "force"         :                 "bibo-shengong"
        "exert1"        :                "powerup"
        "perform1"      :              "unarmed.kuang"
        "prepare1"      :              "unarmed"
        "weapon"        :                __DIR__"obj/changjian"
])
})
