
mapping allloca=([
	"扬州城":({"/d/city/","beidajie1","beidajie2","beimen","bingyin",
				"houyuan","mishi","nandajie1","nandajie2","neizhai","pomiao",
				"postoffice","xidajie1","xidajie2","ximen",}),
    "北京城":({"/d/city2/","alley1","alley2","alley3","andao1","andao10",
               "andao2","andao3","andao4","andao5","andao6","andao7","andao8",
               "andao9","anding","aobai1","aobai10","aobai11","aobai12","aobai2",
               "aobai3","aobai4","aobai5","aobai7",
               "bingqiku","bingyin1","bingyin2","bridge","bridge2","bridge3","ceting",
               "chaguan","chaoyan1","chaoyan2","chaoyang","datiepu","dating",
               "di_an1","di_an2","di_an3","di_an4","di_anmen",
               "dongcha1","dongcha2","dongchangdamen","dongmen","fotang","guancai1","guancai2","haigang",
               "hbridge","houtai","huayuan","huichunt","kang1",
               "kang2","kang3","mapeng","nandaj1","nandaj2","neishi",
               "neitang","qishi","road1","road10","road2","road3",
               "road4","road5","road6","road7","road8","road9",
               "stage","tian_anm","tuzai","wangfu1",
               "wangfu2","wangfu3","wuchang","wuqiku","xiaotan","xiaoyuan",
               "xichang1","xichang2","xichangdamen","xidan","xidan1","ximen","ximenwai",
               "xisi","xisi2","yongding","zhengmen","zhuang1",
               "zhuang2","zhuang3","zhuang4","zhuang5","zhuang6","zhuang7","zhuang8","zhuang9",
               "zhulin1","zhulin2","zhulin3","zhulin4","zhulin5",
                }),
    "白驼山":({"/d/baituo/","bridge","cao1","cao2","caomeide","caoping","cave","cave1","cedong",
               "chaifang","changlang","chufang","damen","dating","dongjie",
               "dongkou","dongnei","fang","fende","guangchang","houmen","houyuan",
               "huayuan","liangong","menlang","midao","mumen","neishi","nongshe",
               "room1","room2","room3","shanlu","shanlu1","shijie","shulin",
               "shulin1","tuyuan","wuqiku","xiaolu1","xiaolu2","xiaolu3",
               "xiaolu4","xijie","ximen","yuanzi","zhailuo","zhulin","zhuyuan",
                }),
    "灵鹫宫":({"/d/lingjiu/","biguan","caifeng","changl1","changl10","changl11",
               "changl12","changl13","changl14","changl2","changl3",
               "changl4","changl5","changl6","changl7","changl8","changl9","chufang",
               "daban","dadao1","dadao2","damen","dating","huayuan","jian","liangong",
               "men1","men2","men3","shanjiao","shufang","wuqiku","xianchou",
               "xiaodao1","xiaodao2",   

             }),
    "南阳":({"/d/nanyang/","hanshui1","hanshui2","matou1","matou2","nanyang",
             "ruzhou","wangxi-lu","wangxi-lu","xiaozheng","ximen",
             "yidao","yidao2","yidao3",             
             }),
    "泉州" :({"/d/quanzhou/","beimen","haigang","houyuan","huangye","jiaxing",
              "jxnanmen","laozhai","midao","mishi","nanhu","nanhu1","nanmen",
              "qzroad1","qzroad2","qzroad3","qzroad4","qzroad5","tieqiang",
              "xijie","zhongxin",
             }),

     ]);

// 通过下面定义的地图范围自动搜索其bin文件来获取刷怪位置 Add By Wenwu，
mapping guai_place = ([
	"扬州城"   : "/d/city/",
	"泉州"     : "/d/quanzhou/",
	"灵鹫宫"   : "/d/lingjiu/",
	"白驼山"   : "/d/baituo/",
	"北京城"   : "/d/city2/",
	"大理"     : "/d/dali/",
	"峨嵋山"   : "/d/emei/",
	"武当山"   : "/d/wudang/",
	"红花会"   : "/d/honghua/",
	"浣花剑派" : "/d/huanhua/",
	"华山村"   : "/d/village/",
	"逍遥派"   : "/d/xiaoyao/",
	"星宿海"   : "/d/xingxiu/",
	"雪山寺"   : "/d/xueshan/",
	"血刀门"   : "/d/xuedao/",
	"天龙寺"   : "/d/tianlongsi/",
	"铁掌山"   : "/d/tiezhang/",
	"嵩山"     : "/d/songshan/",
	"绝情谷"   : "/d/jqg/",
	"泰山"     : "/d/taishan/",
	"杀手楼"   : "/d/shashou/",
	"凌霄城"   : "/d/lingxiao/",
	"青城山"   : "/d/qingcheng/",
	"唐门"     : "/d/tangmen/",
	"襄阳城"   : "/d/xiangyang/",
	"梅庄"     : "/d/meizhuang/",
	"全真教"   : "/d/quanzhen_old/",
	"衡山"     : "/d/henshan/",
	"恒山"     : "/d/hengshan/",
	"燕子坞"   : "/d/mr/",
	"关外"     : "/d/guanwai/",
	"蒙古"     : "/d/menggu/",
	"南阳"     : "/d/nanyang/"
	]);