#ifndef l_setup_h
#define l_setup_h

#include "domains.h"

mapping Cemeteries = ([
  "Arcanith": FROSTMARCHES_TOWNS "arcanith/room/cemetary",
  "Averath": AVERATH_TOWNS "averath/room/cemetery",
  "Baria": BARIA_TOWNS "baria/room/cemetery",
  "Dalnairn": AVERATH_TOWNS "dalnairn/room/cemetery",
  "Durgoroth": FROSTMARCHES_TOWNS "durgoroth/room/cemetery",
  "Glimmerdin": CRYSTAL_REACHES_TOWNS "glimmerdin/room/cemetery",
  "Grymxoria": ESTERGRYM_TOWNS "grymxoria/room/cemetery",
  "Gwonish": CRYSTAL_REACHES_TOWNS "gwonish/room/cemetery",
  "Gurov": GUROV_TOWNS "gurov/room/cemetery",
  "Haven": SOUTHERN_COAST_TOWNS "haven/room/cemetery",
  "Havenwood": HAVENWOOD_TOWNS "havenwood/room/gelf9",
  "Jidoor": VALLEY_TOWNS "jidoor/room/cemetery",
  "Karak": CRYSTAL_REACHES_TOWNS "karak/room/cemetery",
  "Keryth": FROSTMARCHES_TOWNS "keryth/room/cemetery",
  "Kresh": SOUTHERN_COAST_TOWNS "kresh/room/cem",
  "Lloryk": CRYSTAL_REACHES_TOWNS "lloryk/room/mausoleum",
  "Lisht": XANDRIA_TOWNS "lisht/room/death",
  "Malveillant": HAVENWOOD_TOWNS "malveillant/rooms/grave",
  "Underland": VALLEY_TOWNS "underland/room/cemetery",
  "Parva": HAVENWOOD_TOWNS "parva/room/cemetery",
  "Soleil": WESTWOOD_TOWNS "soleil/room/cemetery",
  "Sanctum": PENINSULA_TOWNS "sanctum/room/cemetery",
  "Tairi": TAIRI_TOWNS "tairi/room/cemetery",
  "Yozrath": YOZRATH_TOWNS "yozrath/room/oasis5",
]);

mapping MoveMessages = ([
  "lamrani": ({ "$N drifts $D effortlessly.", "$N drifts in effortlessly." }),
  "sprite": ({ "$N buzzes out $D", "$N buzzes in." }),
]);

mapping Religions = ([
  "Arcanith": "agnostic",
  "Averath": "Aetarin",
  "Baria": "Kuthar",
  "Dalnairn": "Soirin",
  "Durgoroth": "Saahagoth",
  "Glimmerdin": "Kylin",
  "Grymxoria": "Aberach",
  "Gwonish": "Kuthar",
  "Gurov": "Kylin",
  "Haven": "Kylin",
  "Havenwood": "Eclat",
  "Jidoor": "Magildan",
  "Karak": "Saahagoth",
  "Keryth": "Soirin",
  "Kresh": "Kuthar",
  "Lisht": "Enniae",
  "Lloryk": "Eclat",
  "Malveillant": "Soirin",
  "Parva": "agnostic",
  "Soleil": "Eclat",
  "Tairi": "Eclat",
  "Ungkh": "Kuthar",
  "Underland": "agnostic",
  "Yozrath": "Kylin",
]);

mapping StartingAges = ([
  "daemon": 80,
  "dark-elf": 50,
  "draconian": 25,
  "dark-dwarf": 50,
  "dwarf": 50,
  "elf": 60,
  "gelfling": 16,
  "gnoll": 3,
  "gnome": 20,
  "goblin": 12,
  "goden": 18,
  "halfling": 20,
  "half-elf": 20,
  "half-orc": 17,
  "human": 17,
  "kobold": 15,
  "lamrani": 20,
  "lizardman": 15,
  "muezzin": 18,
  "nosferatu": 40,
  "ogre": 15,
  "orc": 17,
  "skaven": 15,
  "sprite": 18,
  "wild-elf": 40,
]);

mapping StartingLanguages = ([
  "Arcanith": "Koblich",
  "Averath": "Avera",
  "Baria": "Barian",
  "Dalnairn": "Runic",
  "Durgoroth": "Gryshnak",
  "Glimmerdin": "Runic",
  "Grymxoria": "Blaodric",
  "Gwonish": "Slith",
  "Gurov": "Gurovian",
  "Haven": "Eltherian",
  "Havenwood": "Eltherian",
  "Jidoor": "Sprith",
  "Karak": "Uruk",
  "Keryth": "Eetria",
  "Kresh": "Gobyshkin",
  "Lloryk": "Eltherian",
  "Lisht": "Rehshai",
  "Malveillant": "Eltherian",
  "Parva": "Enlan",
  "Soleil": "Oiseau",
  "Sanctum": "Imperial",
  "Tairi": "Tai",
  "Ungkh": "Uruk",
  "Underland": "Nibelungen",
  "Yozrath": "Padashi",
]);

mapping StartRooms = ([
  "Arcanith": FROSTMARCHES_TOWNS "arcanith/room/park",
  "Averath": AVERATH_TOWNS "averath/room/church",
  "Baria": BARIA_TOWNS "baria/room/path9",
  "Dalnairn": AVERATH_TOWNS "dalnairn/room/hall",
  "Durgoroth": FROSTMARCHES_TOWNS "durgoroth/room/start",
  "Glimmerdin": CRYSTAL_REACHES_TOWNS "glimmerdin/room/keep",
  "Grymxoria": ESTERGRYM_TOWNS "grymxoria/room/road16",
  "Gwonish": CRYSTAL_REACHES_TOWNS "gwonish/room/gw07",
  "Gurov": GUROV_TOWNS "gurov/room/keep1",
  "Haven": SOUTHERN_COAST_TOWNS "haven/room/misc_buildings/start_room",
  "Havenwood": HAVENWOOD_TOWNS "havenwood/room/gelf4",
  "Jidoor": VALLEY_TOWNS "jidoor/room/twnsquare",
  "Karak": CRYSTAL_REACHES_TOWNS "karak/room/rd3",
  "Keryth": FROSTMARCHES_TOWNS "keryth/room/townhall",
  "Kresh": SOUTHERN_COAST_TOWNS "kresh/room/tents/shaman",
  "Lloryk": CRYSTAL_REACHES_TOWNS "lloryk/room/town_hall",
  "Lisht": XANDRIA_TOWNS "lisht/room/start",
  "Malveillant": HAVENWOOD_TOWNS "malveillant/rooms/center2",
  "Parva": HAVENWOOD_TOWNS "parva/room/town_hall",
  "Soleil": WESTWOOD_TOWNS "soleil/room/temple",
  "Sanctum": PENINSULA_TOWNS "sanctum/room/forum",
  "Tairi": TAIRI_TOWNS "tairi/room/p1",
  "Underland": VALLEY_TOWNS "underland/room/newbie",
  "Yozrath": YOZRATH_TOWNS "yozrath/room/oasis4",
]);

mapping Towns = ([
  "dark-elf": ({ "Malveillant" }),
  "dwarf": ({ "Glimmerdin" }),
  "elf": ({ "Haven" }),
  "half-elf": ({ "Parva", "Haven", "Malveillant", }),
  "half-orc": ({ "Parva", "Karak" }),
  "human": ({ "Parva", "Haven", "Sanctum", "Karak" }),
  "orc": ({ "Karak" }),
  "wild-elf": ({ "Havenwood" }),
  "sprite": ({ "Jidoor" }),
  "lamrani": ({ "Jidoor" }),
  "skaven": ({ "Malveillant" }),
]);

mapping AdvancedStart = ([
  "human": ({
    "Gurov",
    "Yozrath",
    "Tairi",
    "Baria",
    "Parva",
    "Haven",
    "Sanctum",
    "Averath",
    "Karak"
  }),
  "daemon": ({ "Durgoroth", }),
  "elf": ({ "Lisht", "Haven", }),
  "gnoll": ({ "Lisht" }),
  "halfling": ({ "Lloryk" }),
  "muezzin": ({ "Westwood" }),
  "dark-dwarf": ({ "Dalnairn" }),
  "lizardman": ({ "Gwonish" }),
  "goblin": ({ "Kresh" }),
  "goden": ({ "Keryth" }),
  "muezzin": ({ "Soleil" }),
  "nosferatu": ({ "Grymxoria" }),
  "kobold": ({ "Arcanith" }),
]);

#endif /* l_setup_h */
