#!/usr/bin/env bash
#
# write_play_page.sh -- write ONE lib's play.html + fluffos-boot.js into an
# already-assembled site directory that has that lib's <slug>.zip in it
# (from pack_lib_zip.sh). Deliberately cheap (plain template substitution,
# no rsync/zip work) and NOT cached: build_site.sh runs this unconditionally
# for every packable lib on every run, so editing
# scripts/web_shell_override/index.html (or this script) takes effect for
# the whole site immediately without invalidating any lib's (expensive)
# cached zip -- see pack_lib_zip.sh's header for why that split matters.
#
# Usage: scripts/write_play_page.sh <slug> <driver_dir> <shell_dir> <site_lib_dir>
#
#   <slug>          directory name under libs/
#   <driver_dir>    dir containing fluffos.js + fluffos.wasm (only validated
#                   here; the driver and the shared client scripts referenced
#                   by play.html live once at the site root, see the dedupe
#                   note in scripts/web_shell_override/index.html)
#   <shell_dir>     dir containing the web terminal index.html (in the
#                   release zip this is the same dir as the driver). When
#                   scripts/web_shell_override/index.html exists it is used
#                   as the page template INSTEAD -- see that file's own
#                   comments; the override must keep the patch anchors below.
#   <site_lib_dir>  the site's already-assembled libs/<slug>/ dir -- must
#                   already contain <slug>.zip (from pack_lib_zip.sh); this
#                   script adds play.html + fluffos-boot.js to it.

set -euo pipefail

SELF_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SELF_DIR/.." && pwd)

if [ $# -ne 4 ]; then
  echo "usage: $0 <slug> <driver_dir> <shell_dir> <site_lib_dir>" >&2
  exit 2
fi
SLUG=$1
DRIVER_DIR=$(cd "$2" && pwd)
SHELL_DIR=$(cd "$3" && pwd)
OUT=$4

LIB="$REPO_ROOT/libs/$SLUG"
[ -f "$DRIVER_DIR/fluffos.js" ] && [ -f "$DRIVER_DIR/fluffos.wasm" ] || {
  echo "error: driver not found in $DRIVER_DIR (need fluffos.js + fluffos.wasm)" >&2; exit 1; }
[ -f "$SHELL_DIR/index.html" ] || { echo "error: $SHELL_DIR/index.html not found" >&2; exit 1; }
[ -f "$OUT/$SLUG.zip" ] || { echo "error: $OUT/$SLUG.zip missing -- run pack_lib_zip.sh first" >&2; exit 1; }

SHELL_PAGE="$SHELL_DIR/index.html"
if [ -f "$SELF_DIR/web_shell_override/index.html" ]; then
  SHELL_PAGE="$SELF_DIR/web_shell_override/index.html"
fi

# --- boot config -------------------------------------------------------
# keepDirs: directories wasm_keep_dirs.txt records for this slug -- dirs
# that exist on a booted local tree but hold no git-tracked files, so the
# zip (built from a checkout) lacks them entirely.  Many libs'
# log_file()/write_file()/save_object() calls throw -- silently aborting
# the caller -- on a missing directory at any depth (AGENTS.md's
# missing-directory-swallows-errors pattern), so zip-loader.js must
# recreate these (plus /work/log unconditionally) before boot.
KEEP_DIRS_JSON=$(python3 -c "
import json, sys
slug = sys.argv[1]
keep_list = sys.argv[2]
dirs = []
try:
    with open(keep_list) as f:
        for line in f:
            s, rel = line.rstrip('\n').split('\t')
            if s == slug:
                dirs.append(rel)
except FileNotFoundError:
    pass
print(json.dumps(dirs))
" "$SLUG" "$SELF_DIR/wasm_keep_dirs.txt")

cat > "$OUT/fluffos-boot.js" <<EOF
// Generated by scripts/write_play_page.sh -- consumed by play.html.
window.FLUFFOS_BOOT = {
  mount: "/mudlib",
  config: "config.fluffos",
};
window.FLUFFOS_ZIP_BOOT = {
  slug: $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$SLUG"),
  zip: $(python3 -c 'import json,sys; print(json.dumps(sys.argv[1] + ".zip"))' "$SLUG"),
  mount: "/mudlib",
  keepDirs: $KEEP_DIRS_JSON,
};
EOF

# --- per-lib play page: patched copy of the web terminal -----------------
# Path patches (MUST all apply -- fail loudly if the upstream page changed):
#   vendor/, telnet.js, fluffos.js -> ../_driver/...
#   locateFile: .wasm from ../_driver/, everything else local.
# Cosmetic patches (title/h1 -> game name) are best-effort.
# (The zip-loader/persist/save-export/tab-lock/sync-hook script tags already
# reference ../_driver/ directly in the template -- see index.html -- so
# they need no per-lib patching here.)
GAME_NAME=$(sed -n 's/^# *//p' "$LIB/README.md" 2>/dev/null | head -1)
[ -n "$GAME_NAME" ] || GAME_NAME=$SLUG
export SLUG GAME_NAME
python3 - "$SHELL_PAGE" "$OUT/play.html" <<'PYEOF'
import os, sys
src, dst = sys.argv[1], sys.argv[2]
html = open(src, encoding='utf-8').read()
slug = os.environ['SLUG']
name = os.environ['GAME_NAME']

required = [
    ('href="vendor/xterm.css"', 'href="../_driver/vendor/xterm.css"'),
    ('<script src="vendor/xterm.js"></script>',
     '<script src="../_driver/vendor/xterm.js"></script>'),
    ('<script src="vendor/addon-fit.js"></script>',
     '<script src="../_driver/vendor/addon-fit.js"></script>'),
    ('<script src="telnet.js"></script>',
     '<script src="../_driver/telnet.js"></script>'),
    ('<script src="fluffos.js"></script>',
     '<script src="../_driver/fluffos.js"></script>'),
    ('locateFile: (f) => f,',
     "locateFile: (f) => f.endsWith('.wasm') ? '../_driver/' + f : f,"),
]
for old, new in required:
    if html.count(old) != 1:
        sys.exit('error: pattern not found exactly once in %s: %r\n'
                 '(the release web terminal page changed; update '
                 'scripts/write_play_page.sh)' % (src, old))
    html = html.replace(old, new)

cosmetic = [
    ('<title>FluffOS — WebAssembly driver</title>',
     '<title>%s — FluffOS WASM</title>' % name),
    ('<h1>FluffOS / WebAssembly</h1>',
     '<h1><a href="./" style="color:inherit;text-decoration:none" '
     'title="返回介绍页">«</a> %s</h1>' % name),
]
for old, new in cosmetic:
    if html.count(old) == 1:
        html = html.replace(old, new)
    else:
        print('warning: cosmetic pattern not found, skipped: %r' % old,
              file=sys.stderr)

open(dst, 'w', encoding='utf-8').write(html)
PYEOF

echo "wrote play page for $SLUG -> $OUT/play.html"
