#define DIR_PLANES  "/domains/planes/"
#define DIR_VIRT  DIR_PLANES + "virtual/"
#define FIRST_PLANE DIR_VIRT + "first/"
#define SECOND_PLANE DIR_VIRT + "second/"
#define THIRD_PLANE DIR_VIRT + "third/"
#define PLANE_NPC DIR_PLANES + "npc/"
#define PLANE_OBJ DIR_PLANES + "obj/"
#define PLANE_CASTLE  DIR_PLANES + "castles/"
#define FIRE_PLANE  DIR_VIRT + "fire/"
