mapping allloca=([
    "扬州城":({"/d/city/","beidajie1","beidajie2","beimen","beiyin1",
               "guangchang","houyuan","jiaowai8","kedian","kedian2",
               "kedian3","jiaowai3","lichunyuan","lichunyuan2","meigui",
               "mishi","ml1","ml2","ml3","ml4","ml5","ml6","ml7",
               "mudan","nandajie1","nandajie2","nanmen","neizhai",
               "pomiao","youju","qianzhuang","shuyuan","shuyuan2",
               "ximen","jiaowai1","jiaowai2","beidajie2","xidajie1","xidajie2",
               "ximen","xiting","xixiang","bingyindamen","spirit","bingyin",
               "yamen","yaopu","yaopuls","ymzhengting","zahuopu","zhengting",
               "zuixianlou","zuixianlou2","zxlpath",
             }),
/*
  "泉洲" :({"/d/quanzhou/","beimen","haigang","houyuan","jiaxing",
              "jxnanmen","laozhai","liang","midao","mishi","nanhu","nanhu1","nanmen",
              "qzroad1","qzroad2","qzroad3","qzroad4","qzroad5","tieqiang","well",
              "xijie","yanyu","zahuopu","zhongxin",
             }),
*/
   "大理城" : ({"/d/dali/","tusifu","guangchang",
             "sheguta","tusimentang","xidajie1","xidajie2","xidajie3","dongdajie1",
             "tusiyishi","paifang",
             "tusihouting",}),
    "北京城":({"/d/city2/","alley1","alley2","alley3","andao1","andao10",
               "andao2","andao3","andao4","andao5","andao6","andao7","andao8",
               "andao9","anding","aobai1","aobai10","aobai11","aobai12","aobai2",
               "aobai3","aobai4","aobai5","aobai6","aobai7","aobai8","aobai9",
               "bingqiku","bingyin1","bingyin2","bridge","bridge2","bridge3","ceting",
               "chaguan","chaoyan1","chaoyan2","chaoyang","dangpu","datiepu","dating",
               "daxiao","daxiao2","di_an1","di_an2","di_an3","di_an4","di_anmen",
               "dongcha1","dongcha2","dongchangdamen","dongmen","duchang","duchang2",
               "duchang1","duchang2","eproom","fotang","guancai1","guancai2","haigang",
               "hbridge","houtai","huichunt","huichunt","jiulou1","jiulou2","kang1",
               "kang2","kang3","kedian","kedian1","kedian2","kedian3","kedian4",
               "lab","lilishi","mapeng","mianguan","nandaj1","nandaj2","neishi",
               "neitang","nproom","qianzhua","qishi","road1","road10","road2","road3",
               "road4","road5","road6","road7","road8","road9","shaizi-room","shufang",
               "shuyuan","shuyuan2","sproom","stage","tian_anm","tingyu","tuzai","wangfu1",
               "wangfu2","wangfu3","wenmiao","wproom","wuchang","wuqiku","xiaotan","xiaoyuan",
               "xichang1","xichang2","xichangdamen","xidan","xidan1","ximen","ximenwai",
               "xisi","xisi2","xiyuan","yihongyu","yongding","zahuopu","zhengmen","zhuang1",
               "zhuang2","zhuang3","zhuang4","zhuang5","zhuang6","zhuang7","zhuang8","zhuang9",
               "zhulin1","zhulin2","zhulin3","zhulin4","zhulin5",
                }),
"白驼山":({"/d/baituo/","bridge","cao1","cao2","caomeide","caoping","cave","cave1","cedong",
               "chaifang","changlang","chufang","damen","datiepu","dating","dongjie",
               "dongkou","dongnei","fang","fende","gebi","guangchang","houmen","houyuan",
               "huayuan","jiudian","liangong","menlang","midao","mumen","neishi","nongshe",
               "restroom","room1","room2","room3","shanlu","shanlu1","shijie","shulin",
               "shulin1","storeroom","tuyuan","wuqiku","xiaolu1","xiaolu2","xiaolu3",
               "xiaolu4","xijie","ximen","yaofang","yuanzi","zhailuo","zhulin","zhuyuan",
                }),
"灵蹴宫":({"/d/lingjiu/","biguan","caifeng","changl1","changl10","changl11",
               "changl12","changl13","changl14","changl15","changl2","changl3",
               "changl4","changl5","changl6","changl7","changl8","changl9","chufang",
               "daban","dadao1","dadao2","damen","dating","huayuan","jian","liangong",
               "men1","men2","men3","shanjiao","shufang","wuqiku","xianchou",
               "xiaodao1","xiaodao2",   
             }),


"华山" :({"/d/huashan/","baichi","bingqifang","buwei1","buwei2","buwei3",
                "canglong","changlang","chaopath1","chaopath2","chaoyang","chengxiang","chufang","doctorroom",
                "garden","houyuan","huixinshi","husun","jiashan","jinsuo","lianpath1",                         "lianpath2","luoyan","path1","pingdi","pingxinshi",
                "qingke","qunxiangyuan","sgyhole","sgyhole1","shaluo",
                "shangtianshi","shangu","sheshen","shufang","siguoya",
                "songlin1","songlin2","songlin3","songlin4","square2",
                "xiaolu2","xiaowu","xiuxishi","xuanya","yunmen",
                "yuntai","yunupath1","yunu","yunuci","yunupath1",
                "yunupath2","yuquan","zhandao","zhenyue","ziqitai",
                 }),
"逍遥派邻近":({"/d/xiaoyao/","bingqif.c","damen.c","fangjian1.c","fangjian2.c","gudi","hubian",
               "liangong","midao1","midao2","midao3","mubanlu","muwu1","muwu2","muwu3.c","pubu",
               "qingcaop","shantang","shidong","shiji1","shiji2","shiji3","shishi1","shishi2",
               "shishi3.c","shishi4.c","shishi5.c","shulin1.c","shulin2.c","shulin3.c","tongmen","xiaodao1",
               "xiaodao2","xiaodao3","xiaodao4","xiaodao5","xiuxis","yandong","yanfeng",}),


"五毒教" :({"/d/wudujiao/","baidu1","baidu2","beiyuan","bianzhai1","bianzhai2",
                "bianzhai3","cun1","cun2","cun3","cun4","cun5","cun6","cun7",
                "cun8","cun9","huating1","huating2","huating3","milin1","milin2",
                "milin3","milin4","milin5","milin6","milin7","milin8","minju1","minju2",
                "minju3","minju4","minju5","minju6","minju7","minju8",
                "st4","st5","st6","st7","st8","wdsl1","wdsl2","wdsl3","wdsl4","wdsl5",
                "wdsl6","wdsl7","wdsl8",
             }),
              
     "华山村":({"/d/village/","alley1","alley2","bighouse1","bighouse2","eexit","ehouse1","ehouse2",
                 "eroad1","eroad2","eroad3","hsroad1","hsroad2","hsroad3","nwhouse","nwroad1",
                 "nwroad2","sexit.c","shack","shop","shouse","smithy1","smithy2","square","sroad1",
           "sroad2","sroad3","sroad4","temple1","temple2","wexit",}),
        
    "北京城外":({"/d/city2/","road10","road9","road8","road7","road6","road5",
               "road4","road3","road2","road1","zhuang1","zhuang2","zhuang3","zhuang4",
               "haigang",}),
     ]);

