#define FOREST "/realms/arathorn/area/forest/"
#define FOREST_OBJ "/realms/arathorn/area/forest/obj/"
#define FOREST_NPC "/realms/arathorn/area/forest/npc/"
#define FOREST_ROOM "/realms/arathorn/area/forest/room/"
#define BEORN_ROOM "/domains/southern_coast/areas/beornwulf_keep/room/"
#define BEORNWULF "/domains/southern_coast/areas/beornwulf_keep/"
#define BEORN_NPC "/domains/southern_coast/areas/beornwulf_keep/npc/"
#define BEORN_OBJ "/domains/southern_coast/areas/beornwulf_keep/obj/"
