#define WESTWOOD_DIR  "/domains/westwood"
#define VIRTUAL       WESTWOOD_DIR + "/virtual/"
#define START         "/domains/southern_coast/virtual/havenroad/-20,0"
#define W_NPC         VIRTUAL + "npc/"
#define W_OBJ         VIRTUAL + "obj/"
#define S_ROOM        WESTWOOD_DIR + "/towns/soleil/room/"
#define R_OBJ         WESTWOOD_DIR + "/areas/rooklair/obj/"
#define V_ROOM        VIRTUAL + "westwood/"
#define C_ROOM        WESTWOOD_DIR + "/areas/castle/room/"
