#ifndef s_save_h
#define s_save_h

#include "dirs.h"

#define SAVE_ADVERBS       DIR_SAVE "/adverbs"
#define SAVE_ALCHEMY       DIR_SAVE "/alchemy"
#define SAVE_BANISH        DIR_SAVE "/banish"
#define SAVE_BOXES         DIR_SAVE "/boxes/"
#define SAVE_BUGS          DIR_SAVE "/bugs"
#define SAVE_CHARACTER     DIR_SECURE_SAVE "/character"
#define SAVE_CHAT          DIR_SAVE "/chat"
#define SAVE_CHAT_HIST     DIR_SAVE "/chathist"
#define SAVE_CENSOR        DIR_SAVE "/censor"
#define SAVE_CLAN          DIR_SAVE "/clans"
#define SAVE_CLASSES       DIR_SAVE "/classes"
#define SAVE_ECONOMY       DIR_SAVE "/economy"
#define SAVE_ESTATES       DIR_SAVE "/estates"
#define SAVE_EVENTS        DIR_SAVE "/events"
#define SAVE_GOSSIP        DIR_GOSSIP "/gossip"
#define SAVE_GUILD         DIR_SAVE "/guild"
#define SAVE_INET          DIR_SECURE_SAVE "/inet"
#define SAVE_INTERMUD      DIR_SAVE "/intermud"
#define SAVE_LANGUAGES     DIR_SAVE "/languages"
#define SAVE_LOOT          DIR_SAVE "/loot"
#define SAVE_MAILQUEUE     DIR_DATA "/mailqueue"
#define SAVE_NAMESERVER    DIR_SAVE "/network"
#define SAVE_NOTIFY        DIR_SAVE "/notify"
#define SAVE_PLANETS       DIR_SAVE "/planets"
#define SAVE_PSHOPS        DIR_SAVE "/pshops/"
#define SAVE_PHOUSES       DIR_SAVE "/phouses/"
#define SAVE_QUESTS        DIR_SECURE_SAVE "/quests"
#define SAVE_QUOTES        DIR_SAVE "/quotes"
#define SAVE_PLAYER_LIST   DIR_SAVE "/player_list"
#define SAVE_POLITICS      DIR_SECURE_SAVE "/politics"
#define SAVE_RACES         DIR_SAVE "/races"
#define SAVE_SERVICES      DIR_SAVE "/services"
#define SAVE_SETUP         DIR_SAVE "/setup"
#define SAVE_SKILLS        DIR_SAVE "/skills"
#define SAVE_SOUL          DIR_SAVE "/soul"
#define SAVE_UNIQUE        DIR_SAVE "/unique"
#define SAVE_VEHICLES      DIR_SAVE "/vehicles"
#define SAVE_VOTES         DIR_SAVE "/votes"
#define SAVE_WEATHER       DIR_SAVE "/weather"

#endif /* s_save_h */
