// stuffs for xx task

mapping *stuffs = ({ 
        ([      "quest":                "雪藤",
                "obj_id":               "xue teng",
                "exp_bonus":            200,
                "pot" :                 80,
        ]),
        ([      "quest":                "练心石",
                "obj_id":               "lianxin shi",
                "exp_bonus":            170,
                "pot" :                 80,
        ]),
        ([      "quest":                "摩诃僧诋律",
                "obj_id":               "moheseng diyu",
                "exp_bonus":            170,
                "pot" :                 80,
        ]),
        ([      "quest":                "蟒蛇皮",
                "obj_id":               "mangshe pi",
                "exp_bonus":            350,
                "pot" :                 120,
        ]),
        ([      "quest":                "银索",
                "obj_id":               "yin suo",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),
        ([      "quest":                "玉竹棒",
                "obj_id":               "yuzhu bang",
                "exp_bonus":            400,
                "pot" :                 175,
        ]),       
        ([      "quest":                "铁指环",
                "obj_id":               "zhi huan",
                "exp_bonus":            250,
                "pot" :                 75,
        ]),
        ([      "quest":                "白菊花",
                "obj_id":               "bai juhua",
                "exp_bonus":            99,
                "pot" :                 43,
        ]),
        ([      "quest":                "金孔雀",
                "obj_id":               "jin kongque",
                "exp_bonus":            102,
                "pot" :                 43,
        ]),
        ([      "quest":                "莺羽黄",
                "obj_id":               "yin yuhuang",
                "exp_bonus":            106,
                "pot" :                 33,
        ]),                               
        ([      "quest":                "虎皮",
                "obj_id":               "hu pi",
                "exp_bonus":            100,
                "pot" :                 35,
        ]),
        ([      "quest":                "斗转星移秘籍",
                "obj_id":               "douzhuan xingyi",
                "exp_bonus":            75,
                "pot" :                 23,
        ]),
        ([      "quest":                "三冈识略",
                "obj_id":               "shi lue",
                "exp_bonus":            70,
                "pot" :                 30,
        ]),
        ([      "quest":                "九环锡杖",
                "obj_id":               "jiuhuan xizhang",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),
        ([      "quest":                "熊掌",
                "obj_id":               "xiong zhang",
                "exp_bonus":            150,
                "pot" :                 70,
        ]),              
        ([      "quest":                "内功心法",
                "obj_id":               "force book",
                "exp_bonus":            80,
                "pot" :                 24,
        ]),
        ([      "quest":                "珊瑚金",
                "obj_id":               "shanhu jin",
                "exp_bonus":            240,
                "pot" :                 70,
        ]),
        ([      "quest":                "玉楼春",
                "obj_id":               "yu louchun",
                "exp_bonus":            86,
                "pot" :                 33,
        ]),
        ([      "quest":                "桃花菊",
                "obj_id":               "tao huaju",
                "exp_bonus":            118,
                "pot" :                 75,
        ]),                     
        ([      "quest":                "天王护心丹",
                "obj_id":               "huxin dan",
                "exp_bonus":            90,
                "pot" :                 30,
        ]),
        ([      "quest":                "黑玉镯",
                "obj_id":               "yu zhuo",
                "exp_bonus":            220,
                "pot" :                 100,
        ]),
        ([      "quest":                "野菊花",
                "obj_id":               "ye juhua",
                "exp_bonus":            102,
                "pot" :                 42,
        ]),
        ([      "quest":                "药理经",
                "obj_id":               "yaoli jing",
                "exp_bonus":            90,
                "pot" :                 50,
        ]),
        ([      "quest":                "玉洞黑石丹",
                "obj_id":               "heishi dan",
                "exp_bonus":            60,
                "pot" :                 30,
        ]),
        ([      "quest":                "铜钥匙",
                "obj_id":               "tong yaoshi",
                "exp_bonus":            123,
                "pot" :                 42,
        ]),
        ([      "quest":                "铁焰令",
                "obj_id":               "tieyan ling",
                "exp_bonus":            100,
                "pot" :                 30,
        ]),     
        ([      "quest":                "太极拳经",
                "obj_id":               "taiji quanjing",
                "exp_bonus":            130,
                "pot" :                 30,
        ]),
          ([      "quest":                "『明教简史』",
                "obj_id":               "book",
                "exp_bonus":            60,
                "pot" :                 20,
        ]),
        ([      "quest":                "肘後备急方",
                "obj_id":               "ji fang",
                "exp_bonus":            50,
                "pot" :                 10,
        ]),

        ([      "quest":                "回阳玉龙膏",
                "obj_id":               "yulong san",
                "exp_bonus":            90,
                "pot" :                 35,
        ]),
        ([      "quest":                "玉灵散",
                "obj_id":               "yuling san",
                "exp_bonus":            90,
                "pot" :                 35,
        ]),
        ([      "quest":                "碧水剑",
                "obj_id":               "bishui jian",
                "exp_bonus":            280,
                "pot" :                 70,
        ]),
        ([      "quest":                "玉真散",
                "obj_id":               "yuzhen san",
                "exp_bonus":            90,
                "pot" :                 35,
        ]),
        ([      "quest":                "踏雪无痕",
                "obj_id":               "shoes",
                "exp_bonus":            70,
                "pot" :                 20,
        ]),
        ([      "quest":                "天神篇",
                "obj_id":               "tianshen pian",
                "exp_bonus":            91,
                "pot" :                 23,
        ]),
        ([      "quest":                "归元丹",
                "obj_id":               "guiyuan dan",
                "exp_bonus":            70,
                "pot" :                 25,
        ]),
        ([      "quest":                "易经",
                "obj_id":               "yi jing",
                "exp_bonus":            100,
                "pot" :                 50,
        ]),
        ([      "quest":                "黄鹤翎",
                "obj_id":               "huang heling",
                "exp_bonus":            123,
                "pot":                  46,
        ]),
        ([      "quest":                "龙神篇",
                "obj_id":               "longshen pian",
                "exp_bonus":            82,
                "pot":                  35,
        ]),         
        ([      "quest":                "白虹剑",
                "obj_id":               "baihong sword",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),
        ([      "quest":                "黄金双铙",
                "obj_id":               "huangjin nao",
                "exp_bonus":            330,
                "pot" :                 90,
        ]),
        ([      "quest":                "夜叉篇",
                "obj_id":               "yecha pian",
                "exp_bonus":            82,
                "pot":                  36,
        ]),
        ([      "quest":                "乾达婆篇",
                "obj_id":               "qiandapo pian",
                "exp_bonus":            76,
                "pot":                  23,
        ]),
        ([      "quest":                "阿修罗篇",
                "obj_id":               "axiuluo pian",
                "exp_bonus":            103,
                "pot":                  32,
        ]),
        ([      "quest":                "迦楼罗篇",
                "obj_id":               "jialouluo pian",
                "exp_bonus":            104,
                "pot":                  31,
        ]),
        ([      "quest":                "紧那罗篇",
                "obj_id":               "jinnaluo pian",
                "exp_bonus":            106,
                "pot":                  34,
        ]),
        ([      "quest":                "摩呼罗迦篇",
                "obj_id":               "mohuluojia pian",
                "exp_bonus":            98,
                "pot":                  33,
        ]),
        ([      "quest":                "紫金袈裟",
                "obj_id":               "zijin jiasha",
                "exp_bonus":            200,
                "pot" :                 80,
        ]),
        ([      "quest":                "金龙鞭",
                "obj_id":               "jinlong bian",
                "exp_bonus":            250,
                "pot" :                 50,
        ]), 
        ([      "quest":                "伏魔金铙",
                "obj_id":               "fumo nao",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),  
        ([      "quest":                "斩妖金铙",
                "obj_id":               "zhanyao nao",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),           
        ([      "quest":                "道德经「下卷」",
                "obj_id":               "daode jing",
                "exp_bonus":            50,
                "pot" :                 25,
        ]),        
        ([      "quest":                "碧玉剑",
                "obj_id":               "biyu jian",
                "exp_bonus":            230,
                "pot" :                 80,
        ]),
        ([      "quest":                "瑶琴",
                "obj_id":               "yao qin",
                "exp_bonus":            60,
                "pot" :                 30,
        ]),
        ([      "quest":                "斑竹棍",
                "obj_id":               "banzhu gun",
                "exp_bonus":            300,
                "pot" :                 100,
        ]),              
        ([      "quest":                "天山雪莲",
                "obj_id":               "xuelian",
                "exp_bonus":            200,
                "pot" :                 90,
        ]),                
        ([      "quest":                "金刚罩",
                "obj_id":               "jingang zhao",
                "exp_bonus":            350,
                "pot" :                 120,
        ]),
        ([      "quest":                "铁罗汉",
                "obj_id":               "iron luohan",
                "exp_bonus":            150,
                "pot" :                 50,
        ]),        
        ([      "quest":                "银匕首",
                "obj_id":               "yin bishou",
                "exp_bonus":            140,
                "pot" :                 50,
        ]),
        ([      "quest":                "灰狼皮",
                "obj_id":               "langpi",
                "exp_bonus":            100,
                "pot" :                 60,
        ]),
        ([      "quest":                "太极十三势",
                "obj_id":               "taiji shi",
                "exp_bonus":            120,
                "pot" :                 40,
        ]),
        ([      "quest":                "美人红",
                "obj_id":               "meiren hong",
                "exp_bonus":            89,
                "pot":                  25,
        ]),        
        ([      "quest":                "金匕首",
                "obj_id":               "jin bishou",
                "exp_bonus":            160,
                "pot" :                 50,
        ]),
        ([      "quest":                "落第秀才",
                "obj_id":               "luodi xiucai",
                "exp_bonus":            68,
                "pot" :                 25,
        ]),
        ([      "quest":                "金蛇剑",
                "obj_id":               "jinshe sword",
                "exp_bonus":            320,
                "pot" :                 100,
        ]),
        ([      "quest":                "罗盘",
                "obj_id":               "luo pan",
                "exp_bonus":            150,
                "pot" :                 50,
        ]),       
        ([      "quest":                "八仙过海",
                "obj_id":               "baxian guohai",
                "exp_bonus":            62,
                "pot" :                 35,
        ]),
        ([      "quest":                "面罩",
                "obj_id":               "mian zhao",
                "exp_bonus":            160,
                "pot" :                 50,
        ]),       
        ([      "quest":                "黑龙鞭",
                "obj_id":               "bian",
                "exp_bonus":            150,
                "pot" :                 50,
        ]),              
        ([      "quest":                "十八学士",
                "obj_id":               "shiba xueshi",
                "exp_bonus":            58,
                "pot" :                 32,
        ]),
        ([      "quest":                "手绢",
                "obj_id":               "shou juan",
                "exp_bonus":            260,
                "pot" :                 80,
        ]),
        ([      "quest":                "拳谱",
                "obj_id":               "quan pu",
                "exp_bonus":            100,
                "pot" :                 25,
        ]),
        ([      "quest":                "黑索",
                "obj_id":               "hei suo",
                "exp_bonus":            400,
                "pot" :                 220,
        ]),
        ([      "quest":                "红装素裹",
                "obj_id":               "hongzhuang suguo",
                "exp_bonus":            74,
                "pot" :                 53,
        ]),
        ([      "quest":                "柔丝索",
                "obj_id":               "rousi suo",
                "exp_bonus":            240,
                "pot" :                 85,
        ]),
        ([      "quest":                "烈焰刀",
                "obj_id":               "lieyan dao",
                "exp_bonus":            280,
                "pot" :                 70,
        ]), 
        ([      "quest":                "琵琶",
                "obj_id":               "pi pa",
                "exp_bonus":            120,
                "pot" :                 30,
        ]),
        ([      "quest":                "断肠草",
                "obj_id":               "duanchang cao",
                "exp_bonus":            240,
                "pot" :                 100,
        ]), 
        ([      "quest":                "千年首乌",
                "obj_id":               "jujing dan",
                "exp_bonus":            250,
                "pot" :                 65,
        ]),
        ([      "quest":                "圣火令",
                "obj_id":               "shenghuo ling",
                "exp_bonus":            300,
                "pot" :                 100,
        ]),       
        ([      "quest":                "洗髓经",
                "obj_id":               "xisui",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),
        ([      "quest":                "大还丹",
                "obj_id":               "dahuan dan",
                "exp_bonus":            230,
                "pot" :                 70,
        ]),        
        ([      "quest":                "小还丹",
                "obj_id":               "xiaohuan dan",
                "exp_bonus":            200,
                "pot" :                 60,
        ]),       
        ([      "quest":                "『少林旅游图』",
                "obj_id":               "luyou tu",
                "exp_bonus":            70,
                "pot" :                 20,
        ]),
        ([      "quest":                "金蛇锥",
                "obj_id":               "jinshe zhui",
                "exp_bonus":            210,
                "pot" :                 90,
        ]),
        ([      "quest":                "抓破美人脸",
                "obj_id":               "mei renlian",
                "exp_bonus":            68,
                "pot" :                 36,
        ]),             
        ([      "quest":                "徐霞客游记",
                "obj_id":               "xuxiake youji",
                "exp_bonus":            90,
                "pot" :                 30,
        ]),     
        ([      "quest":                "银钥匙",
                "obj_id":               "yin yaoshi",
                "exp_bonus":            200,
                "pot" :                 80,
        ]),
        ([      "quest":                "软剑",
                "obj_id":               "ruan jian",
                "exp_bonus":            90,
                "pot" :                 30,
        ]),
        ([      "quest":                "金钥匙",
                "obj_id":               "jin yaoshi",
                "exp_bonus":            150,
                "pot" :                 70,
        ]),
        ([      "quest":                "真武剑",
                "obj_id":               "zhenwu jian",
                "exp_bonus":            330,
                "pot" :                 200,
        ]),
        ([      "quest":                "腰带",
                "obj_id":               "yao dai",
                "exp_bonus":            90,
                "pot" :                 20,
        ]),
        ([      "quest":                "棒法图解上册",
                "obj_id":               "stick book",
                "exp_bonus":            150,
                "pot" :                 90,
        ]),
        ([      "quest":                "线装经书",
                "obj_id":               "xianzhuang jingshu",
                "exp_bonus":            150,
                "pot" :                 90,
        ]),
        ([      "quest":                "寓意草",
                "obj_id":               "yuyi cao",
                "exp_bonus":            50,
                "pot" :                 10,
        ]),
        ([      "quest":                "科金镜赋集解",
                "obj_id":               "kejin jijie",
                "exp_bonus":            150,
                "pot" :                 70,
        ]),
        ([      "quest":                "痘疹定论",
                "obj_id":               "douzhen dinglun",
                "exp_bonus":            150,
                "pot" :                 70,
        ]),
        ([      "quest":                "博集稀痘方",
                "obj_id":               "boji xidoufang",
                "exp_bonus":            150,
                "pot" :                 70,
        ]),
        ([      "quest":                "金花",
                "obj_id":               "jin hua",
                "exp_bonus":            230,
                "pot" :                 90,
        ]),
        ([      "quest":                "冰魄神针",
                "obj_id":               "bingbo shenzhen",
                "exp_bonus":            300,
                "pot" :                 150,
        ]),
        ([      "quest":                "鹰爪手法",
                "obj_id":               "hand book",
                "exp_bonus":            120,
                "pot" :                 40,
        ]),
        ([      "quest":                "蟒蛇胆",
                "obj_id":               "mangshe dan",
                "exp_bonus":            250,
                "pot" :                 100,
        ]),
        ([      "quest":                "掌法诀要",
                "obj_id":               "zhangfa jueyao",
                "exp_bonus":            100,
                "pot" :                 50,
        ]),
        ([      "quest":                "天龙丹",
                "obj_id":               "tianlong dan",
                "exp_bonus":            130,
                "pot" :                 50,
        ]), 
        ([      "quest":                "指法诀要",
                "obj_id":               "zhifa jueyao",
                "exp_bonus":            100,
                "pot" :                 50,
        ]), 
        ([      "quest":                "金蛇秘籍",
                "obj_id":               "jinshe miji",
                "exp_bonus":            250,
                "pot" :                 100,
        ]),
        ([      "quest":                "天心解毒丹",
                "obj_id":               "tianxinjiedu dan",
                "exp_bonus":            350,
                "pot" :                 170,
        ]),
        ([      "quest":                "九雪碧云丹",
                "obj_id":               "jiuxuebiyun dan",
                "exp_bonus":            250,
                "pot" :                 70,
        ]),
        ([      "quest":                "禅刀精义",
                "obj_id":               "chandao",
                "exp_bonus":            100,
                "pot" :                 50,
        ]),
        ([      "quest":                "铁八卦",
                "obj_id":               "tie bagua",
                "exp_bonus":            200,
                "pot" :                 70,
        ]),
        ([      "quest":                "旋风扫叶腿图解",
                "obj_id":               "tuifa tujie",
                "exp_bonus":            100,
                "pot" :                 50,
        ]),
        ([      "quest":                "毒蟒胆",
                "obj_id":               "dumang dan",
                "exp_bonus":            200,
                "pot" :                 100,
        ]),
        ([      "quest":                "倚天剑",
                "obj_id":               "yitian jian",
                "exp_bonus":            400,
                "pot" :                 240,
        ]),
        ([      "quest":                "屠龙刀",
                "obj_id":               "tulong dao",
                "exp_bonus":            400,
                "pot" :                 240,
        ]),
        ([      "quest":                "玄铁剑",
                "obj_id":               "xuantie jian",
                "exp_bonus":            400,
                "pot" :                 200,
        ]),
        ([      "quest":                "雪蚕",
                "obj_id":               "xuecan",
                "exp_bonus":            250,
                "pot" :                 40,
        ]),
        ([      "quest":                "蓝玉钵",
                "obj_id":               "lanyu bo",
                "exp_bonus":            150,
                "pot" :                 40,
        ]),
        ([      "quest":                "小木鼎",
                "obj_id":               "mu ding",
                "exp_bonus":            150,
                "pot" :                 40,
        ]),
        ([      "quest":                "杖法图解",
                "obj_id":               "staff book",
                "exp_bonus":            120,
                "pot" :                 60,
        ]),
        ([      "quest":                "华山剑谱",
                "obj_id":               "sword book",
                "exp_bonus":            120,
                "pot" :                 60,
        ]),
        ([      "quest":                "乾坤一气袋",
                "obj_id":               "yiqi dai",
                "exp_bonus":            200,
                "pot" :                 80,
        ]),
        ([      "quest":                "玉玺",
                "obj_id":               "yu xi",
                "exp_bonus":            130,
                "pot" :                 60,
        ]),
        ([      "quest":                "七伤拳谱",
                "obj_id":               "qishang quanpu",
                "exp_bonus":            120,
                "pot" :                 50,
        ]),
});
