//      Tbh 具体制作
//      HBRED   HBGRN   HBYEL   HBBLU   HBMAG   HBCYN   HBWHT

#include <ansi.h>

mapping exert_names = ([

        "bahuang-gong/heal":			HIW"真气疗伤"NOR,
        "bahuang-gong/lifeheal":		HIW"他人疗伤"NOR,
        "bahuang-gong/powerup":		        HIW"唯我独尊"NOR,
        "beiming-shengong/beiming":             HIW"北    冥"NOR,
        "beiming-shengong/heal":		HIW"真气疗伤"NOR,
        "beiming-shengong/lifeheal":		HIW"他人疗伤"NOR,
        "beiming-shengong/xi":                  HIW"吸取内力"NOR,
        
        "bihai-chaosheng/cuidu":		HIW"催    毒"NOR,
        "bihai-chaosheng/heal":			HIW"真气疗伤"NOR,
        "bihai-chaosheng/lifeheal":		HIW"他人疗伤"NOR,
        "bihai-chaosheng/maze":			HIW"布 迷 阵"NOR,
        "bihai-chaosheng/play":			HIW"吹    箫"NOR,
        "bihai-chaosheng/qimen":		HIW"奇门八卦"NOR,
        
        "dulong-dafa/heal":			HIW"真气疗伤"NOR,
        "dulong-dafa/jiedu":			HIW"解    毒"NOR,
        "dulong-dafa/shougong":			CYN"收    功"NOR,
        "dulong-dafa/wudi":			HIR"无敌大法"NOR,
        
        "emei-jiuyang/heal":			HIW"真气疗伤"NOR,
        "emei-jiuyang/lifeheal":		HIW"他人疗伤"NOR,
        "emei-jiuyang/powerup":			HIY"峨嵋九阳功"NOR,
        
        "guiyuan-tunafa/heal":			HIY"真气疗伤"NOR,
        "guiyuan-tunafa/lifeheal":		HIY"他人疗伤"NOR,
        
        "hunyuan-yiqi/heal":			HIW"真气疗伤"NOR,
        "hunyuan-yiqi/lifeheal":		HIW"他人疗伤"NOR,
        "hunyuan-yiqi/roar":			HIY"狮 子 吼"NOR,
        
        "hunyuan-gong/jianmang":                MAG"剑　　芒"NOR,
        "hunyuan-gong/ningshen":                MAG"凝　　神"NOR,
        "hunyuan-gong/lifeforce":               MAG"治疗内伤"NOR,
        "hunyuan-gong/lifeheal":                MAG"疗　　伤"NOR,
        "hunyuan-gong/zixia":                   MAG"紫　　霞"NOR,
        
        "huntian-qigong/heal":			HIW"真气疗伤"NOR,
        "huntian-qigong/powerup":		HIW"混天气功"NOR,
        "huntian-qigong/tiangang":		HIW"混元天罡"NOR,        

        "huagong-dafa/heal":                    RED"真气疗伤"NOR,
        "huagong-dafa/huadu":                   RED"化　　毒"NOR,
        "huagong-dafa/huagong":                 RED"化　　功"NOR,
        "huagong-dafa/judu":                    RED"聚　　毒"NOR,
        "huagong-dafa/liaodu":                  RED"疗　　毒"NOR,
        
        "hamagong/hama":			HIY"蛤 蟆 功"NOR,
        "hamagong/heal":			HIW"真气疗伤"NOR,
        "hamagong/nizhuan":			HIW"逆    转"NOR,
        "hamagong/qudu":			HIW"驱    毒"NOR,
        
        "linji-zhuang/fengyun":			MAG"风    云"NOR,
        "linji-zhuang/riyue":			MAG"日    月"NOR,
        "linji-zhuang/tiandi":			HIY"天    地"NOR,
        "linji-zhuang/wuwo":			MAG"无    我"NOR,
        "linji-zhuang/yinyang":			HIW"阴    阳"NOR,
        "linji-zhuang/zhixin":			MAG"之    心"NOR,

        "longxiang-boruo/heal":			MAG"真气疗伤"NOR,
        "longxiang-boruo/longxiang":            MAG"龙象之力"NOR,
        "longxiang-boruo/shield":               MAG"真气护体"NOR,
        "longxiang-boruo/trans":		MAG"对方疗伤"NOR,
        "longxiang-boruo/yinyang":		MAG"阴阳大法"NOR,

        "jiuyang-shengong/chuangong":           RED"传　　功"NOR,
        "jiuyang-shengong/heal":                RED"真气疗伤"NOR,
        "jiuyang-shengong/lifeheal":		RED"他人疗伤"NOR,
        "jiuyang-shengong/powerup":             RED"九阳神功"NOR,
        "jiuyang-shengong/tougu":               RED"透 骨 针"NOR,
        "jiuyang-shengong/yinfeng":             RED"阴 风 刀"NOR,
        
        "jiuyin-zhengong/heal":			HIW"真气疗伤"NOR,
        "jiuyin-zhengong/jingheal":		HIB"真气疗精"NOR,
        "jiuyin-zhengong/lifeheal":		HIW"他人疗伤"NOR,
        "jiuyin-zhengong/yihun":		HIW"移魂大法"NOR,
        "jiuyin-zhengong/zongjue":		HIB"九阴总诀"NOR,
        
        "kurong-changong/heal":			HIW"真气疗伤"NOR,
        "kurong-changong/jiuchong":     	HIR"九 重 天"NOR,
        "kurong-changong/ku":         		YEL"枯字大法"NOR,
        "kurong-changong/liao":         	RED"疗    伤"NOR,
        "kurong-changong/roar":         	HIY"狮 子 吼"NOR,
        "kurong-changong/rong":       		HIY"荣字大法"NOR,
        
        "qiantian-yiyang/heal":			HIW"真气疗伤"NOR,
        "qiantian-yiyang/liao":			HIW"真气疗伤"NOR,
        "qiantian-yiyang/xinjing":		GRN"静心潜修"NOR,

        "shenghuo-shengong/chuangong":          RED"传　　功"NOR,
        "shenghuo-shengong/heal":		HIW"真气疗伤"NOR,
        "shenghuo-shengong/lifeheal":		HIW"他人疗伤"NOR,
        "shenghuo-shengong/tougu":              RED"透 骨 针"NOR,
        "shenghuo-shengong/yinfeng":            RED"阴 风 刀"NOR,
        
        "shenyuan-gong/heal":			HIW"真气疗伤"NOR,
        "shenyuan-gong/lifeheal":		HIW"他人疗伤"NOR,
        "shenyuan-gong/shenyuan":		HIY"神 元 功"NOR,
        
        "shenzhao-jing/heal":			HIW"真气疗伤"NOR,
        
        "songshan-qigong/jianqi":		GRN"运 剑 气"NOR,
        
        "tiangang-zhengqi/heal":		HIW"真气疗伤"NOR,
        "tiangang-zhengqi/lifeheal":		HIW"他人疗伤"NOR,
        "tiangang-zhengqi/powerup":		HIR"运 天 罡"NOR,
        
        "xiantian-gong/heal":			HIW"真气疗伤"NOR,
        "xiantian-gong/lifeheal":		HIW"他人疗伤"NOR,
        
        "xixing-dafa/heal":			HIW"真气疗伤"NOR,
        "xixing-dafa/lifeheal":			HIW"他人疗伤"NOR,
        "xixing-dafa/powerup":			HIR"吸心大法"NOR,
        "xixing-dafa/roar":			HIR"长空狂吼"NOR,
        "xixing-dafa/xijing":			HIR"吸    精"NOR,
        "xixing-dafa/xineili":			HIR"吸 内 力"NOR,
        "xixing-dafa/xiqi":			HIR"吸    气"NOR,
        
        "xuantian-wuji/heal":			HIW"真气疗伤"NOR,
        "xuantian-wuji/lifeheal":		HIW"他人疗伤"NOR,
        
        "yijin-jing/heal":			HIW"真气疗伤"NOR,
        "yijin-jing/jingang":			HIR"金刚不坏体神功"NOR,
        "yijin-jing/roar":			HIY"狮 子 吼"NOR,
        
        "yinyun-ziqi/cure":                     MAG"真气疗伤"NOR,
        "yinyun-ziqi/heal":			HIW"真气疗伤"NOR,
        "yinyun-ziqi/lifesave":                 MAG"鹤嘴劲点"NOR,
        "yinyun-ziqi/taiji":                    MAG"太　　极"NOR,
        "yinyun-ziqi/yinyun":                   MAG"氤氲内聚"NOR,  
        
        "yunu-xinjing/heal":			HIW"真气疗伤"NOR,
        "yunu-xinjing/hebi":			HIY"合    壁"NOR,
        "yunu-xinjing/xinjing":			HIY"心    经"NOR, 
        
        "zixia-gong/heal":			HIW"真气疗伤"NOR,
        "zixia-gong/lifeheal":			HIW"他人疗伤"NOR,
        "zixia-gong/lifeforce":			MAG"疗    伤"NOR,
        
]);

mapping perform_names = ([

        "anran-zhang/anran":			HIG"黯然"NOR,
        "anran-zhang/xiaohun":			HIG"销魂"NOR,
        "banruo-zhang/yipai":			RED"一拍两散"NOR,     
        "canglang-goufa/beauty":		MAG"美人三招"NOR,
        "canglang-goufa/hero":			HIR"英雄三招"NOR,
        "canhe-zhi/ci":				HIC"刺 字 诀"NOR,
        "cihang-bian/cibei":            	HIY"我佛慈悲"NOR,
        "chongling-jian/hebi":          	YEL"双剑合璧"NOR,
        "chousui-zhang/biyan":          	GRN"碧　　焰"NOR,
        "chousui-zhang/huoqiang":       	HIR"火　　墙"NOR,
        "chousui-zhang/huoqiu":         	RED"火　　球"NOR,
        "chousui-zhang/yinhuo":         	HIY"银　　火"NOR,
        "dafumo-quan/fumo":			HIY"伏   魔"NOR,
        "dafumo-quan/posha":			HIY"破   煞"NOR,
        "dafumo-quan/qiankun":			HIY"乾坤一击"NOR,
        "dagou-bang/chan":			HIY"缠字诀"NOR,
        "dagou-bang/linglong":			HIY"玲珑棒诀"NOR,
        "dagou-bang/wugou":			HIY"天下无狗"NOR,
        "damo-jian/sanjue":			RED"达摩三绝"NOR,   
        "dashou-yin/tianyin":           	HIG"阿修罗天印"NOR,
        "douzhuan-xingyi/xingyi":       	HIC"星移斗转"NOR,
        "douzhuan-xingyi/bishen":       	HIC"以彼之道还施彼身"NOR,
        "duanjia-jianfa/fenglei":		HIY"风雷四击"NOR,
        "dugu-jiujian/kuangfeng":       	HIG"狂风卷地"NOR,
        "dugu-jiujian/po":			HIG"破 气 式"NOR,
        "duoming-jinhua/huayu":         	HIW"满天花雨"NOR,
        "fanliangyi-dao/hebi":          	HIC"合　　璧"NOR,
        "fanliangyi-dao/sanshen":		HIC"华岳三神峰"NOR,
        "fengmo-zhang/feizhang":		HIR"飞    杖"NOR,
        "hanbing-mianzhang/xixue":      	HIC"吸血青蝠"NOR,
        "hanbing-shenzhang/hanbing":		BLU"寒冰真气"NOR,
        "hansha-sheying/xiangyin":		HIY"心心相印"NOR,
        "huagu-mianzhang/bujue":		HIY"绵绵不绝"NOR,
        "huagu-mianzhang/huagu":		HIY"化    骨"NOR,
        "huagu-mianzhang/puhuo":		HIR"飞蛾扑火"NOR,
        "huashan-jianfa/jianmang":		HIC"剑     芒"NOR,
        "huashan-jianfa/jianzhang":		HIR"剑掌五连环"NOR,
        "huashan-jianfa/lianhuan":      	HIR"夺命三仙剑"NOR,
        "huashan-jianfa/wudui":			HIC"无双无对"NOR,
        "huifeng-bian/huixuan":			HIY"回旋十三式"NOR,
        "huifeng-jian/jue":			HIW"绝   剑"NOR,
        "huifeng-jian/liaoyuan":		HIW"燎原百击"NOR,
        "huifeng-jian/mie":			HIW"灭    剑"NOR,
        "hunyuan-zhang/wuji":			HIR"混元无极"NOR,
        "huoyan-dao/fen":               	RED"　 焚　 "NOR,
        "lanhua-shou/fuxue":			HIC"兰花拂穴"NOR,
        "liangyi-jian/sanqiu":			CYN"一日三秋"NOR,
        "lietian-fu/lihun":			RED"离 魂 斩"NOR,
        "lieyan-dao/shenghuo":          	HIC"圣火光明"NOR,
        "lingshe-bianfa/chan":			HIY"金蛇缠丝"NOR,
        "lingshe-bianfa/sandou":		HIY"灵蛇三抖"NOR,
        "liuhe-daofa/sancai":			CYN"奇门三才刀"NOR,
        "liumai-shenjian/ciqu":			MAG"此去彼来"NOR,
        "liuyang-zhang/jie":            	HIC"解生死符"NOR,
        "liuyang-zhang/zhong":          	MAG"种生死符"NOR,
        "longzhua-gong/canyun":			RED"风卷残云"NOR,
        "luoying-zhang/bading":			HIW"拔附骨钉"NOR,
        "luoying-zhang/fugu":			HIR"附 骨 钉"NOR,
        "luoying-zhang/kuangfeng":		HIG"狂风绝技"NOR,
        "luoying-zhang/pikong":			HIB"劈 空 掌"NOR,
        "luoying-zhang/shenjian":		CYN"桃花影里飞神剑"NOR,
        "jieshou-jiushi/foguang":		HIY"佛光普照"NOR,
        "jingang-quan/fumo":			HIR"金刚伏魔"NOR,
        "jinshe-jianfa/kuangwu":        	HIR"金蛇狂舞"NOR,
        "jinshe-zhuifa/sheying":		HIR"蛇影万道"NOR,
        "jiuyin-baiguzhua/jiuyin":		RED"九阴三绝爪"NOR,
        "jiuyin-shenzhua/sanjue":		RED"九阴三绝抓"NOR,
        "juehu-shou/juehu":             	BLU"绝　　户"NOR,
        "kongming-quan/luanwu":			RED"群魔乱舞"NOR,
        "kongmingquan/chan":			CYN"缠 字 诀"NOR,
        "kongmingquan/kongqianjiuhou":		CYN"空前绝后"NOR,
        "kunlun-zhang/diezhang":		HIG"昆仑叠掌"NOR,
        "murong-daofa/daoying":			HIR"刀 影 掌"NOR,
        "murong-jianfa/lianhuan":		MAG"剑指连环"NOR,
        "murong-jianfa/qixing":			HIB"剑转七星"NOR,
        "murong-jianfa/qixingplus":		HIB"七剑转七星"NOR,
        "nianhua-zhi/fuxue":			HIY"拂穴绝技"NOR,
        "pangen-cuojie/pifeng":			HIR"乱 披 风"NOR,
        "pixie-jianfa/cimu":            	BLU"飞针刺目"NOR,
        "pixie-jianfa/feiying":         	BLU"葵花飞影术"NOR,
        "pixie-jianfa/jue":             	BLU"绝 命 针"NOR,
        "poyu-quan/leidong":			MAG"雷动九天"NOR,
        "qiankun-danuoyi/xu":           	BLU"蓄 字 诀"NOR,
        "qiankun-danuoyi/yi":           	BLU"移 字 诀"NOR,
        "qianye-shou/qianshou":			HIY"千手如来"NOR,
        "qingxu-bian/fei":			HIB"龙凤双飞"NOR,
        "qingyan-zhang/liaorao":		HIY"烟雾缭绕"NOR,
        "qishang-quan/qishang":         	HIR"七伤总诀"NOR,
        "quanzhen-jianfa/qixing":		HIW"七星绝命剑"NOR,
        "ranmu-daofa/fentian":			HIR"举火焚天"NOR,
        "ranmu-daofa/fenwo":			HIR"焚    我"NOR,
        "ranmu-daofa/fenxin":			HIR"焚 心 决"NOR,
        "riyue-bian/chanrao":			HIY"缠 绕 诀"NOR,
        "riyue-bian/fumoquan":			HIY"金刚伏魔圈"NOR,
        "riyue-bian/riyue":			HIC"日月神鞭"NOR,
        "ruying-suixingtui":			YEL"如影随形"NOR,
        "sanhua-zhang/sanhua":			HIW"四季散花"NOR,
        "sanyin-zhua/sanyin":           	BLU"三阴毒蛭抓"NOR,
        "shenghuo-lingfa/duo":          	HIM"夺 字 诀"NOR,
        "shenghuo-lingfa/ji":           	HIM"击 字 诀"NOR,
        "shenghuo-lingfa/tisha":        	HIM"踢　　沙"NOR,
        "shenghuo-lingfa/xinmo":        	HIM"心　　魔"NOR,
        "shenlong-tuifa/zhuiming":		HIY"神龙追命腿"NOR,
        "songshan-jian/feiwu":			BLU"飞    舞"NOR,
        "songyang-zhang/junji":			CYN"峻极神掌"NOR,
        "suibo-zhuliu/wuzhuan":			HIW"奇门五转"NOR,
        "suishangpiao/piao":			HIC"   飘  "NOR,
        "taiji-jian/chan":              	RED"缠 字 诀"NOR,
        "taiji-jian/lian":              	RED"连 字 诀"NOR,
        "taiji-jian/sanhuan":           	RED"三环套月"NOR,
        "taiji-jian/tongshou":          	RED"天地同寿"NOR,
        "taiji-quan/ji":                	RED"挤 字 诀"NOR,
        "taiji-quan/luanhuan":          	RED"乱 环 诀"NOR,
        "taiji-quan/zhen":              	RED"震 字 诀"NOR,
        "tanzhi-shentong/huayu":		CYN"漫天花雨"NOR,
        "tanzhi-shentong/lingxi":		CYN"灵犀一指"NOR,
        "tanzhi-shentong/shentong":		HIW"弹指神通"NOR,
        "tiangang-jian/qixinggongyue":		YEL"七星拱月"NOR,
        "tiangang-zhang/tiangang":		HIG"天    罡"NOR,
        "tianshan-zhang/feizhi":        	HIC"飞掷"NOR,
        "tianyu-qijian/san":			HIR"天女散花"NOR,
        "tiezhang-zhangfa/tianlei":		HIY"天 雷 气"NOR,
        "tiezhang-zhangfa/zhangdao":		YEL"掌刀绝技"NOR,
        "tiyunzong/zong":               	YEL"梯 云 纵"NOR,
        "wuhu-duanmendao/duan":			HIY"五虎断门刀"NOR,
        "xiangfu-lun/dazhuan":          	HIY"五轮大转"NOR,
        "xiangfu-lun/wushuai":          	HIY"天人五衰"NOR,
        "xianglong-zhang/hanglong":		HIC"亢龙有悔"NOR,
        "xianglong-zhang/paiyun":		HIY"排云双掌"NOR,
        "xianglong-zhang/xiao":			HIY"降 龙 啸"NOR,
        "xingyi-zhang/riyue":			HIG"日月同辉"NOR,
        "xingyi-zhang/xingdian":		HIW"星光点点"NOR,
        "xuanfeng-tui/kuangfeng":		HIG"狂风绝技"NOR,
        "xuantie-jianfa/haichao":		HIB"海潮汹涌"NOR,
        "xuanxu-daofa/luanhuan":        	RED"乱 环 诀"NOR,
        "xuedao-jing/jixue":            	HIR"祭血神刀"NOR,
        "xuedao-jing/shendao":          	HIR"神刀穿心"NOR,
        "yanxing-daofa/huanying":		HIY"幻    影"NOR,
        "yingou-bifa/caoshu":			HIM"草    书"NOR,
        "yingou-bifa/kaishu":			HIC"楷    书"NOR,
        "yingou-bifa/shigu":			HIY"石 鼓 文"NOR,
        "yinsuo-jinling/dian":			HIW"点    穴"NOR,
        "yinsuo-jinling/dianxue":		HIW"点 字 诀"NOR,
        "yinsuo-jinling/feng":			HIC"封    穴"NOR,
        "yinsuo-jinling/yufeng":		HIW"玉 蜂 针"NOR,
        "yiyang-zhi/ciqu":			MAG"此去彼来"NOR,
        "yiyang-zhi/liumai":			HIW"六脉神剑"NOR,
        "yiyang-zhi/sandie":			HIY"阳关三叠"NOR,
        "yizhi-chan/qiankun":           	HIY"一指乾坤"NOR,
        "yizhi-chan/wofo":              	HIW"皈依我佛"NOR,
        "youlong-shenfa/baibian":		HIY"神行百变"NOR,
        "youming-zhao/youming":			HIR"呼唤鬼魂"NOR,
        "yubi-jianfa/san":              	HIM"天女散花"NOR,
        "yubi-jianfa/shuangzhao":       	HIG"璧影双照"NOR,
        "yunu-jianfa/suxin":			HIW"玉女素心"NOR,        
        "yuxiao-jian/feiying":			HIW"飞    影"NOR,
        "yuxiao-jian/qimen":			HIG"奇门玉箫"NOR,
        "yuxiao-jian/yuxiao":			CYN"碧海潮生按玉箫"NOR,
        "zhemei-shou/tanmei":           	HIG"弹梅.落雪.散花香"NOR,
        "zhemei-shou/duo":              	HIW"空手入白刃"NOR,
        "zhemei-shou/zhemei":           	RED"折梅展"NOR,
        "zhenshan-mianzhang/bingdi":    	YEL"花开并蒂"NOR,
        "zhuihun-gou/luanpifeng":       	HIB"乱 披 风"NOR,
        "zui-gun/zuida":			HIY"八仙醉打"NOR,
        "zuibaxian/zuijiu":			GRN"八仙醉酒"NOR,

]);
