#include <ansi.h>
mapping *quest = ({
      (["short":                "飞天 厢房",
       "place" :              "/d/feitian/xiangfang",]), 
      (["short":                "飞天 厨房",
       "place" :              "/d/feitian/chufang",]), 
      (["short":                "飞天 后花园",
       "place" :              "/d/feitian/huayuan",]), 
      (["short":                "飞天 练武场",
       "place" :              "/d/feitian/lianwuchang",]), 
      (["short":                "飞天 后庭",
       "place" :              "/d/feitian/houting",]), 
      (["short":                "飞天 储藏室",
       "place" :              "/d/feitian/chucangshi",]), 
      (["short":                "飞天 药铺",
       "place" :              "/d/feitian/yaopu",]),   
      (["short":                "飞天 武器店",
       "place" :              "/d/feitian/wuqidian",]), 
      (["short":                "飞天 落人村",
       "place" :              "/d/feitian/luorencun",]), 
      (["short":                "飞天 长乐屋",
       "place" :              "/d/feitian/changlewu",]), 
      (["short":                "飞天 牛肉馆",
       "place" :              "/d/feitian/niurouguan",]), 
      (["short":                "飞天 京都警备署",
       "place" :              "/d/feitian/jingbeisu",]), 
      (["short":                "飞天 神古活心流大门",
       "place" :              "/d/feitian/damen",]), 
      (["short":                "飞天 前庭",
       "place" :              "/d/feitian/qianting",]), 
      (["short":                "飞天 修练室",
       "place" :              "/d/feitian/xiulianshi",]), 
      (["short":                "飞天 空地",
       "place" :              "/d/feitian/kongdi",]), 
      (["short":                "飞天 中庭",
       "place" :              "/d/feitian/zhongting",]), 
      (["short":                "飞天 玄关",
       "place" :              "/d/feitian/xuanguan",]), 
      (["short":                "飞天 走廊",
       "place" :              "/d/feitian/zoulang",]), 
      (["short":                "飞天 神古活心流",
       "place" :              "/d/feitian/daochang",]), 
      (["short":                "飞天 兵器室",
       "place" :              "/d/feitian/bingqishi",]), 
      (["short":                "飞天 厢房",
       "place" :              "/d/feitian/xiangfang",]), 
      (["short":                "飞天 厨房",
       "place" :              "/d/feitian/chufang",]), 
      (["short":                "飞天 后花园",
       "place" :              "/d/feitian/huayuan",]), 
      (["short":                "飞天 练武场",
       "place" :              "/d/feitian/lianwuchang",]), 
      (["short":                "飞天 后庭",
       "place" :              "/d/feitian/houting",]), 
      (["short":                "飞天 储藏室",
       "place" :              "/d/feitian/chucangshi",]), 
          });
mapping query_quest()
 {
 return quest[random(sizeof(quest))];
}

