#ifndef K_MARSH_H
#define K_MARSH_H
#define ITEMS "/wizards/wildflower/marsh/item/"
#define MOB "/wizards/wildflower/marsh/mob/"
#define ARM "/wizards/wildflower/marsh/arm/"
#define WEP "/wizards/wildflower/marsh/wep/"
#define ROOMS "/wizards/wildflower/marsh/room/"
#define BA  ROOMS "ba/"
#define CAVE  ROOMS "cave/"
#define ELE  ROOMS "ele/"
#define FORT  ROOMS "fort/"
#define FUN  ROOMS "fun/"
#define GAR  ROOMS "gar/"
#define HAM  ROOMS "ham/"
#define SAB  ROOMS "sab/"
#define SPI  ROOMS "spi/"
#define TOWN  ROOMS "town/"
#define UMI  ROOMS "umi/"
#define WATER  ROOMS "water/"
#define HIVE  ROOMS "hive/"
#endif
