/*  Player House .h file
 */
string SetOwner(string);
string GetOwner();
string SetCurrentBidder(string);
string GetCurrentBidder();
mixed SetKiller(mixed);
mixed GetKiller();
mapping SetSaleInventory(mapping);
mapping GetSaleInventory();
mapping AddSaleInventory(string, int, string);
mapping RemoveSaleInventory(string);
int SetSaleCost(string, int);
int AddSaleCost(string, int);
int GetSaleCost(string);
int SetInnkeep(int);
int GetInnkeep();
int SetMeatCost(string, int);
int GetMeatCost(string);
int SetMad(int);
int GetMad();
int AddMad(int);
int SetCurrentBid(int);
int GetCurrentBid();
int SetStoreFunds(int);
int GetStoreFunds();
int AddStoreFunds(int);
int SetMeatPoints(int);
int AddMeatPoints(int);
int GetMeatPoints();
int SetMeat(string, int);
int AddMeat(string, int);
int GetMeat(string);
string SetHouseId(string);
string GetHouseId();
string SetLocalCurrency(string);
string GetLocalCurrency();
string SetHouseName(string);
string GetHouseName();
string SetHouseDesc(string);
string GetHouseDesc();
int SetPayOut(string, int);
int RemovePayOut(string);
int GetPayOut(string);
mapping GetHouseInfo();
mapping GetPayOuts();
void ChooseInvOption(string);
void ChooseMakeOption(string);
void ChoosePriceOption(string);
void ChooseFundsOption(string);
void ChooseSetupOption(string);
void AddInvItem(string);
void RemoveInvItem(string);
void MakeFood(string);
void DoPrice(string, string);
void DoSalePrice(string, string);
void MakeInnkeeper();
void SetupHouseName(string);
void SetupHouseDesc(string);
void DepositFunds(string);
void WithdrawFunds(string);
void ChooseAmount(string, string);
nosave void LoadInventory();
