#ifndef _STD_H_
#define _STD_H_
#define OBJECT "/std/object"
#define LIVING "/std/living"
#define MONSTER "/std/monster"
#define UNDEAD "/std/undead"
#define CONTAINER "/std/container"
#define ROOM "/std/room"
#define LAVA "/std/weather/lava"
#define WEATHER "/std/weather/weather"
#define DAEMON "/std/daemon"
#define BODY "/std/living/body"
#define SKILLS "/std/living/skills"
#define AFFLICTIONS "/std/living/afflictions"
#define RESISTANCES "/std/resistances"
#define PIER "/std/pier"
#define PERIODIC_ROOM "/std/periodic_room"
#define PERIODIC "/std/periodic"
#define VAULT "/std/vault"
#define WEAPON "/std/weapon"
#define ARMOUR "/std/armour"
#define MOUNT   "/std/ride"
#define PET "/std/pet"
#define BAG "/std/bag_logic"
#define PACK "/std/backpack"
#define LOCKER "/std/locker"
#define BARKEEP "/std/barkeep"
#define BOW "/std/bow"
#define QUIVER "/std/quiver"
#define INSTANCE "/std/instance"
#define BBOARD "/std/bboard"
#define HALL "/std/room/hall"
#define MOVE "/std/move"
#define GUILD "/std/guild"
#define POISON "/std/poison"
#define SPELL "/std/spell"
#define FOOD "/std/food"
#define DRINK "/std/drink"
#define PK_BOOK "/std/obj/book"
#define OLD_SPELL "/std/bak/spell"
#define SONG "/std/song"
#define OIL "/std/oil"
#define OINTMENT "/std/ointment"
#define SEAL "/std/seal"
#define OBMOUNT "/std/obmount"
#define SENSES "/std/senses"
#define SENSE_CMD "/std/obj/sensecmd"
#define SKIN "/std/obj/skin"
#define VENDOR "/std/vendor"
#define BEACH "/std/beach"
#define DOCKS "/std/docks"
#define GERM "/wizards/inferno/germ"
#define LOGGER "/std/logger"
#define AIRPORT "/std/room/airport"
#define SKY_ROOM "/std/room/sky_room"
#define VIRTUAL "/std/virtual/"
#define VIRTUALMAP VIRTUAL+"virtualmap"
#define VMAPROOM VIRTUAL+"vmaproom"
#define VIRTUALROOM VIRTUAL+"vroom"
#define VIRTUALSERVER VIRTUAL+"vserver"

//  Guild defines -  Whit Jan, 07
#define VOTE "/std/guild/vote"
#define TREASURY "/std/guild/treasury"
#define GUILDRING "/std/guild/ring"
#define STONE "/std/stone"
#define DESERT "/std/desert"
#define BREEZE "/std/breeze"

#define OCEAN "/std/ocean"

#endif
