#ifndef _TEST_STD_H_
#define _TEST_STD_H_
#define OBJECT "/std/test/object"
#define LIVING "/std/test/living"
#define MONSTER "/std/test/monster"
#define UNDEAD "/std/test/undead"
#define CONTAINER "/std/test/container"
#define ROOM "/std/test/room"
#define SENSES "/std/senses"
#define LAVA "/std/test/weather/lava"
#define WEATHER "/std/test/weather/weather"
#define DAEMON "/std/test/daemon"
#define BODY "/std/test/living/body"
#define SKILLS "/std/test/living/skills"
#define AFFLICTIONS "/std/test/living/afflictions"
#define PIER "/std/test/pier"
#define PERIODIC_ROOM "/std/test/periodic_room"
#define VAULT "/std/test/vault"
#define WEAPON "/std/test/weapon"
#define ARMOUR "/std/test/armour"
#define MOUNT   "/std/test/ride"
#define BAG "/std/test/bag_logic"
#define PACK "/std/test/backpack"
#define LOCKER "/std/test/locker"
#define BARKEEP "/std/test/barkeep"
#define BOW "/std/test/bow"
#define QUIVER "/std/test/quiver"
#define VIRTUALROOM "/std/test/vroom"
#define VIRTUALSERVER "/std/test/vserver"
#define BBOARD "/std/test/bboard"
#define HALL "/std/test/room/hall"
#define MOVE "/std/test/move"
#define GUILD "/std/test/guild"
#define POISON "/std/test/poison"
#define SPELL "/std/test/spell"
#define FOOD "/std/test/food"
#define DRINK "/std/test/drink"
#define PK_BOOK "/std/test/obj/book"
#define OLD_SPELL "/std/test/bak/spell"
#define SONG "/std/test/song"
#define OIL "/std/test/oil"
#define OINTMENT "/std/test/ointment"
#define SEAL "/std/test/seal"
#define OBMOUNT "/std/test/obmount"
#define VENDOR "/std/test/vendor"
#define BEACH "/std/test/beach"
#define DOCKS "/std/test/docks"
#define GERM "/wizards/inferno/germ"
#define LOGGER "/std/test/logger"
#define AIRPORT "/std/test/room/airport"
#define SKY_ROOM "/std/test/room/sky_room"
//  Guild defines -  Whit Jan, 07
#define VOTE "/std/test/guild/vote"
#define TREASURY "/std/test/guild/treasury"
#define GUILDRING "/std/test/guild/ring"
#define STONE "/std/test/stone"
#define DESERT "/std/test/desert"
#define BREEZE "/std/test/breeze"

#define OCEAN "/std/test/ocean"

#endif
