mapping *dest = ({
 ([ "name":"chengmen",
           "context": ({
"/d/kaifeng/chen1",
"/d/kaifeng/chen2",
"/d/kaifeng/tieta",
"/d/kaifeng/taishan/tulu1",
"/d/kaifeng/taishan/tulu2",
"/d/kaifeng/taishan/shulin1",
"/d/kaifeng/taishan/shulin2",
"/d/kaifeng/taishan/daizong",
"/d/kaifeng/taishan/yidao3",
"/d/kaifeng/taishan/yidao2",
"/d/kaifeng/tieta",
"/d/kaifeng/chengmen",
})]),

 ([ "name":"daizong",
           "context": ({
"/d/kaifeng/taishan/baihe",
"/d/kaifeng/taishan/yitian",
"/d/kaifeng/taishan/doumo",
"/d/kaifeng/taishan/shijin",
"/d/kaifeng/taishan/huima",
"/d/kaifeng/taishan/ertian",
"/d/kaifeng/taishan/wudafu",
"/d/kaifeng/taishan/longmen",
"/d/kaifeng/taishan/shengxian",
"/d/kaifeng/taishan/nantian",
"/d/kaifeng/taishan/yueguan",
"/d/kaifeng/taishan/xitian",
})]),
 ([ "name":"beiyin1",
           "context": ({
"/u/city/beiyin2",
"/u/city/jiuguan",
"/u/city/beiyin4",
"/u/city/beiyin5",
"/u/city/zahuopu",
"/u/city/minju4",
"/u/city/zhuque-s4",
"/d/eastway/wangnan5",
"/d/eastway/wangnan4",
"/d/eastway/jinshi",
"/d/eastway/beilin1",
"/d/eastway/beilin2
",
})]),
 ([ "name":"ciensiw",
           "context": ({
"/d/eastway/ciensi",
"/d/eastway/dyt","/d/eastway/dyt1",
"/d/eastway/dyt2",
"/d/eastway/dyt3",
"/d/eastway/dyt4",
"/d/eastway/dyt5",
"/d/eastway/dyt6",
"/d/eastway/dyt7",
"/d/eastway/dyt",
"/d/eastway/ciensi",
"/d/eastway/ciensiw",
})]),
 ([ "name":"nanchengkou",
           "context": ({
"/d/changan/sbridge",
"/d/changan/broadway1",
"/d/changan/zhongnan.lpc",
"/d/changan/broadway2",
"/d/changan/nanyue",
"/d/changan/broadway3",
"/d/changan/broadway4",
"/d/changan/broadway5",
"/d/jz/sibei-w3",
"/d/jz/sibei-w2",
"/d/jz/sibei-w1",
"/d/jz/center",
})]),
 ([ "name":"ngate",
           "context": ({
"/d/jz/road1",
"/d/jz/road2",
"/d/jz/road3",
"/d/meishan/denglong1",
"/d/meishan/denglong2",
"/d/meishan/denglong3",
"/d/meishan/erlangwai",
"/d/meishan/fenglin1",
"/d/meishan/sengquan",
"/d/meishan/zhaoyun",
"/d/meishan/jixian",
"/d/meishan/feifeng",
})]),

});


