mapping *dest = ({
 ([ "name":"shijianshi",
           "context": ({
"/d/suzhou/qianrenshi",
"/d/suzhou/wjszhuang",
"/d/suzhou/toushanmen",
"/d/suzhou/huqiushan",
"/d/suzhou/qsgdao6",
"/d/city/sroad1",
"/d/city/jiangnan",
"/d/city/sroad1",
"/d/suzhou/qsgdao6",
"/d/suzhou/northgate",
"/d/suzhou/beidajie2",
"/d/suzhou/beidiajie1",
})]),

 ([ "name":"caixiangjing",
           "context": ({
"/d/suzhou/shuiwa1",
"/d/suzhou/shiyuan",
"/d/suzhou/yingxiaoting",
"/d/suzhou/lingyanshan",
"/d/suzhou/tianpingshan",
"/d/suzhou/shihu",
"/d/suzhou/tianpingshan",
"/d/suzhou/baiyunquan",   
"/d/suzhou/tianpingshan",
"/d/suzhou/qsgdao",
"/d/suzhou/qsgdao1",
"/d/suzhou/qsgdao2",
})]),
([ "name":"chitang",
           "context": ({
"/d/suzhou/gumujiaohe",
"/d/suzhou/hehuating",
"/d/suzhou/liuyuan",
"/d/suzhou/nandajie2",
"/d/suzhou/tingyuxuan",
"/d/suzhou/nandajie2",
"/d/suzhou/nandajie1",
"/d/suzhou/shizilin",
"/d/suzhou/zhibaixuan",
"/d/suzhou/shizilin",
"/d/suzhou/baodaiqiao",
})]),
([ "name":"baodaiqiao",
           "context": ({
"/d/suzhou/canglangting",
"/d/suzhou/xidajie1",
"/d/suzhou/xidajie2",
"/d/suzhou/xuanmiaoguan",
"/d/suzhou/xidajie1",
"/d/suzhou/westgate",
"/d/suzhou/qsgdao3",
"/d/suzhou/qsgdao4",
"/d/suzhou/qsgdao5",
"/d/suzhou/hanshansi",
"/d/suzhou/zhengdian",
})]),

});

