
nosave mapping domain_cost = ([
  "city" : ([ "cost" : 10000000, // 2000 gold.
              "max"  : 20,       //此区域最多可建 10 套房子。
                                 //-1 代表不限制数量,此区域内
                                 //只要符合建房条件的地方就可以建.
              "min_level" : 4,   //在此区域建房要求的最低房屋等级.
           ]),                   //1 就代表不限制最低房屋等级了.
  "luoyang" : ([ "cost" : 9000000,
                 "max"  : 20,
                 "min_level" : 3,
              ]),

  "beiping" : ([ "cost" : 5000000,
                 "max"  : 10,
                 "min_level" : 2,
               ]),
  "changan-e" : ([ "cost" : 6000000,
                   "max"  : 20,
                   "max_level" : 3,
                ]),

  "changan-s" : ([ "cost" : 6000000,
                   "max"  : 20,
                   "max_level" : 3,
                ]),

  "chengdu" : ([ "cost" : 5000000,
                 "max"  : 10,
                 "min_level" : 2,
              ]),
  "guanwai" : ([ "cost" : 4000000,
                 "max"  : 6,
                 "max_level" : 2,
              ]),
  "hangzhou" : ([ "cost" :  9000000,
                  "max"  :  20,
                  "min_level" : 3,
               ]),
  "jingzhou" : ([ "cost" :  5000000,
                  "max"  :  10,
                  "min_level" : 2,
               ]),

  "kaifeng" : ([ "cost" : 7000000,
                 "max"  :  12,
                 "min_level" : 2,
              ]),
  "kunming" : ([ "cost" : 5000000,
                 "max"  :  12,
                 "max_level" : 3,
              ]),
  "lanzhou" : ([ "cost" : 4000000,
                 "max"  :  20,
                 "max_level" : 3,
              ]),
  "lingzhou" : ([ "cost" : 4000000,
                 "max"  :  20,
                 "max_level" : 3,
              ]),
  "suzhou" : ([ "cost" : 8000000,
                 "max"  :  20,
                 "min_level" : 3,
              ]),
  "yangzhou" : ([ "cost" : 7000000,
                 "max"  :  20,
                 "min_level" : 3,
              ]),
  "emei" : ([ "cost" : 3000000,
              "max"  :  10,
              "max_level" : 2,
           ]),
  "huashan" : ([ "cost" : 2000000,
              "max"  :  10,
              "max_level" : 1,
           ]),
  "hengshan" : ([ "cost" : 1500000,
              "max"  :  10,
              "max_level" : 1,
           ]),
  "henshan" : ([ "cost" : 3500000,
              "max"  :  10,
              "max_level" : 2,
           ]),
  "songshan" : ([ "cost" : 2000000,
              "max"  :  10,
              "max_level" : 1,
           ]),
  "taishan" : ([ "cost" : 1500000,
              "max"  :  10,
              "max_level" : 1,
           ]),
  "wutaishan" : ([ "cost" : 2000000,
              "max"  :  10,
              "max_level" : 2,
           ]),
]);