string day_event()
{
  return NATURE_D->outdoor_room_event();
}

string *path=({
        "/d/beiping/",
        "/d/changan-e/",
        "/d/changan-s/",
        "/d/chengdu/",
        "/d/city/",
        "/d/emei/",
        "/d/guanwai/",
        "/d/hangzhou/",
        "/d/hengshan/",
        "/d/henshan/",
        "/d/huashan/",
        "/d/jingzhou/",
        "/d/jjf/",
        "/d/kaifeng/",
        "/d/kunming/",
        "/d/lanzhou/",
        "/d/lingzhou/",
        "/d/luoyang/",
        "/d/moon/",
        "/d/songshan/",
        "/d/suzhou/",
        "/d/taishan/",
        "/d/wutaishan/",
        "/d/yangzhou/",
        "/d/qujing/baotou/",
        "/d/qujing/baoxiang/",
        "/d/qujing/bibotan/",
        "/d/qujing/biqiu/",
        "/d/qujing/chechi/",
        "/d/qujing/dudi/",
        "/d/qujing/fengxian/",
        "/d/qujing/heifeng/",
        "/d/qujing/huangfeng/",
        "/d/qujing/jilei/",
        "/d/qujing/jindou/",
        "/d/qujing/jingjiling/",
        "/d/qujing/jinping/",
        "/d/qujing/jisaiguo/",
        "/d/qujing/liusha/",
        "/d/qujing/maoying/",
        "/d/qujing/nuerguo/",
        "/d/qujing/pansi/",
        "/d/qujing/pingding/",
        "/d/qujing/qilin/",
        "/d/qujing/qinfa/",
        "/d/qujing/qinglong/",
        "/d/qujing/shuangcha/",
        "/d/qujing/tianzhu/",
        "/d/qujing/tongtian/",
        "/d/qujing/wuji/",
        "/d/qujing/xiaoxitian/",
        "/d/qujing/yinwu/",
        "/d/qujing/yuhua/",
        "/d/qujing/zhujie/",
        "/d/qujing/zhuzi/",
});
string *name=({
        HIW U"北平府"NOR,
        HIW U"长安东"NOR,
        HIW U"长安南"NOR,
        HIW U"成都"NOR,
        HIW U"长安城内"NOR,
        HIW U"峨眉山"NOR,
        HIW U"关外"NOR,
        HIW U"杭州"NOR,
        HIW U"恒山"NOR,
        HIW U"衡山"NOR,
        HIW U"华山"NOR,
        HIW U"荆州"NOR,
        HIW U"将军府"NOR,
        HIW U"开封"NOR,
        HIW U"昆明"NOR,
        HIW U"兰州"NOR,
        HIW U"灵州"NOR,
        HIW U"洛阳"NOR,
        HIW U"昆仑山月宫"NOR,
        HIW U"嵩山"NOR,
        HIW U"苏州"NOR,
        HIW U"泰山"NOR,
        HIW U"五台山"NOR,
        HIW U"扬州"NOR,
        HIW U"豹头山附近"NOR,
        HIW U"宝象国附近"NOR,
        HIW U"碧波潭附近"NOR,
        HIW U"比丘国附近"NOR,
        HIW U"车迟国附近"NOR,
        HIW U"毒敌山附近"NOR,
        HIW U"凤仙郡附近"NOR,
        HIW U"黑风山附近"NOR,
        HIW U"黄风岭附近"NOR,
        HIW U"积雷山附近"NOR,
        HIW U"金兜山附近"NOR,
        HIW U"荆棘岭附近"NOR,
        HIW U"金平府附近"NOR,
        HIW U"祭赛国附近"NOR,
        HIW U"流沙河附近"NOR,
        HIW U"毛颖山附近"NOR,
        HIW U"女儿国附近"NOR,
        HIW U"盘丝岭附近"NOR,
        HIW U"平顶山附近"NOR,
        HIW U"麒麟山附近"NOR,
        HIW U"钦法国附近"NOR,
        HIW U"青龙山附近"NOR,
        HIW U"双叉岭附近"NOR,
        HIW U"天竺国附近"NOR,
        HIW U"通天河附近"NOR,
        HIW U"乌鸡国附近"NOR,
        HIW U"小西天附近"NOR,
        HIW U"隐雾山附近"NOR,
        HIW U"玉华县附近"NOR,
        HIW U"竹节山附近"NOR,
        HIW U"朱紫国附近"NOR,
});

// 风霜雨雪区域信息显示
string *nameW=({
        HIY"大唐北平府"NOR,
        HIY"大唐长安东"NOR,
        HIY"大唐长安南"NOR,
        HIY"大唐成都"NOR,
        HIY"大唐长安城内"NOR,
        HIY"大唐峨眉山"NOR,
        HIY"大唐关外"NOR,
        HIY"大唐杭州"NOR,
        HIY"大唐恒山"NOR,
        HIY"大唐衡山"NOR,
        HIY"大唐华山"NOR,
        HIY"大唐荆州"NOR,
        HIY"大唐将军府"NOR,
        HIY"大唐开封"NOR,
        HIY"大唐昆明"NOR,
        HIY"大唐兰州"NOR,
        HIY"大唐灵州"NOR,
        HIY"大唐洛阳"NOR,
        HIY"昆仑山月宫"NOR,
        HIY"大唐嵩山"NOR,
        HIY"大唐苏州"NOR,
        HIY"大唐泰山"NOR,
        HIY"大唐五台山"NOR,
        HIY"大唐扬州"NOR,
        HIY"西域豹头山"NOR,
        HIY"西域宝象国"NOR,
        HIY"西域碧波潭"NOR,
        HIY"西域比丘国"NOR,
        HIY"西域车迟国"NOR,
        HIY"西域毒敌山"NOR,
        HIY"西域凤仙郡"NOR,
        HIY"西域黑风山"NOR,
        HIY"西域黄风岭"NOR,
        HIY"西域积雷山"NOR,
        HIY"西域金兜山"NOR,
        HIY"西域荆棘岭"NOR,
        HIY"西域金平府"NOR,
        HIY"西域祭赛国"NOR,
        HIY"西域流沙河"NOR,
        HIY"西域毛颖山"NOR,
        HIY"西域女儿国"NOR,
        HIY"西域盘丝岭"NOR,
        HIY"西域平顶山"NOR,
        HIY"西域麒麟山"NOR,
        HIY"西域钦法国"NOR,
        HIY"西域青龙山"NOR,
        HIY"西域双叉岭"NOR,
        HIY"西域天竺国"NOR,
        HIY"西域通天河"NOR,
        HIY"西域乌鸡国"NOR,
        HIY"西域小西天"NOR,
        HIY"西域隐雾山"NOR,
        HIY"西域玉华县"NOR,
        HIY"西域竹节山"NOR,
        HIY"西域朱紫国"NOR,
});
