//edit by landy 2007.06

string *wanted_list = ({
        "/clone/drug/badan.lpc",            // 巴丹
        "/clone/drug/baicao-dan.lpc",       // 百草丹
        "/clone/drug/baihu.lpc",            // 白虎夺命丸
        "/clone/drug/baodan.lpc",           // 豹子胆
        "/clone/drug/bmdan.lpc",            // 天王保命丹
        "/clone/drug/buyin-wan.lpc",        // 补阴丸
//        "/clone/drug/cb_renshen.lpc",       // 人参
        "/clone/drug/dahuan-dan.lpc",       // 大还丹
        "/clone/drug/dali-wan.lpc",         // 金刚大力丸
        "/clone/drug/danggui.lpc",          // 当归
        "/clone/drug/dilong-wan.lpc",       // 通犀地龙丸
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushegao.lpc",         // 百花腹蛇膏
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/guiyuan.lpc",          // 归元丹
        "/clone/drug/heishi-dan.lpc",       // 玉洞黑石丹
        "/clone/drug/huashi.lpc",           // 化尸粉
//        "/clone/drug/hugu.lpc",             // 虎骨
        "/clone/drug/huiyang-san.lpc",      // 回阳五龙散
        "/clone/drug/hulipi.lpc",           // 狐狸皮
        "/clone/drug/huxin.lpc",            // 天王护心丹
        "/clone/drug/jinchuang.lpc",        // 金创药
        "/clone/drug/jueqing-dan.lpc",      // 绝情丹
        "/clone/drug/lingzhi.lpc",          // 灵芝
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/pldan.lpc",            // 破立丹
        "/clone/drug/puti-zi.lpc",          // 菩提子
        "/clone/drug/sanhuang-wan.lpc",     // 三黄宝蜡丸
        "/clone/drug/shanshen.lpc",         // 老山参
        "/clone/drug/shedan.lpc",           // 毒蛇胆
        "/clone/drug/sheli-zi.lpc",         // 舍利子
        "/clone/drug/sheyao.lpc",           // 蛇药
        "/clone/drug/shouwu.lpc",           // 何首乌
        "/clone/drug/sl_jinchuang.lpc",     // 金创药
        "/clone/drug/swjing.lpc",           // 首乌精
        "/clone/drug/tianqi-san.lpc",       // 田七鲨胆散
        "/clone/drug/tianxiang.lpc",        // 天香断续膏
        "/clone/drug/tianxin.lpc",          // 天心解毒丹
        "/clone/drug/wuchang-dan.lpc",      // 无常丹
        "/clone/drug/xh-wan.lpc",           // 雄黄丸
        "/clone/drug/xiaohuan-dan.lpc",     // 小还丹
        "/clone/drug/xiongdan.lpc",         // 熊胆
        "/clone/drug/xiongdan-wan.lpc",     // 白云熊胆丸
        "/clone/drug/xuelian.lpc",          // 雪莲
        "/clone/drug/xueteng.lpc",          // 大血藤
        "/clone/drug/xxqingxin-san.lpc",    // 清心散
        "/clone/drug/yangjing.lpc",         // 养精丹
        "/clone/drug/yangrong-wan.lpc",     // 人参养荣丸
        "/clone/drug/renshen_guo.lpc",      // 人参果
        "/clone/drug/yulu-wan.lpc",         // 九花玉露丸
        "/clone/drug/yuzhen-san.lpc",       // 玉真散
        "/clone/drug/zuixian-mi.lpc",       // 醉仙蜜
//------------------------------------------------
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/mangshe-dan.lpc",      // 蟒蛇胆
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/menghan_yao.lpc",      // 蒙汗药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/gaoyao.lpc",           // 狗皮膏药
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
        "/clone/drug/fushedan.lpc",         // 腹蛇胆
});
