string *dirs1 = ({
        "/d/qujing/baotou", "/d/qujing/baoxiang", "/d/qujing/biqiu","/d/qujing/chechi",
        "/d/qujing/dudi","/d/qujing/fengxian","/d/qujing/firemount","/d/qujing/jilei",
        "/d/qujing/jindou","/d/qujing/jinping","/d/qujing/jisaiguo","/d/qujing/jingjiling",
        "/d/qujing/maoying","/d/qujing/nuerguo","/d/qujing/pingding","/d/qujing/pansi",
        "/d/qujing/tongtian","/d/qujing/qilin","/d/qujing/qinfa","/d/qujing/qinglong",
        "/d/qujing/tianzhu","/d/qujing/wudidong","/d/qujing/wuzhuang","/d/qujing/wuji",
        "/d/qujing/xiaoxitian","/d/qujing/yinwu","/d/qujing/yuhua","/d/qujing/zhujie",
        "/d/qujing/zhuzi",
//"/d/kaifeng", 影响yunbiao任务，剔除开封
});

string *names = ({
        "孙坚","sun jian",      "王平","wang ping",     "王允","wang yun",      "徐晃","xu huang",
        "王朗","wang lang",     "公孙瓒","gongsun zan", "严白虎","yan baihu",   "纪灵","ji ling",
        "孔铀","kong you",      "鲁智深","lu zhishen",  "王双","wang shuang",   "邓艾","deng ai",
        "夏侯霸","xiahou ba",   "夏侯桀","xiahou jie",  "孙策","sun ce",        "曹仁","cao ren",
        "曹洪","cao hong",      "于禁","yu jin",        "李典","li dian",       "孟获","meng huo",
        "董卓","dong zhuo",     "刘封","liu feng",      "司马懿","sima yi",     "司马昭","sima zhao",
        "司马师","sima shi",    "管亥","guan hai",      "陶谦","tao qian",      "文丑","wen chou",
        "张颌","zhang he",      "姜维","jiang wei",     "夏侯渊","xiahou yuan", "曹操","cao cao",
        "宋江","song jiang",    "林冲","lin chong",     "史进","shi jin",       "马良","ma liang",
        "马谡","ma su",         "石秀","shi xiu",       "时迁","shi qian",      "严颜","yan yan",
        "武松","wu song",       "李魁","li kui",        "王英","wang ying",     "黄祖","huang zu",
        "徐庶","xu shu",        "陆逊","lu xun",        "吕蒙","lv meng",       "黄盖","huang gai",
        "晁盖","chao gai",      "张苞","zhang bao",     "关兴","guan xing",     "关平","guan ping",
        "关索","guan suo",      "赵统","zhao tong",     "司马炎","sima yan",    "曹彰","cao zhang",
        "程普","cheng pu",      "颜良","yan liang",     "许诸","xu zhu",        "典韦","dian wei",
        "吕布","lv bu",         "张辽","zhang liao",    "诸葛亮","zhuge liang", "孙权","sun quan",
        "关羽","guan yu",       "张飞","zhang fei",     "刘备","liu bei",       "周瑜","zhou yu",
        "甘宁","gang ning",     "马超","ma chao",       "赵云","zao yun",       "黄忠","huang zhong",
        "魏延","wei yan",       "曹丕","cao pi",        "曹植","cao zhi",       "曹熊","cao xiong",
        "袁绍","yuan shao",     "袁术","yuan shu",      "袁谭","yuan tan",      "袁熙","yuan xi",
        "袁尚","yuan shang",    "刘表","liu biao",      "刘琦","liu qi",        "刘琮","liu cong",
        "韩遂","han sui",       "马腾","ma teng",       "马铁","ma tie",        "张邈","zhang miao",
        "公孙度","gongsun du",  "公孙渊","gongsun yuan","公孙康","gongsun kang","张杨","zhang yang",
        "张燕","zhang yan",     "张绣","zhang xiu",     "张鲁","zhang lu",      "夏侯惇","xiahou dun",
        "韩浩","han hao",       "夏侯威","xiahou wei",  "夏侯惠","xiahou hui",  "夏侯和","xiahou he",
        "夏侯尚","xiahou shang","夏侯恩","xiahou en",   "曹纯","cao chun",      "曹休","cao xiu",
        "曹真","cao zhen",      "曹爽","cao shuang",    "荀彧","xun yu",        "荀攸","xun you",
        "贾诩","jia xu",        "田畴","tian chou",     "田丰","tian feng",     "沮授","ju shou",
        "郭图","guo tu",        "审配","shen pei",      "高览","gao lan",       "蒯良","kuai liang",
        "蒯越","kuai yue",      "陈宫","chen gong",     "崔琰","cui yan",       "毛玠","mao jie",
        "锺繇","zhong you",     "锺会","zhong hui",     "华歆","hua xin",       "程昱","cheng yu",
        "郭嘉","guo jia",       "董昭","dong zhao",     "刘晔","liu ye",        "贾逵","jia kui",
        "乐进","yue jin",       "李通","li tong",       "文聘","wen pin",       "吕虔","lu qian",
        "庞德","pang de",       "陈群","chen qun",      "辛毗","xin pi",        "杨阜","yang fu",
        "高堂隆","gao tanglong","蒋干","jiang gan",     "满宠","man chong",     "郝昭","hao zhao",
        "郭淮","guo huai",      "王基","wang ji",       "毌丘俭","wuqiu jian",  "诸葛诞","zhuge dan",
        "刘焉","liu yan",       "刘璋","liu zhang",     "刘禅","liu shan",      "庞统","pang tong",
        "法正","fa zheng",      "许靖","xu jing",       "麋竺","mi zhu",        "孙乾","sun qian",
        "简雍","jian yong",     "麋芳","mi fang",       "伊籍","yi ji",         "秦宓","qin mi",
        "刘巴","liu ba",        "董和","dong he",       "陈震","chen zhen",     "李严","li yan",
        "杨仪","yang yi",       "文鸯","wen yang",      "文钦","wen qin",       "向朗","xiang lang",
        "向宠","xiang chong",   "费诗","fei shi",       "霍峻","huo jun",       "黄权","huang quan",
        "李恢","li hui",        "张翼","zhang yi",      "廖化","liao hua",      "张任","zhang ren",
        "华雄","hua xiong",     "马忠","ma zhong",      "潘璋","pan zhang",     "蒋琬","jiang wan",
        "费祎","fei yi",        "邓芝","deng zhi",      "陈到","chen dao",      "刘繇","liu you",
        "太史慈","taishi ci",   "士燮","shi xie",       "孙静","sun jing",      "孙瑜","sun yu",
        "孙翊","sun yi",        "张昭","zhang zhao",    "顾雍","gu yong",       "诸葛瑾","zhuge jin",
        "诸葛恪","zhuge ke",    "诸葛瞻","zhuge zhan",  "虞翻","yu fan",        "步骘","bu zhi",
        "张纮","zhang hong",    "程秉","cheng bing",    "阚泽","kan ze",        "鲁肃","lu su",
        "韩当","han dang",      "蒋钦","jiang qin",     "周泰","zhou tai",      "陈武","chen wu",
        "董袭","dong xi",       "凌统","ling tong",     "凌操","ling cao",      "徐盛","xu sheng",
        "丁奉","ding feng",     "朱治","zhu zhi",       "朱然","zhu ran",       "朱桓","zhu huan",
        "全琮","quan cong",     "陆凯","lu kai",        "卢俊义","lu junyi",    "吴用","wu yong",
        "公孙胜","gongsun sheng","关胜","guan sheng",   "秦明","qin ming",      "呼延灼","huyan zhuo",
        "花荣","hua rong",      "柴进","chai jin",      "李应","li ying",       "朱仝","zhu tong",
        "董平","dong ping",     "张清","zhang qing",    "杨志","yang zhi",      "徐宁","xu ning",
        "索超","suo chao",      "戴宗","dai zong",      "刘唐","liu tang",      "穆弘","mu hong",
        "雷横","lei heng",      "李俊","li jun",        "阮小二","ruan xiaoer", "阮小五","ruan xiaowu",
        "阮小七","ruan xiaoqi", "张横","zhang heng",    "张顺","zhang shun",    "杨雄","yang xiong",
        "解珍","xie zhen",      "解宝","xie bao",       "燕青","yan qing",      "孙立","sun li",
        "穆春","mu chun",       "施恩","shi en",        "蔡福","cai fu",        "蔡庆","cai qing",
        "郑天寿","zheng tianshou","杨春","yang chun",   "郭盛","guo sheng",     "吕方","lu fang",
        "朱武","zhu wu",        "黄信","huang xin",     "臧洪","zang hong",     "臧霸","zang ba",
        "陈登","chen deng",
});

