#define BASE "/d/Dark/Keldros/linshara/"
#define ROOMS(x) BASE + "rooms/" +"x"
#define MON(x) BASE + "mon/" + "x"
#define ARMOR(x) BASE + "armor/" +"x"
#define WEAP(x) BASE + "weapons/" + "x"
#define OBJ(x) BASE + "obj/" + "x"
