//丐帮初级job
//jzad完成于2001 8.2


#include <ansi.h>
  mapping *wheres = ({
      (["short":                "大理北门",
       "place" :              "/d/dali/beidajie3",]),   
     (["short":                "峨嵋报国寺",
       "place" :              "/d/emei/baoguosi",]),
     (["short":                "扬州西门",
       "place" :              "/d/city/ximen",]),
     (["short":                "雪山土路",
       "place" :              "/d/xueshan/tulu2",]),
     (["short":                "石铺",
       "place" :              "/d/dali/zhubaodian",]),  
      (["short":                "扬州中央广场",
       "place" :              "/d/city/guangchang",]),  
      (["short":                "成都北大街",
       "place" :              "/d/city3/beijie1",]), 
      (["short":                "成都百花潭",
       "place" :              "/d/city3/cdta",]), 
      (["short":                "成都小巷",
       "place" :              "/d/city3/xiaoxiang",]), 
      (["short":                "北疆小镇",
       "place" :              "/d/xingxiu/beijiang",]), 
      (["short":                "乌鸦岭",
       "place" :              "/d/wudang/wuyalin",]), 
      (["short":                "峨嵋十二盘",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "峨嵋千佛庵",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "牛心亭",
       "place" :              "/d/emei/niuxinting",]), 
      (["short":                "明教厚土旗门",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "明教烈火旗后门",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
      (["short":                "泉州南门",
       "place" :              "/d/quanzhou/nanmen",]), 
      (["short":                "少林寺石阶",
       "place" :              "/d/shaolin/shijie8",]),
      (["short":                "华山猢狲愁",
       "place" :              "/d/huashan/husun",]),
      (["short":                "华山玉女峰",
       "place" :              "/d/huashan/yunu",]),
      (["short":                "慕容小径",
       "place" :              "/d/mr/xiaojing1-2",]),
      (["short":                "慕容柳树林",
       "place" :              "/d/mr/liulin",]),
      (["short":                "大理夕照路",
       "place" :              "/d/dali/xbdajie2",]),
      (["short":                "少林寺山门殿",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "天府广场",
       "place" :              "/d/city3/guangchang",]),
      (["short":                "雪山山脚",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "峨嵋九老洞",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "峨嵋古德林",
       "place" :              "/d/emei/gudelin",]),
       (["short":                "成都石拱桥",
       "place" :              "/d/city3/gongqiao",]),
       (["short":                "成都薛涛井",
       "place" :              "/d/city3/xuetao",]),
       (["short":                "成都府南河畔",
       "place" :              "/d/city3/funanhe1",]),
       (["short":                "汉水南岸",
       "place" :              "/d/nanyang/hanshui1",]),
       (["short":                "中条山密林",
       "place" :              "/d/huashan/jzroad5",]),
       (["short":                "天山脚下",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "华山脚下",
       "place" :              "/d/huashan/path1",]),
       (["short":                "平定州",
       "place" :              "/d/heimuya/pingdingzhou",]),
       (["short":                "乱石坡",
       "place" :              "/d/heimuya/road1",]),      
       ([ "short":                "华山村南村口",
          "place":                "/d/village/sexit",
        ]), ([       "short":                "玉皇顶",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "六盘山",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "天山山路",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "嘉峪关",
                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "西单北大街",
                "place":                "/d/city2/xidan1",
        ]),([      "short":                "嘉兴南湖",
                "place":                "/d/quanzhou/nanhu",
        ]),([      "short":                "王府井大街",
                "place":                "/d/city2/wangfu2",
        ]),([      "short":                "破旧长城",
                "place":                "/d/gaochang/room3",
        ]),([      "short":                "龙门客栈",
                "place":                "/d/gaochang/room16",
        ]),([      "short":                "老龙头",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "嘉兴城",
                "place":                "/d/quanzhou/jiaxing",
        ]),([      "short":                "扬州西门",
                "place":                "/d/city/ximen",
        ]),([      "short":                "星星峡",
                "place":                "/d/gaochang/room52",
        ]),([      "short":                "一天门",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "小土屋",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "铁索桥",
                "place":                "/d/heimuya/zhaoze/tsq",
        ]),([      "short":                "澜沧江畔",
                 "place":                "/d/heimuya/zhaoze/lczb",
        ]),([      "short":                "无量山界",
                 "place":                "/d/heimuya/zhaoze/pubu",
        ]),([      "short":                "蜀道",
                 "place":                "/d/city3/shudao3",
        ]),([      "short":                "朝天门",
                 "place":                "/d/songshan/chaotian",
        ]),([      "short":                "碧水神潭",
                 "place":                "/d/nanyang/shuitan",
        ]),([      "short":                "铁梁峡",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "峻极禅院山门",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "嵩山",
                 "place":                "/d/songshan/songshan",
        ]),([      "short":                "终南山大校场",
                 "place":                "/d/gumu/daxiaochang",
        ]),([      "short":                "天中阁",
                 "place":                "/d/songshan/tianzhongge",
        ]),([      "short":                "平心石",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "千尺幢",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "山洪瀑布",
                 "place":                "/d/huashan/shanhongpb",
        ]),([      "short":                "清音阁",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "十二盘",
                 "place":                "/d/emei/shierpan1",
        ]),([      "short":                "白龙洞",
                 "place":                "/d/emei/bailongdong",
        ]),([      "short":                "清音阁外",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "千佛庵",
                 "place":                "/d/emei/qianfoan",
        ]),([      "short":                "龙升坪",
                 "place":                "/d/emei/lshenggang",    
          ]),([      "short":                "中天门",
                   "place":                "/d/gumu/ztm",
          ]),([      "short":                "洪水旗山崖",
                   "place":                "/d/mingjiao/shanya",
          ]),([      "short":                "烈火旗大门",
                   "place":                "/d/mingjiao/lhqmen",
          ]),([      "short":                "雪山寺山门",
                   "place":                "/d/xueshan/shanmen",
          ]),([      "short":                "洪水旗大门",
                   "place":                "/d/mingjiao/hsqmen",
          ]),([      "short":                "青石大道",
                   "place":                "/d/wudang/wdroad1",
          ]),([      "short":                "北码头",
                   "place":                "/d/nanyang/matou2",
          ]),([      "short":                "大驿道",
                   "place":                "/d/taishan/yidao",
          ]),([      "short":                "太乙湖",
                   "place":                "/d/quanzhen/taiyihu",
          ]),([      "short":                "终南山脚",
                   "place":                "/d/quanzhen/shanjiao",
          ]),([      "short":                "樊川",
                  "place":                "/d/quanzhen/fanchuan",
          ]),([      "short":                "函谷关",
                   "place":                "/d/wugongzhen/hanguguan",
          ]),([      "short":                "小村庄",
                   "place":                "/d/wugongzhen/xiaocun",
          ]),([      "short":                "星宿海",
                   "place":                "/d/xingxiu/xxh2",
         ]),([      "short":                "天山脚下",
                   "place":                "/d/xingxiu/shanjiao",
          ]),([      "short":                "丝绸之路",
                   "place":                "/d/xingxiu/silk2",
          ]),([      "short":                "长安城西门",
                   "place":                "/d/changan/ximen",
          ]),([      "short":                "长安城东门",
                   "place":                "/d/changan/dongmen",
          ]),([      "short":                "上天梯",
                   "place":                "/d/huashan/shangtianti",
          ]),([      "short":                "树林",
                   "place":                "/d/xiaoyao/shulin3",
          ]),([      "short":                "南大街",
                   "place":                "/d/city/nandajie2",
        ]),     
          });
mapping query_quest()
{
    return wheres[random(sizeof(wheres))];
}
