/d/lingtai/npc/puti
/d/nanhai/npc/guanyin
/d/death/npc/pang
/d/death/npc/yanluowang
/d/moon/npc/change
/d/city/npc/yuantiangang
/d/meishan/npc/erlang
/d/pantao/npc/taibai
/d/jjf/npc/luocheng
/d/qujing/xihai/npc/taizi
/d/qujing/wuzhuang/npc/zhenyuan
/d/xueshan/npc/kongque-gongzhu
/d/xueshan/npc/shenying-shizhe
/d/qujing/nuerguo/npc/princess
/d/qujing/bibotan/npc/dragon
/d/qujing/tianzhu/npc/realgirl
/d/qujing/wuji/npc/longwang
/d/qujing/jingjiling/npc/xing
/d/qujing/wudidong/npc/yushu
/d/sea/npc/long8
/d/qujing/lingshan/npc/rulai
/d/qujing/jilei/npc/niumo
/d/qujing/qilin/npc/queen
/d/qujing/heishui/npc/heshen
/d/qujing/zhujie/npc/shi
/d/qujing/huangfeng/npc/lingjipusa
